### ISSUE TITLE
[Bug] 清理最近聊天失效

### ISSUE THREAD

**Issue by Seukieee** [cinit/QAuxiliary#1006]
### Steps to reproduce/复现步骤

1.长按右上角加号
2.清理最近聊天

### Expected behaviour/预期行为

最近聊天被清理，主页没有多余的

### Actual behaviour/实际行为

长按后页面无反应，聊天列表保持原样

### Xposed Framework you used/你使用的Xposed框架

Npatch

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### Module Version/模块版本

1.5.1.r2102.a3e8397

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2102.a3e8397
QQ9.0.60(6478)
PID: 9965, UID: 10252
xyz.nextalone.hook.CleanRecentChat
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
top.linl.util.reflect.ReflectException: 没有查找到方法 : com.tencent.mobileqq.activity.home.Conversation.onResume(boolean)
	at top.linl.util.reflect.MethodTool.get(MethodTool.java:120)
	at top.linl.hook.FixCleanRecentChat.loadHook(FixCleanRecentChat.java:103)
	at xyz.nextalone.hook.CleanRecentChat.initOnce$lambda$8(CleanRecentChat.kt:96)
	at xyz.nextalone.hook.CleanRecentChat.$r8$lambda$ku6WbMO1yCcTrWLye4NhakmmIsg(CleanRecentChat.kt:0)
	at xyz.nextalone.hook.CleanRecentChat$$ExternalSyntheticLambda6.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at xyz.nextalone.hook.CleanRecentChat.initOnce(CleanRecentChat.kt:93)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:218)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:166)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2636)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2602)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8337)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7841)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7493)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8772)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by HdShare** [comment]
尝试最新CI版
