### ISSUE TITLE
[Bug] QQ9.0.0.14110 明显闪退

### ISSUE THREAD

**Issue by Delta-cloudy** [cinit/QAuxiliary#1010]
### Steps to reproduce/复现步骤

更新 1.5.1 Qauxaliary 
QQ 版本不变
打开后开了新功能，有可能问题在这

此问题个人无法解决

### Expected behaviour/预期行为

正常运行

### Actual behaviour/实际行为

十秒左右闪退，设置不闪退

### Xposed Framework you used/你使用的Xposed框架

LSPatch

### Your Android version/你使用的安卓系统版本

Android 13

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### Module Version/模块版本

1.5.1

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

（此问题找不到详细日志）

**Comment by Delta-cloudy** [comment]
# 版本变化1.5.0--1.5.1

**Comment by HdShare** [comment]
> # 版本变化1.5.0--1.5.1
> 1.5.0无闪退现象

尝试使用二分法排查一下哪个功能导致的

**Comment by Delta-cloudy** [comment]
> > # 版本变化1.5.0--1.5.1
> > 1.5.0无闪退现象
> 
> 尝试使用二分法排查一下哪个功能导致的

#（无效）关闭了所有新功能，无法解决

*我先降级吧

**Comment by klxiaoniu** [comment]
哪个功能导致的也不能提供，crash log也不提供，算命吗

**Comment by Delta-cloudy** [comment]
> 哪个功能导致的也不能提供，crash log也不提供，算命吗

你们 qa 的 crash log 我找不到哇

**Comment by Lesnao** [comment]
同样问题，不过我是8.9.93

从lsp找的可能是异常日志

modules_2024-06-14T12_21_06.041368.log
`
[ 2024-06-14T12:21:18.394    10334: 13285: 13707 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(Unknown Source:18)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.f(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.i(Unknown Source:0)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.a.run(Unknown Source:4)
	at com.tencent.mobileqq.app.Job.run(P:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
`

verbose_2024-06-14T12_21_08.112558.log
`
[ 2024-06-14T12:21:18.394    10334: 13285: 13707 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(Unknown Source:18)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.f(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.i(Unknown Source:0)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.a.run(Unknown Source:4)
	at com.tencent.mobileqq.app.Job.run(P:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
[ 2024-06-14T12:21:18.394    10334: 13285: 13707 E/AndroidRuntime  ] FATAL EXCEPTION: thread_sp_file_2
Process: com.tencent.mobileqq, PID: 13285
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(Unknown Source:18)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAHelper$checkAndDownload$1.invoke(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.f(P:1)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.LIAConfigManager.i(Unknown Source:0)
	at com.tencent.qqnt.biz.lightbusiness.lightinteraction.a.run(Unknown Source:4)
	at com.tencent.mobileqq.app.Job.run(P:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
`

dmesg没找到与qq相关的日志

**Comment by HdShare** [comment]
> 同样问题，不过我是8.9.93

```text
java.lang.IllegalStateException: Fragment already added: FriendFragment
```
目前已知精简联系人可能抛出以上异常
尝试使用二分法排查一下你具体是哪个功能导致的

**Comment by Lesnao** [comment]
> > 同样问题，不过我是8.9.93
> 
> ```
> java.lang.IllegalStateException: Fragment already added: FriendFragment
> ```
> 
> 目前已知精简联系人可能抛出以上异常 尝试使用二分法排查一下你具体是哪个功能导致的

没开启此功能，选择0项，不过倒是测出来了

是 主页 - 禁用轻互动 功能导致的
开启后 在 消息 页面停留时，过几秒就会闪退。

**Comment by Lesnao** [comment]
> > > 同样问题，不过我是8.9.93
> > 
> > 
> > ```
> > java.lang.IllegalStateException: Fragment already added: FriendFragment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目前已知精简联系人可能抛出以上异常 尝试使用二分法排查一下你具体是哪个功能导致的
> 
> 没开启此功能，选择0项，不过倒是测出来了
> 
> 是 主页 - 禁用轻互动 功能导致的 开启后 在 消息 页面停留时，过几秒就会闪退。

关闭该功能后，将消息页面对应的互动点掉，再开启该功能，不会出现闪退

**Comment by HdShare** [comment]
> 关闭该功能后，将消息页面对应的互动点掉，再开启该功能，不会出现闪退

模块版本?

**Comment by Lesnao** [comment]
> > 关闭该功能后，将消息页面对应的互动点掉，再开启该功能，不会出现闪退
> 
> 模块版本?

1.5.1.r2096.9d589b7(2096)
最新的稳定版

**Comment by HdShare** [comment]
> > > 关闭该功能后，将消息页面对应的互动点掉，再开启该功能，不会出现闪退
> > 
> > 
> > 模块版本?
> 
> 1.5.1.r2096.9d589b7(2096) 最新的稳定版

尝试使用CI-r2110以上版本，这个版本修复了轻互动可能抛出异常的问题

**Comment by Lesnao** [comment]
> > > > 关闭该功能后，将消息页面对应的互动点掉，再开启该功能，不会出现闪退
> > > 
> > > 
> > > 模块版本?
> > 
> > 
> > 1.5.1.r2096.9d589b7(2096) 最新的稳定版
> 
> 尝试使用CI-r2110以上版本，这个版本修复了轻互动可能抛出异常的问题

好的
