### ISSUE TITLE
[Bug] QQ 9.0.60 消息+1无法使用

### ISSUE THREAD

**Issue by GojoSatoru007** [cinit/QAuxiliary#1022]
### Steps to reproduce/复现步骤

1.安卓未root，使用太极阴 内核129，安装1.5.0的Qauxaliary（1.5.1貌似不支持）
2.启用消息+1功能
3.无法使用+1功能

### Expected behaviour/预期行为

能够显示+1并可点击复读

### Actual behaviour/实际行为

无+1按钮

### Xposed Framework you used/你使用的Xposed框架

太极阴，14.0.6.11231507

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

QQ 9.0.60.17095

### Module Version/模块版本

1.5.0

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2001.597cbf1
QQ9.0.60(6478)
PID: 10372, UID: 10474
cc.ioctl.hook.ui.chat.RepeaterHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method[] java.lang.Class.getDeclaredMethods()' on a null object reference
	at cc.ioctl.hook.ui.chat.RepeaterHook.initOnce(SourceFile:7)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.startup.task.y.blockUntilFinish(Unknown Source:0)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2636)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2602)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8327)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7831)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7487)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2378)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by HdShare** [comment]
尝试使用[消息+1 Plus]，而不是[消息+1]

**Comment by GojoSatoru007** [comment]
消息+1 PLUS也无法使用，但无报错

**Comment by HdShare** [comment]
[消息+1 Plus]是不显示图标还是无法复读?
1.尝试更换lspatch/opatch框架
2.尝试更换Qa最新Ci-r2146版

**Comment by GojoSatoru007** [comment]
消息+1 PLUS 不显示图标，也无法复读
其他框架我试试看
