### ISSUE TITLE
[Bug] 移除群成员资料卡异常弹窗无法使用

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1026]
### Steps to reproduce/复现步骤

打开移除群成员资料卡异常弹窗功能

### Expected behaviour/预期行为

初始化成功

### Actual behaviour/实际行为

初始化失败

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

1.5.1.r2156.fbded78

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.5.1.r2156.fbded78
QQ9.0.0(5282)
PID: 3504, UID: 10452
me.hd.hook.RemoveGroupProfileDialog
isInitialized: true
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at me.hd.hook.RemoveGroupProfileDialog.initOnce(RemoveGroupProfileDialog.kt:2954)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:157)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:112)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$p6d4Z571M3T0oSu3Ep3L5AMN8ZU(HookInstaller.java:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:922)

```

**Comment by HdShare** [comment]
尝试最新CI版

**Comment by EatHatsuneShallots** [comment]
依然无效，不过初始化成功了
```
1.5.1.r2159.58070d4
QQ9.0.0(5282)
PID: 20297, UID: 10452
me.hd.hook.RemoveGroupProfileDialog
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldError: android.os.Bundle#iResult
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(XposedHelpers.java:246)
	at de.robv.android.xposed.XposedHelpers$$ExternalSyntheticLambda3.get(Unknown Source:2)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:246)
	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:1028)
	at me.hd.hook.RemoveGroupProfileDialog.initOnce$lambda$1(RemoveGroupProfileDialog.kt:59)
	at me.hd.hook.RemoveGroupProfileDialog.$r8$lambda$OnpEJzGfQVxjt-zBWB3kOsy7kds(RemoveGroupProfileDialog.kt:0)
	at me.hd.hook.RemoveGroupProfileDialog$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at cc.ioctl.util.HookUtilsKt$hookBeforeIfEnabled$1.beforeHookedMethod(HookUtils.kt:38)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.processProfileCard(Unknown Source:17)
	at com.tencent.mobileqq.profilecard.processor.ProfileSecureProcessor.onResponseProfileCard(P:1)
	at com.tencent.mobileqq.profilecard.api.impl.ProfileProtocolServiceImpl.responseProfileCard(P:11)
	at com.tencent.mobileqq.profilecard.servlet.ProfileCardServlet.responseSummaryCard(P:10)
	at com.tencent.mobileqq.profilecard.servlet.ProfileCardServlet.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:2)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.receiveMessageFromMSF(Unknown Source:14)
	at mqq.app.MainService.access$700(P:1)
	at mqq.app.MainService$3.onRecvResp(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handleRespMsg(P:139)
	at mqq.app.msghandle.MSFRespHandleTask.doHandleResp(P:2)
	at mqq.app.msghandle.MSFRespHandleTask.handleCommonMsg(P:1)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:7)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.os.HandlerThread.run(HandlerThread.java:67)


```

**Comment by HdShare** [comment]
重新尝试最新CI-r2161版

**Comment by EatHatsuneShallots** [comment]
现在可以用了
