### ISSUE TITLE
[Bug] QQ9.0.65 防撤回无法使用

### ISSUE THREAD

**Issue by LegendEast** [cinit/QAuxiliary#1034]
### Steps to reproduce/复现步骤

QQ9.0.65.17370(6588)版本使用LSPatch嵌入模块后无法正常使用防撤回

### Expected behaviour/预期行为

显示某用户尝试撤回某条消息，保留消息并且附带提示

### Actual behaviour/实际行为

和原版一样仅显示某用户撤回了某条消息

### Xposed Framework you used/你使用的Xposed框架

LSPatch0.6

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.65.17370(6588)

### Module Version/模块版本

1.5.1.r2096.9d589b7(2096)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2096.9d589b7
QQ9.0.65(6588)
PID: 17945, UID: 10384
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 3
java.lang.RuntimeException: AobScanUtils: validator failed for all targets 'RecallC2cSysMsg' with sequence '098d40f8f50300aa21008052f30302aa298d40f9' mask '' for result 0x182d82c+offset
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:15)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.ah.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'InstructionOffsetForTmpRev5048' with sequence '61018052e00300aa0010009400000036000240f961018052e00300aa090040f9e800009120013fd6' mask 'ffffffffffff00ff00ffffffff00ffff00ffffffffffffffffff00ffff00ffffff0000ffffffffff'
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:15)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.ah.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: InitInitNtKernelRecallMsgHook failed, fnHookProc failed
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:15)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.ah.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by HdShare** [comment]
更新最新Ci-r2167版

**Comment by EagleSuHu** [comment]
怎么更新你说的这个CI，是什么？

**Comment by HdShare** [comment]
> 怎么更新你说的这个CI，是什么？

https://t.me/QAuxiliary_CI
