### ISSUE TITLE
[Bug] 有时退出 QA 会导致 QQ 崩溃

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1049]
### Steps to reproduce/复现步骤

不明

### Expected behaviour/预期行为

不会导致崩溃

### Actual behaviour/实际行为

可能导致崩溃

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

c2118fa497b7296ab8c629be6f68119085eb0bd4

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
06-22 23:54:02.215 11289 11289 E AndroidRuntime: FATAL EXCEPTION: main
06-22 23:54:02.215 11289 11289 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 11289
06-22 23:54:02.215 11289 11289 E AndroidRuntime: java.lang.IllegalArgumentException: View=DecorView@91b0df1[SettingsUiFragmentHostActivity] not attached to window manager
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:545)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:449)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:162)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.app.Dialog.dismissDialog(Dialog.java:435)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.app.Dialog.dismiss(Dialog.java:417)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at androidx.appcompat.app.AppCompatDialog.dismiss(AppCompatDialog.java:154)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at io.github.qauxv.ui.CustomDialog.dismiss(CustomDialog.java:322)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at io.github.qauxv.core.HookInstaller.lambda$doInitAndSetupHookForeground$4(HookInstaller.java:174)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at io.github.qauxv.core.HookInstaller.$r8$lambda$wyh8PcHtt4MuhHeEZxZ4Tqgr3n0(HookInstaller.java:0)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:233)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.os.Looper.loop(Looper.java:334)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8397)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
06-22 23:54:02.215 11289 11289 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

**Comment by Arce0416** [comment]
是的，这个问题，有时候用集成模式，清理缓存再退出qq会发生崩溃(可能)
