### ISSUE TITLE
[Bug] 防撤回在9.0.65上异常

### ISSUE THREAD

**Issue by mizuzuli** [cinit/QAuxiliary#1054]
### Steps to reproduce/复现步骤

点击防撤回总开关，显示初始化失败

### Expected behaviour/预期行为

本应该能正常使用

### Actual behaviour/实际行为

点击防撤回总开关

### Xposed Framework you used/你使用的Xposed框架

lspatch

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.65

### Module Version/模块版本

1.51

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2096.9d589b7
QQ9.0.65(6588)
PID: 28767, UID: 10812
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 2
java.lang.RuntimeException: AobScanUtils: validator failed for all targets 'RecallC2cSysMsg' with sequence '098d40f8f50300aa21008052f30302aa298d40f9' mask '' for result 0x182d82c+offset
	at cc.ioctl.hook.msg.RevokeMsgHook.nativeInitNtKernelRecallMsgHook(Native Method)
	at cc.ioctl.hook.msg.RevokeMsgHook.initOnce(RevokeMsgHook.java:186)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:157)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:112)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$p6d4Z571M3T0oSu3Ep3L5AMN8ZU(HookInstaller.java:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'InstructionOffsetForTmpRev5048' with sequence '61018052e00300aa0010009400000036000240f961018052e00300aa090040f9e800009120013fd6' mask 'ffffffffffff00ff00ffffffff00ffff00ffffffffffffffffff00ffff00ffffff0000ffffffffff'
	at cc.ioctl.hook.msg.RevokeMsgHook.nativeInitNtKernelRecallMsgHook(Native Method)
	at cc.ioctl.hook.msg.RevokeMsgHook.initOnce(RevokeMsgHook.java:186)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:157)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:112)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$p6d4Z571M3T0oSu3Ep3L5AMN8ZU(HookInstaller.java:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by HdShare** [comment]
@mizuzuli QA更新到最新CI版

**Comment by mizuzuli** [comment]
1
