### ISSUE TITLE
[Bug] 2197版QA防撤回功能失效

### ISSUE THREAD

**Issue by shugeguangtou** [cinit/QAuxiliary#1058]
### Steps to reproduce/复现步骤

已开启防撤回功能，接受到好友消息后，好友撤回消息，无法阻止消息撤回

### Expected behaviour/预期行为

防撤回功能正常使用

### Actual behaviour/实际行为

![Screenshot_2024-06-29-11-37-02-743_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/171567457/415150b2-8804-44ee-bcdd-72d5386a4ac9)

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2(7058)-zygisk

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.70.17645

### Module Version/模块版本

1.5.1.r2197.7a04437

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2197.7a04437
QQ9.0.70(6698)
PID: 15900, UID: 10293
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 3
java.lang.RuntimeException: AobScanUtils: failed to find target 'GetDecoder' with sequence '3f8d01f8f40300aa1f1000f9' mask ''
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'InstructionOffsetForTmpRev5048' with sequence '61018052e00300aa0010009400000036000240f961018052e00300aa090040f9e800009120013fd6' mask 'ffffffffffff00ff00ffffff0000ffff00ffffffffffffffffff00ffff00ffffff0000ffffffffff'
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: InitInitNtKernelRecallMsgHook failed, fnHookProc failed
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by fulian23** [comment]
我在QQ版本为9.0.65上也出现了相同的问题

**Comment by HdShare** [comment]
> 我在QQ版本为9.0.65上也出现了相同的问题

查看历史Issue或者讨论都可以解决
即：更新到最新CI版本

**Comment by fulian23** [comment]
感谢提醒，更新到最新CI版本后问题解决了❤️

**Comment by fulian23** [comment]
> > 我在QQ版本为9.0.65上也出现了相同的问题
> 
> 查看历史Issue或者讨论都可以解决 即：更新到最新CI版本

感谢提醒，更新到最新版本的CI后问题解决了❤️

**Comment by Infatuation-Fei** [comment]
QQ更新到9.0.71又失效了
![Screenshot_2024_0703_212500](https://github.com/cinit/QAuxiliary/assets/58471624/ac14aaa1-d627-439b-a623-c807f8897972)

**Comment by HomoobyDX** [comment]
[RevokeMsgHook-1720031756516.txt](https://github.com/user-attachments/files/16089345/RevokeMsgHook-1720031756516.txt)
我用的QA是1.5.1.r2096.9d589b7
QQ是官方9.0.71版本，防撤回又不能用了(我是9.0.65是三个异常，更新到9.0.71就变成五个异常了)

**Comment by IzumiChino** [comment]
在最新的QQ版本9.0.73(6722)中也复现了此问题，我使用的QA版本号为1.5.1.r2222.39088a8(2222)，构建时间2024-07-06
目前显示3个异常
```
1.5.1.r2222.39088a8
QQ9.0.73(6722)
PID: 32067, UID: 10254
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 3
java.lang.RuntimeException: AobScanUtils: failed to find target 'GetDecoder' with sequence '3f8d01f8f40300aa1f1000f9' mask ''
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'InstructionOffsetForTmpRev5048' with sequence '61018052e00300aa0010009400000036000240f961018052e00300aa090040f9e800009120013fd6' mask 'ffffffffffff00ff00ffffff0000ffff00ffffffffffffffffff00ffff00ffffff0000ffffffffff'
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: InitInitNtKernelRecallMsgHook failed, fnHookProc failed
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at java.lang.Class.forName(Class.java:467)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.startup.task.KernelInitTask.run(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by EagleSuHu** [comment]
大概多久可以修复呢，我QQ版本是9.0.71，报错和楼上一样

**Comment by R4v3nBlaze** [comment]
QQ 9.0.71 CI版本 防撤回失效：
java.lang.RuntimeException: InitInitNtKernelRecallMsgHook failed, fnHookProc failed
 at java.lang.Runtime.nativeLoad(Native Method)
 at java.lang.Runtime.nativeLoad(runtime.java:1126)
 at java.lang.Runtime.loadLibrary0(runtime.java:1080)
 at java.lang.Runtime.loadLibrary0(runtime.java:1003)
 at java.lang.System.loadLibrary(system.java:1661)
 at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(class.java:536)
 at java.lang.Class.forName(class.java:467)
 at com.tencent.mobileqq.qroute.a.e(P:2)
 at com.tencent.mobileqq.qroute.a.c(P:11)
 at com.tencent.mobileqq.qroute.a.b(P:2)
 at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
 at com.tencent.mobileqq.qroute.QRoute.api(P:1)
 at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
 at mqq.app.MobileQQ$5.run(P:39)
 at mqq.app.MobileQQ.createNewRuntime(P:7)
 at mqq.app.MobileQQ.doInit(P:24)
 at mqq.app.MobileQQ.waitAppRuntime(P:5)
 at mqq.app.MobileQQ.waitAppRuntime(P:14)
 at mqq.app.QQBroadcastReceiver.onReceive(P:9)
 at android.app.ActivityThread.handleReceiver(activitythread.java:4673)
 at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(activitythread.java:2402)
 at android.os.Handler.dispatchMessage(handler.java:106)
 at android.os.Looper.loopOnce(looper.java:224)
 at android.os.Looper.loop(looper.java:318)
 at android.app.ActivityThread.main(activitythread.java:8755)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(runtimeinit.java:561)
 at com.android.internal.os.ZygoteInit.main(zygoteinit.java:1013)

**Comment by bocchi810** [comment]
看了下，可能是特征码失效了，但我不知道当初贡献者怎么搞到的特征码

**Comment by ssszzza** [comment]
现在还有什么办法吗？

**Comment by bocchi810** [comment]
> 现在还有什么办法吗？

无解，只能等开发者修复

**Comment by shugeguangtou** [comment]
开发者修复了，更新到最新的CI版本支持9.0.71版本了，9.0.75的说是比较不然适配，可能还得等一段时间

**Comment by Infatuation-Fei** [comment]
我一直留在71版本，试了下最新的CI版本，防撤回确实可以了

**Comment by HdShare** [comment]
尝试最新Ci版
