### ISSUE TITLE
[Bug] 表情无法正常发送

### ISSUE THREAD

**Issue by MoMingLog** [cinit/QAuxiliary#107]
### Steps to reproduce/复现步骤

1. 开启【实验性功能】下的“回复带图”功能
2. 进入QQ聊天界面
3. 输入“不哭不哭”，在弹出的表情中选择第一个

### Expected behaviour/预期行为

正常发送表情包

### Actual behaviour/实际行为

表情包没有发送
消息编辑框内容清空

### XPosed Framework you used/你使用的XP框架

LSP 1.8.3 (6552) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.8.95(2944)

### Module Version/模块版本

1.2.9.r774.4e81e 6 e(774)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

没有对应的“回复带图”异常日志，只有一个“频道显示更多信息”有异常提示

1.2.9.r774.4e81e6e
QQ8.8.95(2944)
com.hicore.hook.ShowGuildData
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: com.tencent.mobileqq.guild.setting.popup.GuildMainSettingDialogFragment.mk []
	at java.lang.Class.getMethod(Class.java:2103)
	at java.lang.Class.getDeclaredMethod(Class.java:2081)
	at com.hicore.hook.ShowGuildData.initOnce(ShowGuildData.java:63)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:61)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:143)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.run(P:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by keta1** [comment]
使用 回复带图 会导致文本框上方的表情推荐点击无效，如需使用 表情推荐 功能，请关闭回复带图
这是预期行为
