### ISSUE TITLE
[Bug] 复读消息为图片导致闪退

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1078]
### Steps to reproduce/复现步骤

使用复读消息为图片功能

### Expected behaviour/预期行为

功能正常使用

### Actual behaviour/实际行为

点击菜单后闪退

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

a16b4f60305e95c40726a1494a5dc1361852d5ac

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

```
07-14 02:25:48.049  8181  8181 E AndroidRuntime: FATAL EXCEPTION: main
07-14 02:25:48.049  8181  8181 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 8181
07-14 02:25:48.049  8181  8181 E AndroidRuntime: java.lang.NullPointerException
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at me.hd.hook.menu.RepeatToImg.saveAndSendScreenshot(RepeatToImg.kt:107)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at me.hd.hook.menu.RepeatToImg.onGetMenuNt$lambda$8(RepeatToImg.kt:177)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at me.hd.hook.menu.RepeatToImg.$r8$lambda$7NME0rcUyZyrK2awqGDEkEZnOqU(RepeatToImg.kt:0)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at me.hd.hook.menu.RepeatToImg$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu.createItemIconNt$lambda$6(CustomMenu.kt:136)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu.$r8$lambda$1kqu94Xuy5lxsl4ShV8M0-kdyA8(CustomMenu.kt:0)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at com.tencent.qqnt.aio.menu.ui.c$ByteBuddy$5HItrCUK.f(Unknown Source:3)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at com.tencent.qqnt.aio.menu.ui.QQCustomMenuExpandableLayout$c.onClick(P:3)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.view.View.performClick(View.java:7512)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7489)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.view.View.access$3700(View.java:857)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29016)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:334)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8397)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
07-14 02:25:48.049  8181  8181 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

**Comment by HdShare** [comment]
@EatHatsuneShallots 闪退是因为暂时没有适配除8.9.88和9.0.75以外的版本
