### ISSUE TITLE
[Bug] 9.0.35 群文件转存永久报错

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1087]
### Steps to reproduce/复现步骤

启用功能

### Expected behaviour/预期行为

不报错

### Actual behaviour/实际行为

报错

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.35

### Module Version/模块版本

be83b0be4e7e1046fd886c154d893d2dc4bc7aae

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

```
1.5.1.r2253.be83b0b
QQ9.0.35(6150)
PID: 11974, UID: 10452
cc.ioctl.hook.troop.TroopFileSaveLasting
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.IllegalAccessError: Interface com.tencent.mobileqq.troop.widget.j$a implemented by class com.tencent.mobileqq.troop.data.TroopFileShowAdapter is inaccessible (declaration of 'com.tencent.mobileqq.troop.data.TroopFileShowAdapter' appears in /data/data/com.tencent.mobileqq/app_installed_plugin/troop_plugin.apk)
	at java.lang.Class.getDeclaredField(Native Method)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook$lambda$4(TroopFileSaveLasting.kt:50)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.$r8$lambda$5nNEpajNZrcg3cf-B9jO1QxwMfg(TroopFileSaveLasting.kt:0)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook(TroopFileSaveLasting.kt:47)
	at me.ketal.base.PluginDelayableHook.initOnce$lambda$5(PluginDelayableHook.kt:90)
	at me.ketal.base.PluginDelayableHook.$r8$lambda$WhJ6mNnw6HCuTckKFMPJCFAuyns(PluginDelayableHook.kt:0)
	at me.ketal.base.PluginDelayableHook$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at me.ketal.base.PluginDelayableHook.initOnce(PluginDelayableHook.kt:58)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:244)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2476)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2446)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7968)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7458)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7180)
	at android.app.ActivityThread.access$1900(ActivityThread.java:290)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

```

### 补充说明（可选）

我没有登录（因为被禁止登录了），用 #1067 所述的方法打开的模块主页

**Comment by HdShare** [comment]
经实测，功能正常可使用

**Comment by klxiaoniu** [comment]
请你：
1. 打开一次群文件界面
2. 杀后台并重启QQ
