### ISSUE TITLE
防撤回失效

### ISSUE THREAD

**Issue by XXJNOTFOUND** [cinit/QAuxiliary#1089]
### Steps to reproduce/复现步骤

1.更新qq
2.重启模块
3.开启防撤回（之前都没开
4.无法正常防撤回
5.检查故障列表，发现问题

### Expected behaviour/预期行为

正常防撤回

### Actual behaviour/实际行为

没有正常运行，且故障排查-功能异常列表中显示防撤回五个异常

### Xposed Framework you used/你使用的Xposed框架

LSPosed

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.80.18140

### Module Version/模块版本

1.5.1.r2096.9d589b7

### Version and Other Requirements/版本和其他要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.1.r2096.9d589b7
QQ9.0.80(6896)
PID: 23527, UID: 10274
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 5
java.lang.RuntimeException: AobScanUtils: failed to find target 'RecallC2cSysMsg' with sequence '098d40f8f50300aa21008052f30302aa298d40f9' mask ''
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.al.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'RecallGroupSysMsg' with sequence '280040f961008052098d40f8298d40f9' mask ''
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.al.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'GetDecoder' with sequence '3f8d01f8f40300aa1f1000f9' mask ''
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.al.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: failed to find target 'InstructionOffsetForTmpRev5048' with sequence '61018052e00300aa0010009400000036000240f961018052e00300aa090040f9e800009120013fd6' mask 'ffffffffffff00ff00ffffffff00ffff00ffffffffffffffffff00ffff00ffffff0000ffffffffff'
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.al.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: InitInitNtKernelRecallMsgHook failed, fnHookProc failed
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.qqnt.kernel.api.impl.KernelSetterImpl.<clinit>(P:26)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.tencent.mobileqq.qroute.a.e(P:2)
	at com.tencent.mobileqq.qroute.a.c(P:11)
	at com.tencent.mobileqq.qroute.a.b(P:2)
	at com.tencent.mobileqq.qroute.QRoute.apiImpl(P:9)
	at com.tencent.mobileqq.qroute.QRoute.api(P:1)
	at com.tencent.mobileqq.app.QQAppInterface.onCreate(P:6)
	at mqq.app.MobileQQ$5.run(P:39)
	at mqq.app.MobileQQ.createNewRuntime(P:7)
	at mqq.app.MobileQQ.doInit(P:24)
	at com.tencent.mobileqq.startup.task.al.run(P:10)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by HdShare** [comment]
在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中已有相关问题及解决答案
更新最新CI版即可解决
