### ISSUE TITLE
[Bug] 群文件长按转存永久失效

### ISSUE THREAD

**Issue by HeeRo1Yuy** [cinit/QAuxiliary#1096]
### Steps to reproduce/复现步骤

清除QA缓存，重启QQ，功能异常列表里依旧提示“群文件长按转存永久”异常

### Expected behaviour/预期行为

正常长按群文件提示永久保存

### Actual behaviour/实际行为

实际长按群文件没反应

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2 (7058)-Zygisk

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.70(6698)

### Module Version/模块版本

1.5.2.r2272.bdabefa

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.2.r2272.bdabefa
QQ9.0.70(6698)
PID: 22032, UID: 10369
cc.ioctl.hook.troop.TroopFileSaveLasting
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at me.ketal.util.HookUtilKt.findClass(HookUtil.kt:36)
	at me.ketal.util.HookUtilKt.findClass$default(HookUtil.kt:35)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook$lambda$4(TroopFileSaveLasting.kt:52)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.$r8$lambda$5nNEpajNZrcg3cf-B9jO1QxwMfg(TroopFileSaveLasting.kt:0)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook(TroopFileSaveLasting.kt:47)
	at me.ketal.base.PluginDelayableHook.initOnce$lambda$5(PluginDelayableHook.kt:90)
	at me.ketal.base.PluginDelayableHook.$r8$lambda$WhJ6mNnw6HCuTckKFMPJCFAuyns(PluginDelayableHook.kt:0)
	at me.ketal.base.PluginDelayableHook$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at me.ketal.base.PluginDelayableHook.initOnce(PluginDelayableHook.kt:58)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.poststartup.StartupRoutine.execPostStartupInit(StartupRoutine.java:64)
	at io.github.qauxv.poststartup.StartupHook.execStartupInit(StartupHook.java:72)
	at io.github.qauxv.poststartup.StartupHook$1.afterHookedMethod(StartupHook.java:141)
	at io.github.qauxv.util.xpcompat.XposedBridge$WrappedHookCallback.afterHookedMember(XposedBridge.java:164)
	at io.github.qauxv.loader.sbl.xp51.Xp51HookWrapper$Xp51HookCallback.afterHookedMethod(Xp51HookWrapper.java:127)
	at dkr.ukFc.ABKulA.nPNioN.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.B(P:6)
	at com.tencent.mobileqq.startup.director.a.A(P:2)
	at com.tencent.mobileqq.startup.director.a.r(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at RHcv.hyYZiV.aepnW.lQXi.aJ.Syu.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:194)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2650)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2620)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8465)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7976)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7663)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2452)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:255)
	at android.os.Looper.loop(Looper.java:364)
	at android.app.ActivityThread.main(ActivityThread.java:8938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	... 51 more

**Comment by HdShare** [comment]
打开一次群文件界面
杀后台并重启QQ
