### ISSUE TITLE
[Bug] 1.50版本及以上开启“下载文件重定向”会导致无法拍照发图

### ISSUE THREAD

**Issue by HuaSublimation** [cinit/QAuxiliary#1115]
### Steps to reproduce/复现步骤

1.“下载文件重定向”，2.在聊天框上选择拍照。
![IMG_20240806_204741](https://github.com/user-attachments/assets/c0f9fce9-7598-4192-92fc-9d7e74fe7e4d)
![IMG_20240806_204706](https://github.com/user-attachments/assets/235d30f8-4d01-4fc5-8376-5b3fd7dafcff)
![IMG_20240806_204715](https://github.com/user-attachments/assets/9b0546a6-756d-4181-a3d9-2c0363507c98)

### Expected behaviour/预期行为

正常情况下能发送拍摄的图片

### Actual behaviour/实际行为

不能发送拍摄的图片

### Xposed Framework you used/你使用的Xposed框架

手机未root，使用LSPatch 0.6版本

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

1.5.2

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.2.r2263.c3d9cc2
QQ9.0.0(5282)
PID: 21582, UID: 10370
cc.hicore.hook.ReplyMsgWithImg
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: CGuildHelperProvider.INSTANCE
	at java.util.Objects.requireNonNull(Objects.java:232)
	at cc.hicore.hook.ReplyMsgWithImg.initOnce(ReplyMsgWithImg.java:137)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2636)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2602)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8236)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7747)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7399)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2365)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

[异常ReplyMsgWithImg-1722948864740.txt](https://github.com/user-attachments/files/16510521/ReplyMsgWithImg-1722948864740.txt)

### 补充说明（可选）

无

**Comment by HuaSublimation** [comment]
我使用的是LSPatch的集成模式给QQ添加补丁

**Comment by HdShare** [comment]
@HuaSublimation 虽然但是，你这发的日志是带图回复的，与此功能无关

**Comment by HuaSublimation** [comment]
我在功能异常列表里看到的就只有“隐藏侧滑厘米秀”和“回复带图”这两个异常
![Screenshot_2024-08-06-21-11-12-178_com tencent mobileqq](https://github.com/user-attachments/assets/b638c1b1-b631-41b2-83e0-0b582a38f2ac)

**Comment by HuaSublimation** [comment]
> @HuaSublimation虽然但是，你发的日志是带图回复的，与此功能无关

我在 功能异常列表 里看到的就只有“隐藏侧滑厘米秀”和“回复带图”这两个异常
![Screenshot_2024-08-06-21-11-12-178_com tencent mobileqq](https://github.com/user-attachments/assets/c63407e8-fbe7-4bd0-90ed-1b052145cf0c)
