### ISSUE TITLE
[Bug] 清理最近聊天异常

### ISSUE THREAD

**Issue by Simlalsy** [cinit/QAuxiliary#113]
### Steps to reproduce/复现步骤

hook失败？

### Expected behaviour/预期行为

长按加号，弹出选框

### Actual behaviour/实际行为

长按加号，未弹出选框

### XPosed Framework you used/你使用的XP框架

LSP 1.8.3（6577）

### QQ(TIM)版本/QQ(TIM) Version

8.8.90.7975

### Module Version/模块版本

1.2.10.r793.3c1f816

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.10.r793.3c1f816
QQ8.8.90(2828)
xyz.nextalone.hook.CleanRecentChat
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1.invoke(CleanRecentChat.kt:67)
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1.invoke(CleanRecentChat.kt:66)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at xyz.nextalone.hook.CleanRecentChat.initOnce(CleanRecentChat.kt:66)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:61)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:143)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:115)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:146)
	at com.tencent.mobileqq.startup.step.Step.step(P:115)
	at com.tencent.mobileqq.startup.step.Step.run(P:90)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by keta1** [comment]
在 此版本 qq 上使用 最新版 模块测试无此问题
