### ISSUE TITLE
[Bug] 9.0.90版本侧边栏精简功能异常且失效

### ISSUE THREAD

**Issue by CuSO4with5H2O** [cinit/QAuxiliary#1133]
### Steps to reproduce/复现步骤

1.打开侧边栏精简功能

### Expected behaviour/预期行为

功能正常

### Actual behaviour/实际行为

功能异常，如图
![Screenshot_2024-08-16-18-47-12-710_com tencent mobileqq](https://github.com/user-attachments/assets/1b508970-d413-407e-95f5-63adce3500ad)

### Xposed Framework you used/你使用的Xposed框架

lsposed1.9.2 7024

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.90.18890

### Module Version/模块版本

1.5.2.r2376.35c9f8e

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [ ] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.2.r2376.35c9f8e
QQ9.0.90(7196)
PID: 30272, UID: 10342
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: DexTarget: QQ_SETTING_ME_CONFIG_CLASS
	at io.github.qauxv.util.dexkit.DexKit.requireClassFromCache(DexKit.kt:139)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe.initOnce$lambda$16(SimplifyQQSettingMe.kt:260)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe.$r8$lambda$vpZkIc7w17w_FTA_Qk4ey3c9AKQ(SimplifyQQSettingMe.kt:0)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe.initOnce(SimplifyQQSettingMe.kt:170)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:223)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:167)
	at io.github.qauxv.poststartup.StartupRoutine.execPostStartupInit(StartupRoutine.java:79)
	at io.github.qauxv.poststartup.StartupHook.execStartupInit(StartupHook.java:73)
	at io.github.qauxv.poststartup.StartupHook$1.afterHookedMethod(StartupHook.java:143)
	at io.github.qauxv.util.xpcompat.WrappedCallbacks$WrappedHookCallback.afterHookedMember(WrappedCallbacks.java:81)
	at io.github.qauxv.loader.sbl.lsp100.Lsp100HookWrapper$Lsp100HookAgent.handleAfterHookedMethod(Lsp100HookWrapper.java:407)
	at io.github.qauxv.loader.sbl.lsp100.dyn.Lsp100CallbackProxy$P0000000051.after(Lsp100CallbackProxy.java:57)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:264)
	at LSPHooker_.run(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by CuSO4with5H2O** [comment]
开了这些
![Screenshot_2024-08-16-18-51-53-167_com tencent mobileqq](https://github.com/user-attachments/assets/a40bde60-ae5a-4b6e-b2a7-6a0fe4b2ec75)
