### ISSUE TITLE
[Bug] gboard不能正常插入表情

### ISSUE THREAD

**Issue by Pittow2** [cinit/QAuxiliary#1173]
### 复现步骤 / Steps to reproduce

在gboard 中点开emoji 栏，使用表情建议、贴纸或gif

### 预期行为 / Expected behaviour

Gboard 通过content provider将图片传输给qq

### 实际行为 / Actual behaviour

png或gif没有正常插入qq

### 你使用的Xposed框架 / Xposed Framework you used

lsp7058

### 你使用的安卓系统版本 / Your Android version

13

### QQ(TIM) 版本 / QQ(TIM) Version

8.9.70

### 模块版本 / Module Version

2263

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

回复带图功能有红色叹号
1.5.2.r2263.c3d9cc2
QQ8.9.70(4330)
PID: 16782, UID: 10281
cc.hicore.hook.ReplyMsgWithImg
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: CGuildHelperProvider.INSTANCE
	at java.util.Objects.requireNonNull(Objects.java:245)
	at cc.hicore.hook.ReplyMsgWithImg.initOnce(ReplyMsgWithImg.java:137)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.g3.a.a.z(P:6)
	at com.tencent.mobileqq.g3.a.a.y(P:2)
	at com.tencent.mobileqq.g3.a.a.p(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7966)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7477)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7205)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### 补充说明（可选） / Additional information (optional)

报错弹窗
java.io.FileNotFoundException: No content provider: content://com.google.android.inputmethod.latin.fileprovider/content/sticker/sticker5845696869613053863.png
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2015)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
	at cc.ioctl.hook.msg.AioChatPieClipPasteHook.lambda$handleSendUriPicture$3(AioChatPieClipPasteHook.java:214)
	at cc.ioctl.hook.msg.AioChatPieClipPasteHook.$r8$lambda$9xc_RcRWzyvysntkY9M-aBo7S0A(AioChatPieClipPasteHook.java:0)
	at cc.ioctl.hook.msg.AioChatPieClipPasteHook$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by klxiaoniu** [comment]
你好，你提供的是带图回复日志，这个功能坏掉很久了，且与此问题无关。
打开“支持聊天窗口发送图片”，即可发送gboard图片表情。
