### ISSUE TITLE
[Bug] 批量撤回消息功能可能会报错

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1180]
### 复现步骤 / Steps to reproduce

打开一个不属于 `com.tencent.mobileqq.app.BaseActivity` 子类的 `Activity`

### 预期行为 / Expected behaviour

不报错

### 实际行为 / Actual behaviour

报错，但好像不影响使用

### 你使用的Xposed框架 / Xposed Framework you used

ONPatch 0.0.7

### 你使用的安卓系统版本 / Your Android version

10 (HarmonyOS 2.0)

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 模块版本 / Module Version

1.5.2.r2420.bf76891(2420)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

```
1.5.2.r2420.bf76891
QQ9.0.60(6478)
PID: 31884, UID: 10225
me.ketal.hook.MultiActionHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassCastException: com.tencent.mobileqq.activity.ScaleAIOActivity cannot be cast to com.tencent.mobileqq.app.BaseActivity
	at me.ketal.hook.MultiActionHook.hookNt$lambda$4(MultiActionHook.kt:115)
	at me.ketal.hook.MultiActionHook.$r8$lambda$YX38IwvgwY13nklik3T5Frm7xJE(MultiActionHook.kt:0)
	at me.ketal.hook.MultiActionHook$$ExternalSyntheticLambda2.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt$hookAfter$1.afterMethod(HookUtils.kt:238)
	at xyz.nextalone.bridge.NAMethodHook.afterHookedMethod(NAMethodHook.kt:47)
	at io.github.qauxv.util.xpcompat.WrappedCallbacks$WrappedHookCallback.afterHookedMember(WrappedCallbacks.java:81)
	at io.github.qauxv.loader.sbl.xp51.Xp51HookWrapper$Xp51HookCallback.afterHookedMethod(Xp51HookWrapper.java:142)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:447)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.onCreateView(Unknown Source:11)
	at com.tencent.mvi.mvvm.b.b.buildViewTree(P:4)
	at com.tencent.mvi.mvvm.b.b.buildChildVB(P:1)
	at com.tencent.mvi.mvvm.b.b.addChildVB(P:3)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVB.f1(P:2)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVB.d1(P:2)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVB.handleUIState(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.a(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.onChanged(P:1)
	at androidx.lifecycle.MVILiveData$MVIObserverWrapper.onChanged(P:2)
	at androidx.lifecycle.LiveData.considerNotify(P:6)
	at androidx.lifecycle.LiveData.dispatchingValue(P:8)
	at androidx.lifecycle.LiveData.setValue(P:4)
	at androidx.lifecycle.MutableLiveData.setValue(P:1)
	at androidx.lifecycle.MVILiveData.setValue(P:2)
	at com.tencent.mvi.mvvm.b.c.dispatchState$mvi_debug(P:4)
	at com.tencent.mvi.mvvm.BaseVM.updateUI(P:3)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVM.w(P:1)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVM.g(P:1)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVM.r(P:1)
	at com.tencent.mobileqq.aio.input.AIOInputContainerVM$b.call(P:1)
	at com.tencent.mvi.base.route.VMMessenger$send$1.invoke(P:13)
	at com.tencent.mvi.base.route.VMMessenger$send$1.invoke(P:1)
	at com.tencent.mvi.base.route.VMMessenger.r(P:2)
	at com.tencent.mvi.base.route.VMMessenger.s(P:1)
	at com.tencent.mvi.base.route.VMMessenger.f(P:1)
	at com.tencent.aio.runtime.b.f(Unknown Source:24)
	at com.tencent.mobileqq.aio.msglist.holder.component.a.A(P:4)
	at com.tencent.mobileqq.aio.msglist.holder.component.a.s(P:7)
	at com.tencent.mobileqq.aio.msglist.holder.component.video.a.s(P:3)
	at com.tencent.mobileqq.aio.msglist.holder.component.video.a.handleIntent(P:1)
	at com.tencent.mvi.mvvm.BaseVB.sendIntent(P:1)
	at com.tencent.qqnt.aio.menu.r.g(P:1)
	at com.tencent.qqnt.aio.menu.ui.QQCustomMenuExpandableLayout$c.onClick(P:3)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)


```

**Comment by HdShare** [comment]
打开一个不属于 com.tencent.mobileqq.app.BaseActivity 子类的 Activity?

复现步骤推荐更具体一点

**Comment by EatHatsuneShallots** [comment]
> 复现步骤推荐更具体一点

我不太清楚要打开什么界面（Activity），但我肯定的是，打开 `com.tencent.mobileqq.activity.ScaleAIOActivity` 界面时报了错
