### ISSUE TITLE
[Bug] 侧滑栏精简异常

### ISSUE THREAD

**Issue by SYuanLUV** [cinit/QAuxiliary#121]
### Steps to reproduce/复现步骤

更新QQ后出现的bug

### Expected behaviour/预期行为

正常情况下可精简

### Actual behaviour/实际行为

精简无效，故障排查中的清理缓存不能解决问题

### XPosed Framework you used/你使用的XP框架

1.8.3 (6552) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.2.8685

### Module Version/模块版本

1.2.11.r840.5b91f01

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.11.r840.5b91f01
QQ8.9.2(3072)
me.kyuubiran.hook.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at me.kyuubiran.hook.SimplifyQQSettingMe$initOnce$1$1.afterHookedMethod(SimplifyQQSettingMe.kt:139)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:17)
	at com.tencent.mobileqq.activity.home.Conversation.c2(P:17)
	at com.tencent.mobileqq.activity.home.Conversation.l2(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.U0(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.c(P:14)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:2)
	at com.tencent.mobileqq.utils.ah.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.queueIdle(P:2)
	at android.os.MessageQueue.next(Unknown Source:159)
	at android.os.Looper.loopOnce(Unknown Source:6)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)

**Comment by keta1** [comment]
@SYuanLUV 更新qa

**Comment by Narase-Edge** [comment]
@keta1 请问已经更到最新5b91f01了，侧滑仍然提示异常，是要更到其他版本吗
