### ISSUE TITLE
[Bug] 批量撤回消息存在错误

### ISSUE THREAD

**Issue by thefirsttime2021** [cinit/QAuxiliary#1220]
### 复现步骤 / Steps to reproduce

1.打开QQ
2.打开QA-功能异常列表
3.批量撤回消息存在错误

### 预期行为 / Expected behaviour

应是未发现明显异常，并且能够正常的批量撤回消息

### 实际行为 / Actual behaviour

批量撤回消息存在错误，并且批量撤回消息时并没有撤回消息

### 你使用的Xposed框架 / Xposed Framework you used

LSPatch集成

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.5.20120(7688)

### 模块版本 / Module Version

1.5.3.r2434.e6297ae(2434)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.3.r2434.e6297ae
QQ9.1.5(7688)
PID: 14015, UID: 10385
me.ketal.hook.MultiActionHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: com.tencent.mobileqq.aio.input.multiselect.MultiSelectBarVM
	at io.github.qauxv.util.Initiator.loadClass(Initiator.java:97)
	at me.ketal.hook.MultiActionHook.hookNt(MultiActionHook.kt:144)
	at me.ketal.hook.MultiActionHook.initOnce$lambda$1(MultiActionHook.kt:90)
	at me.ketal.hook.MultiActionHook.$r8$lambda$0bKv8UzMMf6HPxRSz4-Lco9pCzA(MultiActionHook.kt:0)
	at me.ketal.hook.MultiActionHook$$ExternalSyntheticLambda9.invoke(R8$$SyntheticClass:0)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at me.ketal.hook.MultiActionHook.initOnce(MultiActionHook.kt:88)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:136)
	at io.github.qauxv.poststartup.StartupRoutine.execPostStartupInit(StartupRoutine.java:79)
	at io.github.qauxv.poststartup.StartupHook.execStartupInit(StartupHook.java:73)
	at io.github.qauxv.poststartup.StartupHook$1.afterHookedMethod(StartupHook.java:143)
	at io.github.qauxv.util.xpcompat.WrappedCallbacks$WrappedHookCallback.afterHookedMember(WrappedCallbacks.java:81)
	at io.github.qauxv.loader.sbl.xp51.Xp51HookWrapper$Xp51HookCallback.afterHookedMethod(Xp51HookWrapper.java:142)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.run(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.NtStartupExecutor$sam$java_lang_Runnable$0.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1019)

**Comment by klxiaoniu** [comment]
更新最新CI
