### ISSUE TITLE
[Bug] 即使篡改图片比例选择默认也会初始化

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1232]
### 复现步骤 / Steps to reproduce

选择“默认”

### 预期行为 / Expected behaviour

不会报错，且可以禁用

### 实际行为 / Actual behaviour

即使选择“默认”也无法禁用并报错

### 你使用的Xposed框架 / Xposed Framework you used

ONPatch 0.0.7

### 你使用的安卓系统版本 / Your Android version

10 (HarmonyOS 2.0)

### QQ(TIM) 版本 / QQ(TIM) Version

Tim 3.5.1

### 模块版本 / Module Version

1.5.4.r2498.732db33

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

```
1.5.4.r2498.732db33
TIM3.5.1(1298)
PID: 7913, UID: 10285
me.hd.hook.FakePicSize
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: false
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: com.tencent.qqnt.kernel.nativeinterface.IKernelMsgService$CppProxy
	at io.github.qauxv.util.Initiator.loadClass(Initiator.java:107)
	at me.hd.hook.FakePicSize.initOnce(FakePicSize.kt:100)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:249)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.poststartup.StartupRoutine.execPostStartupInit(StartupRoutine.java:79)
	at io.github.qauxv.poststartup.StartupHook.execStartupInit(StartupHook.java:73)
	at io.github.qauxv.poststartup.StartupHook$1.afterHookedMethod(StartupHook.java:140)
	at io.github.qauxv.util.xpcompat.WrappedCallbacks$WrappedHookCallback.afterHookedMember(WrappedCallbacks.java:81)
	at io.github.qauxv.loader.sbl.xp51.Xp51HookWrapper$Xp51HookCallback.afterHookedMethod(Xp51HookWrapper.java:142)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:447)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at com.tencent.mobileqq.startup.step.Step.doStep(SourceFile:153)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at anlo.a(SourceFile:408)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(SourceFile:310)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(SourceFile:30)
	at mqq.app.AppContentProvider.onCreate(SourceFile:30)
	at cooperation.readinjoy.content.ReadInJoyDataProvider.onCreate(SourceFile:103)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2097)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2070)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8168)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
	at android.app.ActivityThread.access$2600(ActivityThread.java:260)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

**Comment by HdShare** [comment]
非bug，该功能不适配TIM版本

**Comment by EatHatsuneShallots** [comment]
> 非bug，该功能不适配TIM3.5.1版本

我知道
我是因为不小心选择了一个选项就开始报错了（每次重启都会有报错），所以怎么关闭这个功能
