### ISSUE TITLE
侧滑栏精简失效

### ISSUE THREAD

**Issue by Ricardo669** [cinit/QAuxiliary#124]
### Steps to reproduce/复现步骤

更新至最新版QQ和QA，保存精简项目并重启QQ

### Expected behaviour/预期行为

侧滑栏精简项目不再出现在侧滑

### Actual behaviour/实际行为

显示所有的侧滑栏项目

### XPosed Framework you used/你使用的XP框架

Lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.2

### Module Version/模块版本

1.2.11

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.11.r840.5b91f01
QQ8.9.2(3072)
me.kyuubiran.hook.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at me.kyuubiran.hook.SimplifyQQSettingMe$initOnce$1$1.afterHookedMethod(SimplifyQQSettingMe.kt:139)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:17)
	at com.tencent.mobileqq.activity.home.Conversation.c2(P:17)
	at com.tencent.mobileqq.activity.home.Conversation.l2(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.U0(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.c(P:14)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:2)
	at com.tencent.mobileqq.utils.ah.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.queueIdle(P:2)
	at android.os.MessageQueue.next(MessageQueue.java:401)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by Ricardo669** [comment]
> 我不知道什么是最新版捏，具体版本号pls

我明明填写了版本号，仔细看issue，pls

**Comment by keta1** [comment]
> > 我不知道什么是最新版捏，具体版本号pls
> 
> 我明明填写了版本号，仔细看issue，pls

U are using latest debug CI version of QAuxiliary and enable verbose log/你正在使用最新 CI 调试版本且启用详细日志
