### ISSUE TITLE
[Bug] 功能「群设置页添加精华消息入口」无效

### ISSUE THREAD

**Issue by March7th0721** [cinit/QAuxiliary#1283]
### 复现步骤 / Steps to reproduce

1.打开「群设置页添加精华消息入口」
2.提示初始化失败

### 预期行为 / Expected behaviour

开启成功，群设置页面出现精华消息入口

### 实际行为 / Actual behaviour

打开开关后提示初始化失败

### 你使用的Xposed框架 / Xposed Framework you used

LSPosed 1.9.2（7178） Official

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

Tim 4.0.98(4012)

### 模块版本 / Module Version

1.5.5.r2566.d04bb07

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.5.r2566.d04bb07
TIM4.0.98(4012)
PID: 30516, UID: 10342
io.github.moonleeeaf.hook.AddEssenceViewerToGroupSettingsHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: DexTarget: ChatSettingForTroop_InitUI_TIM
	at io.github.qauxv.util.dexkit.DexKit.requireMethodFromCache(DexKit.kt:134)
	at io.github.moonleeeaf.hook.AddEssenceViewerToGroupSettingsHook.initOnce(AddEssenceViewerToGroupSettingsHook.java:89)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:157)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:112)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$p6d4Z571M3T0oSu3Ep3L5AMN8ZU(HookInstaller.java:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by HdShare** [comment]
尝试 r2568 新增的 "TIM 群标题栏添加精华消息入口"
