### ISSUE TITLE
[Bug] 屏蔽主界面超级QQ秀图标失效

### ISSUE THREAD

**Issue by ANan-12345** [cinit/QAuxiliary#140]
### Steps to reproduce/复现步骤

打开功能，重启qq

### Expected behaviour/预期行为

右上角没有超级QQ图标

### Actual behaviour/实际行为

右上角依旧有超级QQ秀图标

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.3.8730

### Module Version/模块版本

1.2.13 armALL

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.13.r894.c0f4975
QQ8.9.3(3118)
xyz.nextalone.hook.RemoveSuperQQShow
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException
	at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.findMethod(MethodUtils.kt:82)
	at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.findMethod$default(MethodUtils.kt:77)
	at xyz.nextalone.hook.RemoveSuperQQShow$initOnce$1.invoke(RemoveSuperQQShow.kt:44)
	at xyz.nextalone.hook.RemoveSuperQQShow$initOnce$1.invoke(RemoveSuperQQShow.kt:43)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at xyz.nextalone.hook.RemoveSuperQQShow.initOnce(RemoveSuperQQShow.kt:43)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:61)
	at io.github.qauxv.core.HookInstaller.allowEarlyInit(HookInstaller.java:68)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:111)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:63)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:73)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:191)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.k(P:4)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:11)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.onCreate(Unknown Source:8)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.biz.pubaccount.readinjoy.ReadInJoyDataProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7201)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6684)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6579)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7574)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by lliioollcn** [comment]
在 #146 修复
