### ISSUE TITLE
[Bug] 点击底栏的联系人按钮会崩溃

### ISSUE THREAD

**Issue by dogdie233** [cinit/QAuxiliary#156]
### Steps to reproduce/复现步骤

任意点击底栏的`联系人`按钮

### Expected behaviour/预期行为

切换到`联系人`页面

### Actual behaviour/实际行为

报错了，并且上方的Panel卡死，且无法再切换回到别的界面，几秒后会崩溃(疑似因为bugly的另一个报错)

### XPosed Framework you used/你使用的XP框架

Lsposed

### QQ(TIM)版本/QQ(TIM) Version

9.3.2

### Module Version/模块版本

1.3.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

从Lsposed导出来的
```
08-29 21:38:13.012  7628  7810 D DigestGenerator: digest=============com.tencent.mobileqqjava.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.widget.TabHost$FactoryContentStrategy.tabClosed(TabHost.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.widget.TabHost.setCurrentTab(TabHost.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at com.tencent.mobileqq.widget.QQTabHost.setCurrentTab(P:)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.widget.TabHost$.onTabSelectionChanged(TabHost.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.widget.TabWidget$TabClickListener.onClick(TabWidget.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.view.View.performClick(View.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at com.tencent.mobileqq.widget.TabDragAnimationView$a.onSingleTapConfirmed(P:)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.os.Handler.dispatchMessage(Handler.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.os.Looper.loopOnce(Looper.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.os.Looper.loop(Looper.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at android.app.ActivityThread.main(ActivityThread.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at java.lang.reflect.Method.invoke(Native Method)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
08-29 21:38:13.012  7628  7810 D DigestGenerator: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
```

**Comment by dogdie233** [comment]
# 启用模块

![启用模块](https://user-images.githubusercontent.com/42267840/187219535-adf85b04-9466-4a61-ad77-568e3a495c40.jpg)

# 按了联系人按钮之后会黑屏

![要寄了吗](https://user-images.githubusercontent.com/42267840/187219775-0fe00690-8695-4602-bacf-17b6b7e292ea.jpg)

**Comment by dogdie233** [comment]
只有点联系人会崩溃，点动态和频道和消息都不会有问题

**Comment by cinit** [comment]
你在 log 里找 `FATAL EXCEPTION` 或者 `Crash unexpectedly` 后的异常, 那才是导致闪退的直接原因

**Comment by dogdie233** [comment]
> 你在 log 里找 `FATAL EXCEPTION` 或者 `Crash unexpectedly` 后的异常, 那才是导致闪退的直接原因

```
08-29 22:07:26.283 10177 10177 E AndroidRuntime: FATAL EXCEPTION: main
08-29 22:07:26.283 10177 10177 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 10177
08-29 22:07:26.283 10177 10177 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.tencent.mobileqq/com.tencent.mobileqq.activity.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4928)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4961)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8307)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.widget.TabHost$FactoryContentStrategy.tabClosed(TabHost.java:782)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.widget.TabHost.setCurrentTab(TabHost.java:439)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.tencent.mobileqq.widget.QQTabHost.setCurrentTab(P:3)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.widget.TabHost.setCurrentTabByTag(TabHost.java:331)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.tencent.mobileqq.activity.framebusiness.GuildInjectImpl.a(P:8)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.tencent.mobileqq.activity.home.impl.TabFrameControllerImpl.dispatchOnResumeAfter(P:2)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.tencent.mobileqq.activity.home.impl.TabFrameControllerImpl.onResumeAfter(P:2)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at com.tencent.mobileqq.activity.home.MainFragment.onResume(P:45)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performResume(P:5)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.resume(P:3)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(P:29)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(P:69)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(P:4)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(P:75)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(P:3)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchResume(P:3)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchResume(P:1)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onResumeFragments(P:2)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPostResume(P:2)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at mqq.app.AppActivity.onPostResume(P:1)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:8371)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4918)
08-29 22:07:26.283 10177 10177 E AndroidRuntime: 	... 13 more
```
