### ISSUE TITLE
[Bug] 主页面+号入口失效

### ISSUE THREAD

**Issue by turanaa** [cinit/QAuxiliary#157]
### Steps to reproduce/复现步骤

第一次开QQ有但是点一次后入口就没了

### Expected behaviour/预期行为

有入口

### Actual behaviour/实际行为

无入口

### XPosed Framework you used/你使用的XP框架

无极

### QQ(TIM)版本/QQ(TIM) Version

8888

### Module Version/模块版本

505

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

ProcessName:com.tencent.mobileqq
ThreadName:main
XposedTag:Xposed
XposedTagDec:太极
AppVersion:8.8.88.7830
AppType:QQ
ModuleVer:v505
Time:2022-08-30 06:08:08
AndroidVersion:12
SDK_Level:31
CPU_ABI:armeabi-v7a
MODEL:IPone 14 Pro Max
BRAND:vivo
BOARD:taro
DEVICE:PD2196
PRODUCT:PD2196

项目名称:主界面加号入口
项目类:cc.hicore.qtool.XPWork.EntryHook.Hook_For_Main_Entry
项目目标信息
targetVer:-1
maxVer:-1
targetApp:1
period:early
type: Hook

项目启用的方法
--------------------------
getHookMethod
@cc.hicore.HookItemLoader.Annotations.MethodScanner()
@cc.hicore.HookItemLoader.Annotations.VerController(max_targetVer=-1, targetApp=1, targetVer=-1)
--------------------------
worker_1
@cc.hicore.HookItemLoader.Annotations.VerController(max_targetVer=-1, targetApp=1, targetVer=-1)
@cc.hicore.HookItemLoader.Annotations.XPExecutor(hook_period=50, methodID=hook_1, period=1)
--------------------------
worker_2
@cc.hicore.HookItemLoader.Annotations.VerController(max_targetVer=-1, targetApp=1, targetVer=-1)
@cc.hicore.HookItemLoader.Annotations.XPExecutor(hook_period=50, methodID=hook_2, period=1)
--------------------------

项目报告的方法
--------------------------
hook_1->private static void com.tencent.widget.PopupMenuDialog.createAndAttachItemsView(android.app.Activity,java.util.List,android.widget.LinearLayout,boolean)
hook_2->public void com.tencent.widget.PopupMenuDialog.onClick(android.view.View)
--------------------------

执行异常列表:
--------------------------
worker_1
android.content.res.Resources$NotFoundException: Resource ID #0x21080099
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:333)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:1069)
	at android.content.res.Resources.getDrawable(Resources.java:1009)
	at android.content.Context.getDrawable(Context.java:753)
	at cc.hicore.qtool.XPWork.EntryHook.Hook_For_Main_Entry.lambda$worker_1$0(Unknown Source:66)
	at cc.hicore.qtool.XPWork.EntryHook.Hook_For_Main_Entry.a(Unknown Source:0)
	at t2.a.onInvoke(Unknown Source:50)
	at cc.hicore.HookItemLoader.core.CoreLoader.lambda$XPHookInstance$1(Unknown Source:4)
	at cc.hicore.HookItemLoader.core.CoreLoader.a(Unknown Source:0)
	at j1.b.c(Unknown Source:6)
	at l1.f.beforeHookedMethod(Unknown Source:2)
	at de.robv.android.xposed.ExposedHelper.beforeHookedMethod(SourceFile:48)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.o0o0000o0o000oooOO0o0o00o000oo0ooo00oo(SourceFile:304)
	at exp.anc.callBeforeMethodHooked(SourceFile:490)
	at exp.ana.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:101)
	at com.tencent.widget.PopupMenuDialog.createAndAttachItemsView(Unknown Source:0)
	at com.tencent.widget.PopupMenuDialog.createAndAttachItemsView(P:213)
	at com.tencent.widget.PopupMenuDialog.prepareConversationPlusContent(P:322)
	at com.tencent.widget.PopupMenuDialog.conversationPlusBuild(P:296)
	at com.tencent.mobileqq.activity.recent.RecentOptPopBar.a(P:240)
	at com.tencent.mobileqq.activity.recent.RecentOptPopBar.a(P:228)
	at com.tencent.mobileqq.activity.recent.RecentOptPopBar.a(P:479)
	at com.tencent.mobileqq.activity.home.Conversation.onClick(P:8904)
	at android.view.View.performClick(View.java:7512)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3700(View.java:857)
	at android.view.View$PerformClick.run(View.java:29020)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at com.tencent.rmonitor.looper.LooperProxy.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

--------------------------

加载异常列表:
--------------------------
--------------------------

**Comment by keta1** [comment]
请像 https://github.com/Hicores/QTool 报告错误
