### ISSUE TITLE
[bug] 消息+1 无效

### ISSUE THREAD

**Issue by RealHeart** [cinit/QAuxiliary#164]
### Steps to reproduce/复现步骤

打开 消息+1 功能

### Expected behaviour/预期行为

消息右侧显示+1图标

### Actual behaviour/实际行为

无任何图标

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.3 (6552) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.5(3176)

### Module Version/模块版本

1.3.0.r958.6b 4bc00(958)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
1.3.0.r958.6b4bc00
QQ8.9.5(3176)
PID: 18935, UID: 10257
cc.ioctl.hook.RepeaterHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: method == null
	at java.util.Objects.requireNonNull(Objects.java:245)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:57)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:178)
	at cc.ioctl.hook.RepeaterHook.initOnce(RepeaterHook.java:182)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:61)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:188)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:142)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.run(P:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)


```

**Comment by lliioollcn** [comment]
你可以使用+1 plus

**Comment by shiroringo** [comment]
> 你可以使用+1 plus

和他一样的问题，但是我是LSPatch，
日志如下
`1.3.1.r974.735d9ad
QQ8.9.5(1)
PID: 23677, UID: 10333
cc.ioctl.hook.RepeaterHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: method == null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:2)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:10)
	at cc.ioctl.hook.RepeaterHook.initOnce(RepeaterHook.java:9)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:3)
	at io.github.qauxv.core.InjectDelayableHooks.doInitDelayableHooksMP(InjectDelayableHooks.java:4)
	at io.github.qauxv.fragment.EulaFragment.onClick(EulaFragment.kt:13)
	at android.view.View.performClick(View.java:7188)
	at android.view.View.performClickInternal(View.java:7165)
	at android.view.View.access$3500(View.java:814)
	at android.view.View$PerformClick.run(View.java:27664)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

`
然后换用+1plus有图标，但是+1功能只能复读纯文本内容，其他的内容狂按+1就是不复读……

**Comment by keta1** [comment]
经测试，使用 +1 plus 在此版本没有问题
