### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by keaidehuangpi** [cinit/QAuxiliary#178]
### Steps to reproduce/复现步骤

打开消息+1
对着一个人的回复消息+1

### Expected behaviour/预期行为

+1这条消息就像其他的消息一样

### Actual behaviour/实际行为

什么都没做

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

QQ8.8.93

### Module Version/模块版本

1.3.1.r1008.a2eae6c

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.1.r1008.a2eae6c
QQ8.8.93(2886)
PID: 12595, UID: 10504
cc.ioctl.hook.RepeaterHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
	at cc.ioctl.hook.RepeaterHook.lambda$initOnce$7(RepeaterHook.java:16)
	at cc.ioctl.hook.RepeaterHook.$r8$lambda$5QIX6I3KvQSDFOAKvhUOl0WooMg(Unknown Source:0)
	at cc.ioctl.hook.RepeaterHook$$ExternalSyntheticLambda3.afterHookedMethod(Unknown Source:2)
	at cc.ioctl.util.HookUtils$1.afterHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.apx$ʼ.ᐝ(SourceFile:334)
	at exp.ani.a(SourceFile:262)
	at exp.ani.a(SourceFile:191)
	at com.tencent.mobileqq.activity.aio.item.ReplyTextItemBuilder_535645708840.F(Unknown Source:46)
	at com.tencent.mobileqq.activity.aio.BaseBubbleBuilder.q(P:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at exp.anj.invoke(Native Method)
	at exp.ans.ˏ(SourceFile:248)
	at exp.ani.invokeOriginalMethod(SourceFile:408)
	at exp.ani.a(SourceFile:246)
	at exp.ani.a(SourceFile:191)
	at com.tencent.mobileqq.activity.aio.BaseBubbleBuilder_538643451584.q(Unknown Source:61)
	at com.tencent.mobileqq.activity.aio.ChatAdapter1.getView(P:8)
	at com.tencent.widget.HeaderViewListAdapter.getView(P:5)
	at com.tencent.widget.AbsListView.obtainView(P:11)
	at com.tencent.widget.ListView.makeAndAddView(P:6)
	at com.tencent.widget.ListView.fillDown(P:6)
	at com.tencent.widget.ListView.fillGap(P:5)
	at com.tencent.widget.AbsListView.trackMotionScroll(P:45)
	at com.tencent.mobileqq.activity.aio.anim.MoveToBottomScroller.c(P:31)
	at com.tencent.mobileqq.activity.aio.anim.MoveToBottomScroller.run(P:1)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by teble** [comment]
+1 plus 请
