### ISSUE TITLE
[Bug] 隐藏群聊共同好友异常

### ISSUE THREAD

**Issue by VictoriousRaptor** [cinit/QAuxiliary#180]
### Steps to reproduce/复现步骤

1. 开启“隐藏群聊共同好友提醒”
2. 提示异常

### Expected behaviour/预期行为

隐藏群聊共同好友

### Actual behaviour/实际行为

模块提示“隐藏群聊共同好友提醒”功能异常

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.4 (6609) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.4.7

### Module Version/模块版本

v1.3.2.r1014.fb897aa

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
1.3.2.r1014.fb897aa
TIM3.4.7(1238)
PID: 2684, UID: 10244
xyz.nextalone.hook.HideTroopAddTips
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.IllegalStateException: dex deobfuscation is not meant to be available now
	at io.github.qauxv.util.dexkit.DexDeobfsProvider.getCurrentBackend(DexDeobfsProvider.kt:72)
	at io.github.qauxv.util.dexkit.DexKit.doFindMethod(DexKit.java:14)
	at xyz.nextalone.hook.HideTroopAddTips$initOnce$1.invoke(HideTroopAddTips.kt:2)
	at xyz.nextalone.hook.HideTroopAddTips$initOnce$1.invoke(HideTroopAddTips.kt:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:9)
	at xyz.nextalone.hook.HideTroopAddTips.initOnce(HideTroopAddTips.kt:6)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:377)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:48)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at com.tencent.mobileqq.startup.step.Step.doStep(SourceFile:153)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at anls.a(SourceFile:892)
	at anls.handleMessage(SourceFile:905)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by teble** [comment]
@VictoriousRaptor 故障排查-清空缓存后呢
