### ISSUE TITLE
[Bug] 小程序下拉&下载重定向

### ISSUE THREAD

**Issue by natsu1949** [cinit/QAuxiliary#191]
### Steps to reproduce/复现步骤

开启屏蔽小程序下拉显示初始化失败，有错误日志；下载重定向开启后没有显示失败，但是没有效果。之前用的是QQ去UE4版，换回来后仍然如此

### Expected behaviour/预期行为

功能正常使用

### Actual behaviour/实际行为

。

### XPosed Framework you used/你使用的XP框架

lsp1.8.2.6519

### QQ(TIM)版本/QQ(TIM) Version

QQ8.8.98

### Module Version/模块版本

1.3.2.r1014.fb897aa

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.2.r1014.fb897aa
QQ8.9.10(3296)
PID: 24732, UID: 10344
cc.ioctl.hook.HideMiniAppPullEntry
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.RuntimeException: getInitMiniAppObfsName() == null
	at cc.ioctl.hook.HideMiniAppPullEntry.initOnce(HideMiniAppPullEntry.java:19)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:102)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(Unknown Source:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by teble** [comment]
@natsu1949 先重置缓存解决

**Comment by natsu1949** [comment]
> @natsu1949 先重置缓存解决

重置后还是如此

**Comment by teble** [comment]
@natsu1949 用最新的ci

**Comment by natsu1949** [comment]
> @natsu1949 用最新的ci

下载重定向我发现把colorQQ2模块关掉就好了，但是以前都没事；小程序换最新的依然不行

**Comment by teble** [comment]
试一下最新的ci呢

**Comment by natsu1949** [comment]
> 试一下最新的ci呢

上个回复的时候已经换了

**Comment by teble** [comment]
在那之后又发布了新的ci，所以让你现在再试试

**Comment by natsu1949** [comment]
> 在那之后又发布了新的ci，所以让你现在再试试

新版已解决，谢谢
