### ISSUE TITLE
[Bug] “隐藏下拉小程序”失效

### ISSUE THREAD

**Issue by 498271674** [cinit/QAuxiliary#198]
### Steps to reproduce/复现步骤

突然发现功能失效

### Expected behaviour/预期行为

隐藏小程序

### Actual behaviour/实际行为

失效

### XPosed Framework you used/你使用的XP框架

LPSosed1.8.4(6609)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.10(3296)

### Module Version/模块版本

1.3.2.r1014.fb897aa

### Version requirement/版本要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.2.r1014.fb897aa
QQ8.9.10(3296)
PID: 22318, UID: 10234
cc.ioctl.hook.HideMiniAppPullEntry
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.RuntimeException: getInitMiniAppObfsName() == null
	at cc.ioctl.hook.HideMiniAppPullEntry.initOnce(HideMiniAppPullEntry.java:19)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:377)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:48)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.r(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.handleMessage(P:52)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by keta1** [comment]
@498271674 -[X] 你正在使用最新 CI 调试版本且启用详细日志
