### ISSUE TITLE
[Bug] 侧滑栏精简在8.6.0失效

### ISSUE THREAD

**Issue by cibimo** [cinit/QAuxiliary#205]
### Steps to reproduce/复现步骤

打开侧滑栏精简并勾选任意项目

### Expected behaviour/预期行为

精简项目

### Actual behaviour/实际行为

不起作用

### XPosed Framework you used/你使用的XP框架

API 版本 93  注入接口 Zygisk  Dex 优化器包装 支持  框架版本 1.8.4 (6609)  管理器版本 1.8.4 (6609)  系统版本 12 (API 31)  设备 Xiaomi Redmi 22011211C   系统架构 arm64-v8a

### QQ(TIM)版本/QQ(TIM) Version

8.6.0

### Module Version/模块版本

1.3.3.r1121.548d777

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.3.r1121.548d777
QQ8.6.0(1672)
PID: 21827, UID: 10355
me.kyuubiran.hook.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: Name: drawer_bottom_container,Static: true, Type: ignore
	at com.github.kyuubiran.ezxhelper.utils.FieldUtilsKt.field(FieldUtils.kt:174)
	at com.github.kyuubiran.ezxhelper.utils.FieldUtilsKt.getStaticObject$default(FieldUtils.kt:17)
	at me.kyuubiran.hook.SimplifyQQSettingMe$initOnce$1$1.afterHookedMethod(SimplifyQQSettingMe.kt:94)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:17)
	at com.tencent.mobileqq.activity.home.Conversation.t(P:3715)
	at com.tencent.mobileqq.activity.home.Conversation.T(P:3823)
	at com.tencent.mobileqq.activity.home.Conversation.d(P:449)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.b(P:1001)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:844)
	at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
	at mqq.os.MqqHandler.dispatchMessage(P:99)
	at mqq.os.MqqMessageQueue.dequeue(P:294)
	at mqq.os.MqqMessageQueue.queueIdle(P:251)
	at android.os.MessageQueue.next(MessageQueue.java:406)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8307)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by keta1** [comment]
fixed in d87e0b44b82e13b6d955ae53e58d4e9c2fbb8bf7
