### ISSUE TITLE
[Bug] TIM 中部分功能无法正常开启

### ISSUE THREAD

**Issue by EmptyDreams** [cinit/QAuxiliary#233]
### Steps to reproduce/复现步骤

启用“拦截异常体积图片加载”和“拦截资料卡异常体积压缩包”时提示初始化错误。

### Expected behaviour/预期行为

正常启用

### Actual behaviour/实际行为

提示初始化错误

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.0

### Module Version/模块版本

1.3.2.r1086.88dda46(1086)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

拦截异常体积图片加载：

```
1.3.2.r1086.88dda46
TIM3.5.0(1278)
PID: 13233, UID: 10265
cc.ioctl.hook.BlockFluxThief
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: DexTarget: CHttpDownloader
	at io.github.qauxv.util.dexkit.DexKit.requireClassFromCache(DexKit.kt:20)
	at cc.ioctl.hook.BlockFluxThief.initOnce(BlockFluxThief.java:3)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:102)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(Unknown Source:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)


```

拦截压缩包：

```
1.3.2.r1086.88dda46
TIM3.5.0(1278)
PID: 13233, UID: 10265
cc.ioctl.hook.InterceptZipBomb
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: DexTarget: CZipUtils
	at io.github.qauxv.util.dexkit.DexKit.requireClassFromCache(DexKit.kt:20)
	at cc.ioctl.hook.InterceptZipBomb.initOnce(InterceptZipBomb.java:5)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:102)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(Unknown Source:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)


```

**Comment by keta1** [comment]
请使用最新版模块
