### ISSUE TITLE
[Bug] 侧滑在8.9.23QQ失效

### ISSUE THREAD

**Issue by twoone-3** [cinit/QAuxiliary#238]
### Steps to reproduce/复现步骤

下载QQ最新版
侧滑精简失效

### Expected behaviour/预期行为

精简成功

### Actual behaviour/实际行为

没有精简

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.9.23

### Module Version/模块版本

1.3.5.r1153

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.5.r1153.c2ed23e
QQ8.9.23(3582)
PID: 15271, UID: 10287
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.TextView
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$1.afterHookedMethod(SimplifyQQSettingMe.kt:245)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:17)
	at com.tencent.mobileqq.activity.home.Conversation.V1(P:14)
	at com.tencent.mobileqq.activity.home.Conversation.e2(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.N0(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.c(P:14)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:2)
	at com.tencent.mobileqq.utils.aj.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.onQueueIdleTimeout(P:1)
	at mqq.os.MqqMessageQueue.handleMessage(P:9)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8303)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)

**Comment by twoone-3** [comment]
什么破机器人

**Comment by qwq233** [comment]
@twoone-3 预期行为
