### ISSUE TITLE
[Bug] 防撤回所有消息显示没收到

### ISSUE THREAD

**Issue by cicur** [cinit/QAuxiliary#248]
### Steps to reproduce/复现步骤

对方撤回消息

### Expected behaviour/预期行为

显示被撤回的消息内容

### Actual behaviour/实际行为

显示被撤回的消息未收到

### XPosed Framework you used/你使用的XP框架

lsposed 1.8.5

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.25.9945

### Module Version/模块版本

1.3.6.r1190.fbc9821

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.6.r1190.fbc9821
QQ8.9.25(3616)
PID: 5892, UID: 10255
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: G0(java.lang.String,int,long,long) in com.tencent.imcore.message.QQMessageFacade
	at cc.ioctl.util.Reflex.invokeVirtual(Reflex.java:169)
	at cc.ioctl.hook.msg.RevokeMsgHook.getMessage(RevokeMsgHook.java:68)
	at cc.ioctl.hook.msg.RevokeMsgHook.onRevokeMsg(RevokeMsgHook.java:92)
	at cc.ioctl.hook.msg.RevokeMsgHook.lambda$initOnce$1(RevokeMsgHook.java:39)
	at cc.ioctl.hook.msg.RevokeMsgHook.$r8$lambda$JsuunyW9TZIAmkKH3LLlau5fTF4(Unknown Source:0)
	at cc.ioctl.hook.msg.RevokeMsgHook$$ExternalSyntheticLambda1.beforeHookedMethod(Unknown Source:4)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.z2(Unknown Source:18)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.O(P:27)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.ck.c(P:5)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.ck.b(P:2)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.ck.a(P:1)
	at com.tencent.imcore.message.g.F(P:2)
	at com.tencent.imcore.message.g.K(P:6)
	at com.tencent.imcore.message.ah$f.j(P:1)
	at com.tencent.imcore.message.ah$f.c(P:32)
	at com.tencent.imcore.message.g$a.f(P:15)
	at com.tencent.imcore.message.ah$f.f(P:1)
	at com.tencent.imcore.message.g.L(P:22)
	at com.tencent.imcore.message.g.v(P:2)
	at com.tencent.mobileqq.app.l.P4(P:2)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:1)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:24)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.u.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:6)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at mqq.app.MainService.access$800(P:1)
	at mqq.app.MainService$4.onRecvCmdPush(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:39)
	at mqq.app.msghandle.MSFRespHandleTask.handlePushMsg(P:3)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by cicur** [comment]
![IMG_20221211_205932.jpg](https://user-images.githubusercontent.com/88472780/206905236-a88113b0-23ca-4d17-9569-7cb665563735.jpg)

**Comment by keta1** [comment]
![image](https://user-images.githubusercontent.com/41381927/206905431-5c9d7f9a-3494-4f40-8af5-223f0bfcaaaa.png)
根据官网显示版本，QQ8.9.25 为测试版，qa 不会考虑支持测试版，待 QQ8.9.25 正式发布后若有同样问题会进行修复

**Comment by cicur** [comment]
@keta1 官网已更新正式版，仍有此问题，日志一致。
QA 1.3.6.r1200
QQ 8.9.25.10005

**Comment by cicur** [comment]
@cinit 请求reopen
