### ISSUE TITLE
[Bug] 功能异常 通知加强异常

### ISSUE THREAD

**Issue by l0z0y** [cinit/QAuxiliary#272]
### Steps to reproduce/复现步骤

开启MessageStyle或通知进化plus

### Expected behaviour/预期行为

正常弹出气泡且功能正常

### Actual behaviour/实际行为

Messagestyle 开启异常，通知plus 点击气泡弹出界面后界面立即消失，plus故障排除功能无异常日志

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.9.23

### Module Version/模块版本

1.36

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.6.r1185.65bc1ae
QQ8.9.23(3584)
PID: 6954, UID: 10361
cc.ioctl.hook.notification.MessageStyleNotification
isInitialized: true
isInitializationSuccessful: true
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NumberFormatException: For input string: "3105005173"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at cc.ioctl.hook.notification.MessageStyleNotification$initOnce$1.invoke(MessageStyleNotification.kt:55)
	at cc.ioctl.hook.notification.MessageStyleNotification$initOnce$1.invoke(MessageStyleNotification.kt:1)
	at xyz.nextalone.util.HookUtilsKt$hookAfter$1.afterMethod(HookUtils.kt:3)
	at xyz.nextalone.bridge.NAMethodHook.afterHookedMethod(NAMethodHook.kt:20)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.g(Unknown Source:23)
	at com.tencent.mobileqq.service.d.v(P:11)
	at com.tencent.mobileqq.service.d.k(P:4)
	at com.tencent.mobileqq.app.cd.f(P:29)
	at com.tencent.mobileqq.app.cd.g(P:5)
	at com.tencent.mobileqq.app.QQAppInterface.showMessageNotificationWithPreview(P:4)
	at com.tencent.mobileqq.app.QQAppInterface.notifyMessageReceived(P:7)
	at com.tencent.mobileqq.app.QQAppInterface.handleReceivedMessage(P:16)
	at com.tencent.mobileqq.app.QQAppInterface.handleReceivedMessage(P:1)
	at com.tencent.mobileqq.app.MessageHandler.W7(P:1)
	at com.tencent.mobileqq.app.MessageHandler.L7(P:2)
	at com.tencent.mobileqq.app.MessageHandler.e2(P:1)
	at com.tencent.imcore.message.BaseMessageProcessor.o(P:3)
	at com.tencent.imcore.message.h.M(P:32)
	at com.tencent.imcore.message.h.w0(P:20)
	at com.tencent.imcore.message.h.v0(P:26)
	at com.tencent.imcore.message.h.C0(P:2)
	at com.tencent.imcore.message.h.v(P:4)
	at com.tencent.mobileqq.app.handler.receivesuccess.j.a(P:4)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:13)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:16)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.v.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:2)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at mqq.app.MainService.access$800(P:1)
	at mqq.app.MainService$3.onRecvResp(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handleRespMsg(P:139)
	at mqq.app.msghandle.MSFRespHandleTask.doHandleResp(P:2)
	at mqq.app.msghandle.MSFRespHandleTask.handleCommonMsg(P:1)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by keta1** [comment]
请使用最新 ci 版本后再反馈
