### ISSUE TITLE
[Bug] 群文件长按转存永久异常

### ISSUE THREAD

**Issue by RedDragon0293** [cinit/QAuxiliary#276]
### Steps to reproduce/复现步骤

开启后报错

### Expected behaviour/预期行为

不报错

### Actual behaviour/实际行为

报错

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.25.10005

### Module Version/模块版本

1.3.6.r1220.5898d6d

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.6.r1220.5898d6d
QQ8.9.25(3640)
PID: 6132, UID: 10287
cc.ioctl.hook.troop.TroopFileSaveLasting
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: 
[com.tencent.mobileqq.troop.data](http://com.tencent.mobileqq.troop.data/)
.TroopFileShowAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(
[Class.java:454](http://class.java:454/)
)
	at me.ketal.util.HookUtilKt.findClass(HookUtil.kt:1)
	at me.ketal.util.HookUtilKt.findClass$default(HookUtil.kt:6)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:3)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:9)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook(TroopFileSaveLasting.kt:6)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:3)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:9)
	at me.ketal.base.PluginDelayableHook.initOnce(PluginDelayableHook.kt:6)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(
[InjectDelayableHooks.java:35](http://injectdelayablehooks.java:35/)
)
	at io.github.qauxv.core.MainHook.performHook(
[MainHook.java:109](http://mainhook.java:109/)
)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(
[StartupRoutine.java:50](http://startuproutine.java:50/)
)
	at io.github.qauxv.startup.StartupHook.execStartupInit(
[StartupHook.java:46](http://startuphook.java:46/)
)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(
[StartupHook.java:50](http://startuphook.java:50/)
)
	at 
[de.robv.android](http://de.robv.android/)
.xposed.XposedBridge$AdditionalHookInfo.callback(
[XposedBridge.java:484](http://xposedbridge.java:484/)
)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.m(P:4)
	at 
[com.tencent.common.app](http://com.tencent.common.app/)
.BaseApplicationImpl.onCreate(P:12)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at 
[mqq.app](http://mqq.app/)
.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(
[ContentProvider.java:2120](http://contentprovider.java:2120/)
)
	at android.content.ContentProvider.attachInfo(
[ContentProvider.java:2093](http://contentprovider.java:2093/)
)
	at 
[android.app](http://android.app/)
.ActivityThread.installProvider(
[ActivityThread.java:8181](http://activitythread.java:8181/)
)
	at 
[android.app](http://android.app/)
.ActivityThread.installContentProviders(
[ActivityThread.java:7722](http://activitythread.java:7722/)
)
	at 
[android.app](http://android.app/)
.ActivityThread.handleBindApplication(
[ActivityThread.java:7586](http://activitythread.java:7586/)
)
	at 
[android.app](http://android.app/)
.ActivityThread.access$2600(
[ActivityThread.java:259](http://activitythread.java:259/)
)
	at 
[android.app](http://android.app/)
.ActivityThread$H.handleMessage(
[ActivityThread.java:2440](http://activitythread.java:2440/)
)
	at android.os.Handler.dispatchMessage(
[Handler.java:110](http://handler.java:110/)
)
	at android.os.Looper.loop(
[Looper.java:219](http://looper.java:219/)
)
	at 
[android.app](http://android.app/)
.ActivityThread.main(
[ActivityThread.java:8673](http://activitythread.java:8673/)
)
	at java.lang.reflect.Method.invoke(Native Method)
	at 
[com.android](http://com.android/)
.internal.os.RuntimeInit$MethodAndArgsCaller.run(
[RuntimeInit.java:513](http://runtimeinit.java:513/)
)
	at 
[com.android](http://com.android/)
.internal.os.ZygoteInit.main(
[ZygoteInit.java:1109](http://zygoteinit.java:1109/)
)
Caused by: java.lang.ClassNotFoundException: 
[com.tencent.mobileqq.troop.data](http://com.tencent.mobileqq.troop.data/)
.TroopFileShowAdapter
	... 41 more

**Comment by Hakuin123** [comment]
QQ8.8.50(2324)
1.4.1.r1395.eccb8bb(1395)

同样有此bug

1.4.1.r1395.eccb8bb
QQ8.8.50(2324)
PID: 19009, UID: 10605
cc.ioctl.hook.troop.TroopFileSaveLasting
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at me.ketal.util.HookUtilKt.findClass(HookUtil.kt:1)
	at me.ketal.util.HookUtilKt.findClass$default(HookUtil.kt:6)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:3)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:9)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook(TroopFileSaveLasting.kt:6)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:3)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:9)
	at me.ketal.base.PluginDelayableHook.initOnce(PluginDelayableHook.kt:6)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:35)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:117)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:87)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:126)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:158)
	at com.tencent.mobileqq.startup.step.Step.step(P:126)
	at com.tencent.mobileqq.startup.director.StartupDirector.a(P:430)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:337)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:471)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30)
	at mqq.app.AppContentProvider.onCreate(P:30)
	at com.tencent.biz.pubaccount.readinjoy.ReadInJoyDataProvider.onCreate(P:92)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2097)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2070)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8168)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
	at android.app.ActivityThread.access$2600(ActivityThread.java:260)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	... 45 more

**Comment by RedDragon0293** [comment]
我已收到邮件。谢谢！I have received the email. Thank you!

**Comment by Hakuin123** [comment]
最新版好像已修复

**Comment by RedDragon0293** [comment]
我已收到邮件。谢谢！I have received the email. Thank you!
