### ISSUE TITLE
[Bug] 防撤回功能报错

### ISSUE THREAD

**Issue by Hakuin123** [cinit/QAuxiliary#278]
### Steps to reproduce/复现步骤

查看功能异常列表

### Expected behaviour/预期行为

无报错

### Actual behaviour/实际行为

报错

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.25(3640)

### Module Version/模块版本

1.3.6.r1185.65bc1ae

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.6.r1185.65bc1ae
QQ8.9.25(3640)
PID: 2880, UID: 10468
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: G0(java.lang.String,int,long,long) in com.tencent.imcore.message.QQMessageFacade
	at cc.ioctl.util.Reflex.invokeVirtual(Reflex.java:169)
	at cc.ioctl.hook.msg.RevokeMsgHook.getMessage(RevokeMsgHook.java:68)
	at cc.ioctl.hook.msg.RevokeMsgHook.onRevokeMsg(RevokeMsgHook.java:92)
	at cc.ioctl.hook.msg.RevokeMsgHook.lambda$initOnce$1(RevokeMsgHook.java:39)
	at cc.ioctl.hook.msg.RevokeMsgHook.$r8$lambda$JsuunyW9TZIAmkKH3LLlau5fTF4(Unknown Source:0)
	at cc.ioctl.hook.msg.RevokeMsgHook$$ExternalSyntheticLambda1.beforeHookedMethod(Unknown Source:4)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:451)
	at LSPHooker_.z2(Unknown Source:18)
	at com.tencent.mobileqq.troop.utils.af.h(P:245)
	at com.tencent.imcore.message.ah$f.k(P:19)
	at com.tencent.imcore.message.ah$f.c(P:16)
	at com.tencent.imcore.message.g$a.f(P:15)
	at com.tencent.imcore.message.ah$f.f(P:1)
	at com.tencent.imcore.message.g.L(P:22)
	at com.tencent.imcore.message.g.v(P:2)
	at com.tencent.mobileqq.app.l.P4(P:2)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:1)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:24)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.u.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:6)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:471)
	at LSPHooker_.receiveMessageFromMSF(Unknown Source:14)
	at mqq.app.MainService.access$800(P:1)
	at mqq.app.MainService$4.onRecvCmdPush(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:39)
	at mqq.app.msghandle.MSFRespHandleTask.handlePushMsg(P:3)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:4)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by keta1** [comment]
请使用 最新 ci
