### ISSUE TITLE
[Bug] 自编译版本无法打开和初始化

### ISSUE THREAD

**Issue by 6DDUU6** [cinit/QAuxiliary#285]
### Steps to reproduce/复现步骤

1.clone本仓库并init子模块
2.使用AS打开本项目
3.Generate signed APK成功
4.传送到手机安装
=======
安装后无法打开app，在QQ内也没有看到QA按钮。
查看模块日志发现好像无法正常加载libqauxv.so（具体日志在下面）。
尝试过使用github ci（https://github.com/6DDUU6/QAuxiliary/actions/runs/3862203741）构建，但是照旧。

### Expected behaviour/预期行为

正常打开并初始化hook

### Actual behaviour/实际行为

点开app后卡死，一片空白，无法初始化hook

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.28

### Module Version/模块版本

QAuxv-v1.3.7.r1254.381896b-universal

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[ 2023-01-07T22:04:36.376    10251: 17701: 17701 E/LSPosed-Bridge  ] java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~YsA1zy0nKrdQfPvafBf1WQ==/io.github.qauxv-3cJEx-vfFAwGiPuGCr2r8g==/base.apk!/lib/arm64-v8a/libqauxv.so"
	at java.lang.Runtime.load0(Runtime.java:939)
	at java.lang.System.load(System.java:1628)
	at io.github.qauxv.util.Natives.load(Natives.java:49)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:43)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.m(P:4)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:12)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7039)
	at android.app.ActivityThread.access$1600(ActivityThread.java:265)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2042)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by cinit** [comment]
@6DDUU6 你好，请以 debug 方式编译 apk, relesse 有签名校验

**Comment by 6DDUU6** [comment]
> @6DDUU6 你好，请以 debug 方式编译 apk, relesse 有签名校验

啊这，我试试

**Comment by keta1** [comment]
https://github.com/cinit/QAuxiliary/blob/873fd0729c63751780819a3740822333746bfc9e/app/build.gradle.kts#L131
如果需要使用 release ，可以这样替换 签名信息
