### ISSUE TITLE
[Bug] 更新1.3.7后QQ版本8.8.50批量撤回信息异常

### ISSUE THREAD

**Issue by YHSanSheng** [cinit/QAuxiliary#287]
### Steps to reproduce/复现步骤

使用QQ8.8.50多选撤回任意信息

### Expected behaviour/预期行为

正常撤回信息

### Actual behaviour/实际行为

java.lang.RuntimeException: QQMessageFacade :Unsupported Version: 8.8.50
	at io.github.qauxv.tlb.ConfigTable.getConfig(ConfigTable.kt:30)
	at io.github.qauxv.bridge.QQMessageFacade.revokeMessage(QQMessageFacade.java:46)
	at me.ketal.hook.MultiActionHook.recall(MultiActionHook.kt:64)
	at me.ketal.hook.MultiActionHook.create$lambda$2(MultiActionHook.kt:7)
	at me.ketal.hook.MultiActionHook.$r8$lambda$IN6B2mmkEtOSXXKXQGCxuD-T1FM(Unknown Source:0)
	at me.ketal.hook.MultiActionHook$$ExternalSyntheticLambda0.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7322)
	at android.view.View.performClickInternal(View.java:7296)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28319)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### XPosed Framework you used/你使用的XP框架

太极 阴

### QQ(TIM)版本/QQ(TIM) Version

8.8.50(2324)

### Module Version/模块版本

1.3.7.r1247.db93733(1247)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.7.r1247.db93733
QQ8.8.50(2324)
PID: 27636, UID: 10307
me.ketal.hook.MultiActionHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by cinit** [comment]
@YHSanSheng 更新 CI, CI 已经修了
