### ISSUE TITLE
[Bug] 多选撤回报错(QQ 8.6.0)

### ISSUE THREAD

**Issue by OnlyNaya** [cinit/QAuxiliary#290]
### Steps to reproduce/复现步骤

1.打开"批量撤回消息"
2.多选消息并点击撤回图标
3.报错

### Expected behaviour/预期行为

成功批量撤回消息，没有报错(但当选择过多时可能提示"撤回失败"，重新操作即可)
在更新到此模块1.3.7版本(github releases)前并没有出现此错误，更新后异常

### Actual behaviour/实际行为

出现报错提示框，无法撤回消息
![Screenshot_20230109_144444_com tencent mobileqq](https://user-images.githubusercontent.com/119770909/211253968-942e9ee1-82b9-4cd8-a340-8f93aec4dd77.jpg)

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.6.0

### Module Version/模块版本

1.3.7.r1247.db93733(1247)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

功能异常列表未提示错误
![Screenshot_20230109_145204](https://user-images.githubusercontent.com/119770909/211254635-25f4a234-3c50-4134-885e-29c302cb26d7.jpg)
当点击撤回图标时出现以下错误(同实际行为处图)：
java.lang.RuntimeException: QQMessageFacade :Unsupported Version: 8.6.0
	at io.github.qauxv.tlb.ConfigTable.getConfig(ConfigTable.kt:30)
	at io.github.qauxv.bridge.QQMessageFacade.revokeMessage(QQMessageFacade.java:46)
	at me.ketal.hook.MultiActionHook.recall(MultiActionHook.kt:64)
	at me.ketal.hook.MultiActionHook.create$lambda$2(MultiActionHook.kt:7)
	at me.ketal.hook.MultiActionHook.$r8$lambda$IN6B2mmkEtOSXXKXQGCxuD-T1FM(Unknown Source:0)
	at me.ketal.hook.MultiActionHook$$ExternalSyntheticLambda0.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at com.tencent.rmonitor.looper.LooperProxy.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by cinit** [comment]
@OnlyNaya 更新CI

**Comment by OnlyNaya** [comment]
> @OnlyNaya 更新CI

已重新安装，但仍未起效
TG群和github releases最新版(1.3.7.r1247.db93733(1247) 内部版本号1247)
请问除了降级还有什么方法吗😂

https://user-images.githubusercontent.com/119770909/211256041-83041b41-e0a2-4a1d-8c29-893ce325263c.mp4

**Comment by huajijam** [comment]
@OnlyNaya 更新 CI

**Comment by cinit** [comment]
@OnlyNaya 你需要使用 r1269, r1247 已经过时了

**Comment by OnlyNaya** [comment]
谢谢作者，已经解决了
原谅我我不理解CI和推荐的CI
