### ISSUE TITLE
[Bug] 开启复读机之后加号一大堆（祖传老秘方）

### ISSUE THREAD

**Issue by Q2297045667** [cinit/QAuxiliary#325]
### Steps to reproduce/复现步骤

开启复读机

### Expected behaviour/预期行为

每条消息后面只显示一个+号

### Actual behaviour/实际行为

同一条消息前后最多可以显示3个+号
![Screenshot_2023-02-15-10-28-42-092_com tencent tim](https://user-images.githubusercontent.com/42416195/218912634-1f7ed6eb-9df7-4c3d-84ee-4d641444bd94.jpg)
头皮发麻
![Screenshot_2023-02-15-10-27-40-416_com tencent tim](https://user-images.githubusercontent.com/42416195/218912744-34e1d857-8ff6-455d-889d-95fa84a8cbb0.jpg)
功能调试显示异常
![Screenshot_2023-02-15-10-38-47-952_com tencent tim](https://user-images.githubusercontent.com/42416195/218913226-ec963062-2ed1-44f7-a1e6-cebe53f52279.jpg)

### XPosed Framework you used/你使用的XP框架

LSP最新版本（老版本同样）

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.0.3148（与版本无关）QQ也同样的问题

### Module Version/模块版本

1.4.0.r1347.58ae9ad(1347)（QN也有同样的问题）

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.0.r1347.58ae9ad
TIM3.5.0(1288)
PID: 19063, UID: 10294
cc.ioctl.hook.ui.chat.RepeaterHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 44
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
	at cc.ioctl.hook.ui.chat.RepeaterHook.lambda$initOnce$3(RepeaterHook.java:247)
	at cc.ioctl.hook.ui.chat.RepeaterHook.$r8$lambda$VDir13Lrb8-kaLWikF7iKEXRF9g(RepeaterHook.java:1)
	at cc.ioctl.hook.ui.chat.RepeaterHook$$ExternalSyntheticLambda4.afterHookedMethod(R8$$SyntheticClass:3)
	at cc.ioctl.util.HookUtils$1.afterHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.a(Unknown Source:23)
	at com.tencent.mobileqq.activity.aio.BaseBubbleBuilder.a(SourceFile:491)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.a(Unknown Source:34)
	at wit.getView(SourceFile:288)
	at ausg.getView(SourceFile:230)
	at com.tencent.widget.AbsListView.obtainView(SourceFile:2252)
	at com.tencent.widget.ListView.makeAndAddView(SourceFile:2071)
	at com.tencent.widget.ListView.fillUp(SourceFile:910)
	at com.tencent.widget.ListView.fillSpecificBottom(SourceFile:1512)
	at com.tencent.widget.ListView.layoutChildren(SourceFile:1862)
	at com.tencent.widget.AbsListView.onLayout(SourceFile:2102)
	at com.tencent.widget.ListView.onLayout(SourceFile:1684)
	at com.tencent.mobileqq.bubble.ChatXListView.onLayout(SourceFile:415)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.RelativeLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at com.tencent.widget.XPanelContainer.onLayout(SourceFile:1115)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.RelativeLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.RelativeLayout.onLayout(Unknown Source:42)
	at com.tencent.mobileqq.activity.fling.TopGestureLayout.onLayout(SourceFile:637)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at com.tencent.mobileqq.widget.DrawerFrame.onLayout(SourceFile:299)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:184)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at com.android.internal.policy.DecorView.onLayout(Unknown Source:0)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.view.ViewRootImpl.performLayout(Unknown Source:32)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:2202)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:530)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
	at cc.ioctl.hook.ui.chat.RepeaterHook.lambda$initOnce$3(RepeaterHook.java:247)
	at cc.ioctl.hook.ui.chat.RepeaterHook.$r8$lambda$VDir13Lrb8-kaLWikF7iKEXRF9g(RepeaterHook.java:1)
	at cc.ioctl.hook.ui.chat.RepeaterHook$$ExternalSyntheticLambda4.afterHookedMethod(R8$$SyntheticClass:3)
	at cc.ioctl.util.HookUtils$1.afterHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.a(Unknown Source:23)
	at com.tencent.mobileqq.activity.aio.BaseBubbleBuilder.a(SourceFile:491)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.a(Unknown Source:34)
	at wit.getView(SourceFile:288)
	at ausg.getView(SourceFile:230)
	at com.tencent.widget.AbsListView.obtainView(SourceFile:2252)
	at com.tencent.widget.ListView.makeAndAddView(SourceFile:2071)
	at com.tencent.widget.ListView.fillUp(SourceFile:910)
	at com.tencent.widget.ListView.correctTooHigh(SourceFile:1618)
	at com.tencent.widget.ListView.fillGap(SourceFile:848)
	at com.tencent.widget.AbsListView.trackMotionScroll(SourceFile:5604)
	at com.tencent.mobileqq.activity.aio.anim.MoveToBottomScroller.run(SourceFile:280)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:509)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)

java.lang.NullPoin

**Comment by Q2297045667** [comment]
问题补充，+号缩小（其实有的时候还会变大）
![Screenshot_2023-02-15-10-46-31-971_com tencent tim](https://user-images.githubusercontent.com/42416195/218914371-dbcad205-eafd-425b-a521-c8ef25a0828e.jpg)

**Comment by klxiaoniu** [comment]
我的建议是不要打开重复的功能，以免冲突:)

**Comment by OnlyNaya** [comment]
> 我的建议是不要打开重复的功能，以免冲突:)

事实上只打开+1关闭+1plus也会出现此问题，我的Tim也是这样(笑)

**Comment by xiuciy** [comment]
Tim一直都这样，+1图片出现的位置很迷，至于图标大小是消息长了就变小，消息短就正常，一直也没修复
