### ISSUE TITLE
[Bug] 消息＋1功能存在错误

### ISSUE THREAD

**Issue by dbdosk7** [cinit/QAuxiliary#327]
### Steps to reproduce/复现步骤

1. 聊天和消息→消息＋1
2. 打开消息＋1开关

### Expected behaviour/预期行为

无异常

### Actual behaviour/实际行为

屏幕上方出现提示：初始化失败

### XPosed Framework you used/你使用的XP框架

Zygisk - LSPosed v1.8.6(6712)

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.28(3700)

### Module Version/模块版本

1.4.0.r1347.58ae9ad

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.0.r1347.58ae9ad
QQ8.9.28(3700)
PID: 32211, UID: 10374
cc.ioctl.hook.ui.chat.RepeaterHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: method == null
	at java.util.Objects.requireNonNull(Objects.java:245)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:2)
	at cc.ioctl.util.HookUtils.hookAfterIfEnabled(HookUtils.java:10)
	at cc.ioctl.hook.ui.chat.RepeaterHook.initOnce(RepeaterHook.java:93)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:102)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(HookInstaller.java:1)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by dbdosk7** [comment]
![Screenshot_2023-02-18-16-36-10-840_com tencent mo](https://user-images.githubusercontent.com/125729071/219851243-16028637-8e9c-4986-be71-0fad31cb96aa.jpg)
