### ISSUE TITLE
[Bug] TIM3.5.1 修改@顺序有时无效

### ISSUE THREAD

**Issue by OnlyNaya** [cinit/QAuxiliary#377]
### Steps to reproduce/复现步骤

1. 打开标题所述功能
2. 在不同的群测试@(未知机制，测试的两个群均在群助手里，且至少有一个群的群员群名片有特殊符号，不知是否构成影响)

### Expected behaviour/预期行为

如图示正常排序，在部分群聊正常
![Screenshot_20230402_214736](https://user-images.githubusercontent.com/119770909/229358893-9bd7ba1f-a17e-41ae-bbf6-a487105bf095.jpg)

### Actual behaviour/实际行为

在部分群里未成功，并和默认一致，且报错
![Screenshot_20230402_214504](https://user-images.githubusercontent.com/119770909/229358870-4ccadd89-8a69-483e-9075-dd11ded86bab.jpg)

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

Tim 3.5.1(1298)

### Module Version/模块版本

1.4.0.r1391.f8ac91b(1391) → 1.4.1.r1402.6c39ad3(1402)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.0.r1391.f8ac91b
TIM3.5.1(1298)
PID: 32761, UID: 10535
me.ketal.hook.SortAtPanel
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at me.ketal.hook.SortAtPanel$initOnce$1$2.invoke(SortAtPanel.kt:13)
	at me.ketal.hook.SortAtPanel$initOnce$1$2.invoke(SortAtPanel.kt:1)
	at xyz.nextalone.util.HookUtilsKt$hookBefore$1.beforeMethod(HookUtils.kt:3)
	at xyz.nextalone.bridge.NAMethodHook.beforeHookedMethod(NAMethodHook.kt:20)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:451)
	at LSPHooker_.a(Unknown Source:11)
	at com.tencent.mobileqq.troop.quickat.ui.AIOAtSearchManager.handleMessage(SourceFile:105)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by keta1** [comment]
这个问题很奇怪，你有电脑吗，我想远程来看看

**Comment by OnlyNaya** [comment]
> 这个问题很奇怪，你有电脑吗，我想远程来看看

我没有电脑（
我也感觉很奇怪，毕竟这有的群可以，有的不行，实在不行模拟一下，我也没有什么好的办法

**Comment by OnlyNaya** [comment]
之前QQ8.6.0一直没出现过(无论是哪个群聊)，被TX和谐旧版后被迫换了Tim5.3.1，就出问题了
