### ISSUE TITLE
新版QQ侧边栏隐藏失效[Bug] 

### ISSUE THREAD

**Issue by XwumingX** [cinit/QAuxiliary#410]
### Steps to reproduce/复现步骤

新版qq侧滑不知道啥时候更新了，变得花里胡哨，隐藏失效了

### Expected behaviour/预期行为

应该能按照设定隐藏

### Actual behaviour/实际行为

没被隐藏

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

8.9.35(3814)

### Module Version/模块版本

1.4.1.r1395.eccb8bb(1395)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1395.eccb8bb
QQ8.9.35(3814)
PID: 25346, UID: 10360
cc.ioctl.hook.qzone.HideQZMTitleBarEntrance
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: No method com.qzone.reborn.qzmoment.itemview.QZMTitleBarEntranceManager.*[class android.content.Context, class android.view.ViewGroup, class android.widget.ImageView] with return type void found
	at cc.ioctl.util.Reflex.findSingleMethod(Reflex.java:198)
	at cc.ioctl.hook.qzone.HideQZMTitleBarEntrance.initOnce(HideQZMTitleBarEntrance.kt:62)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:35)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:117)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:87)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:50)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.startup.step.LoadDex.doStep(Unknown Source:0)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.m(P:4)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:12)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7853)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7370)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by klxiaoniu** [comment]
@XwumingX CI版已上线临时性功能：侧滑栏-禁止新样式侧滑栏。另外，你提供的日志是隐藏空间“此刻”入口的，如果没有云控到新版本空间请关闭，因为没有适配老版本的界面
