### ISSUE TITLE
[Bug] 防撤回功能出现问题

### ISSUE THREAD

**Issue by ZoruaFox** [cinit/QAuxiliary#452]
### Steps to reproduce/复现步骤

1.Run QAuxiliary normally
2.Warnings shows in log files.

### Expected behaviour/预期行为

无报错运行。

### Actual behaviour/实际行为

防撤回运转基本正常但存在报错。

### XPosed Framework you used/你使用的XP框架

太极·青钢影10.3.2.03081020-9488

### QQ(TIM)版本/QQ(TIM) Version

8.9.63(4190)

### Module Version/模块版本

1.4.1.r1522.53ee6f9(1522)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1522.53ee6f9
QQ8.9.63(4190)
PID: 14204, UID: 10530
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: J0(java.lang.String,int,long,long) in com.tencent.imcore.message.QQMessageFacade
	at cc.ioctl.util.Reflex.invokeVirtual(SourceFile:173)
	at cc.ioctl.hook.msg.RevokeMsgHook.getMessage(SourceFile:68)
	at cc.ioctl.hook.msg.RevokeMsgHook.onRevokeMsg(SourceFile:77)
	at cc.ioctl.hook.msg.RevokeMsgHook.lambda$initOnce$1(SourceFile:39)
	at cc.ioctl.hook.msg.RevokeMsgHook.$r8$lambda$JsuunyW9TZIAmkKH3LLlau5fTF4(Unknown Source:0)
	at cc.ioctl.hook.file.BaseApk$$ExternalSyntheticLambda0.beforeHookedMethod(Unknown Source:22)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(SourceFile:15)
	at de.robv.android.xposed.ExposedHelper.beforeHookedMethod(SourceFile:48)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.o0o0000o0o000oooOO0o0o00o000oo0ooo00oo(SourceFile:304)
	at exp.and.callBeforeMethodHooked(SourceFile:490)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:101)
	at com.tencent.imcore.message.QQMessageFacade.b2(Unknown Source:0)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.N(P:27)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.s(P:3)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.J(P:15)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.c(P:12)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.a(P:1)
	at com.tencent.imcore.message.h.R(P:2)
	at com.tencent.imcore.message.h.N(P:48)
	at com.tencent.imcore.message.p.c(P:18)
	at com.tencent.imcore.message.C2CMessageProcessorCallback.y(P:2)
	at com.tencent.imcore.message.h.O(P:1)
	at com.tencent.imcore.message.h.M(P:17)
	at com.tencent.imcore.message.h.x0(P:20)
	at com.tencent.imcore.message.h.w0(P:26)
	at com.tencent.imcore.message.h.D0(P:2)
	at com.tencent.imcore.message.h.v(P:4)
	at com.tencent.mobileqq.app.handler.b.i.a(P:4)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:3)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:16)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.t.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:2)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at exp.ane.camille(Native Method)
	at exp.anb.o0o0000o0o000oooOO0o0o00o000oo0ooo00oo(SourceFile:177)
	at exp.anb.o0o0000o0o000oooOO0o0o00o000oo0ooo00oo(SourceFile:71)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:121)
	at mqq.app.MainService.receiveMessageFromMSF(Unknown Source:0)
	at mqq.app.MainService.access$700(P:1)
	at mqq.app.MainService$3.onRecvResp(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handleRespMsg(P:139)
	at mqq.app.msghandle.MSFRespHandleTask.doHandleResp(P:2)
	at mqq.app.msghandle.MSFRespHandleTask.handleCommonMsg(P:1)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:7)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by WildXBird** [comment]
> 更新8.9.63.11390后功能基本上全部失效了，不只是防撤回

有其他替代品吗？

**Comment by Andy-Chuck** [comment]
> 

TG频道里新发的版本已经大部分功能正常使用了
