### ISSUE TITLE
[Bug] 带图回复无法使用

### ISSUE THREAD

**Issue by getcurl** [cinit/QAuxiliary#458]
### Steps to reproduce/复现步骤

这个可以不用填吧

### Expected behaviour/预期行为

长按选择回复消息可插入表情包

### Actual behaviour/实际行为

无法使用

### XPosed Framework you used/你使用的XP框架

LSPosedv1.8.6 (6712)

### QQ(TIM)版本/QQ(TIM) Version

8.9.63(4194) NT版

### Module Version/模块版本

1.4.1.r1546.cf7cd92(1546)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1546.cf7cd92
QQ8.9.63(4194)
PID: 13623, UID: 10239
cc.hicore.hook.ReplyMsgWithImg
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: CGuildHelperProvider.INSTANCE
	at java.util.Objects.requireNonNull(Objects.java:245)
	at cc.hicore.hook.ReplyMsgWithImg.initOnce(SourceFile:19)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:122)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:112)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.a(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.c.d(P:1)
	at com.tencent.qqnt.startup.c.f(Unknown Source:0)
	at com.tencent.qqnt.startup.b.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by CatOverrun** [comment]
测试8.9.33中，此功能正常。
外加8.9.68，8.9.70中，此功能依旧失效。报错仍为NullPointer

**Comment by getcurl** [comment]
> 测试8.9.33中，此功能正常。 外加8.9.68，8.9.70中，此功能依旧失效。报错仍为NullPointer

:-( 嘤

**Comment by Origin0915** [comment]
> 测试8.9.33中，此功能正常。
> 外加8.9.68，8.9.70中，此功能依旧失效。报错仍为NullPointer

8.9.68往后版本失效的话能修复吗？
