### ISSUE TITLE
[Bug] QQNT版本侧划栏精简异常

### ISSUE THREAD

**Issue by SkyGao2005** [cinit/QAuxiliary#460]
### Steps to reproduce/复现步骤

1. 打开侧划栏-侧划栏精简
2. 选择精简项
3. 重启QQ

### Expected behaviour/预期行为

选择的精简项不显示

### Actual behaviour/实际行为

报错

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6(6712)

### QQ(TIM)版本/QQ(TIM) Version

8.9.68.11450

### Module Version/模块版本

1.4.1.r1550.9b11570

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1550.9b11570
QQ8.9.68(4218)
PID: 14825, UID: 10375
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
 at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke$lambda$4(SourceFile:46)
 at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.$r8$lambda$mB2ZNM6HnOCSBs2WfCd94N8CqdI(Unknown Source:0)
 at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$$ExternalSyntheticLambda0.afterHookedMethod(Unknown Source:0)
 at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
 at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
 at LSPHooker_.constructor(Unknown Source:14)
 at com.tencent.mobileqq.activity.QQSettingMe.g0(P:6)
 at com.tencent.mobileqq.activity.QQSettingMe.j0(P:2)
 at com.tencent.mobileqq.activity.QQSettingMe.<init>(P:4)
 at com.tencent.mobileqq.activity.home.Conversation.b0(P:11)
 at com.tencent.mobileqq.activity.home.Conversation.k0(P:4)
 at com.tencent.mobileqq.activity.home.Conversation.u(P:1)
 at com.tencent.mobileqq.activity.home.Conversation$o.c(P:13)
 at com.tencent.mobileqq.activity.home.Conversation$o.handleMessage(P:2)
 at com.tencent.mobileqq.utils.ak.handleMessage(P:2)
 at mqq.os.MqqHandler.dispatchMessage(P:7)
 at mqq.os.MqqMessageQueue.dequeue(P:15)
 at mqq.os.MqqMessageQueue.queueIdle(P:2)
 at android.os.MessageQueue.next(MessageQueue.java:410)
 at android.os.Looper.loopOnce(Looper.java:168)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8261)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by klxiaoniu** [comment]
@SkyGao2005 你好，非正式版版不作适配

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/211c0cb01b8b30fa189b54f94c366dc14c87466e
