### ISSUE TITLE
[Bug] 聊天字数统计失效

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#468]
### Steps to reproduce/复现步骤

打开聊天字数统计开关后功能不生效

### Expected behaviour/预期行为

正常情况下此处会生效，重启应用后在QQ侧滑栏内能看到字数和表情包统计信息

### Actual behaviour/实际行为

实际上无法生成
![1688737084271](https://github.com/cinit/QAuxiliary/assets/138845393/6c3f1a40-4f57-46cd-aa19-82dc5f8b32aa)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

1.4.1.r1567.8113188(1567)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1567.8113188
QQ8.9.68(4264)
PID: 32064, UID: 10333
xyz.nextalone.hook.ChatWordsCount
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.util.NoSuchElementException: Sequence contains no element matching the predicate.
	at xyz.nextalone.hook.ChatWordsCount$initOnce$1.invoke(SourceFile:21)
	at xyz.nextalone.hook.ChatWordsCount$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at xyz.nextalone.hook.ChatWordsCount.initOnce(Unknown Source:5)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(SourceFile:458)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:184)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:112)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at i.rBJfwGv.uQITYR.nVRTS.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.a(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.c.d(P:1)
	at com.tencent.qqnt.startup.c.f(Unknown Source:0)
	at com.tencent.qqnt.startup.b.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by HdShare** [comment]
尝试更新最新CI版，使用 统计聊天发送消息数量 进行平替
