### ISSUE TITLE
[Bug] 语音转发及保存功能异常

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#469]
### Steps to reproduce/复现步骤

自升级至QQ 8.9.63及以上版本，在QA内打开此开关后，安卓手机端提示报错，安卓平板端提示功能异常

### Expected behaviour/预期行为

语音转发后 也能听到原始语音消息

### Actual behaviour/实际行为

转发后变成如图所示
![Screenshot_2023-07-07-21-44-27-016_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/138845393/89dc3569-c1e0-4269-862c-bde8fdfa0d7e)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

1.4.1.r1567.8113188(1567)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1567.8113188
QQ8.9.68(4264)
PID: 9515, UID: 10371
cc.ioctl.hook.msg.PttForwardHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at io.github.qauxv.util.CustomMenu.createItemNt(SourceFile:13)
	at cc.ioctl.hook.msg.PttForwardHook.lambda$initOnce$3(SourceFile:23)
	at cc.ioctl.hook.msg.PttForwardHook.$r8$lambda$DrQN2q05UIyXs-be9EO9XweKsFM(Unknown Source:0)
	at cc.ioctl.hook.file.BaseApk$$ExternalSyntheticLambda1.afterHookedMethod(Unknown Source:30)
	at cc.ioctl.util.HookUtils$1.afterHookedMethod(SourceFile:15)
	at TAhDtlGhXJSKN.zbSGU.Uo.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.U0(Unknown Source:8)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.V0(P:4)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.e1(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.L0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.L0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.d.K0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.K0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.handleUIState(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.a(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.onChanged(P:1)
	at androidx.lifecycle.MVILiveData$MVIObserverWrapper.onChanged(P:2)
	at androidx.lifecycle.LiveData.considerNotify(P:6)
	at androidx.lifecycle.LiveData.dispatchingValue(P:8)
	at androidx.lifecycle.LiveData.setValue(P:4)
	at androidx.lifecycle.MutableLiveData.setValue(P:1)
	at androidx.lifecycle.MVILiveData.setValue(P:2)
	at com.tencent.mvi.mvvm.b.c.dispatchState$mvi_debug(P:4)
	at com.tencent.mvi.mvvm.BaseVM.updateUI(P:3)
	at com.tencent.mobileqq.aio.msglist.holder.component.c.o(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.c.m(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.q.m(P:17)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.q.handleIntent(P:1)
	at com.tencent.mvi.mvvm.BaseVB.sendIntent(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.AIOBubbleMsgItemVB.O0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.AIOBubbleMsgItemVB.g1(Unknown Source:0)
	at com.tencent.mobileqq.aio.msglist.holder.b.onLongClick(Unknown Source:4)
	at android.view.View.performLongClickInternal(View.java:7625)
	at android.view.View.performLongClick(View.java:7583)
	at com.tencent.qqnt.aio.holder.template.BubbleLayoutCompatPress.b(P:5)
	at com.tencent.qqnt.aio.holder.template.BubbleLayoutCompatPress.a(Unknown Source:0)
	at com.tencent.qqnt.aio.holder.template.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by klxiaoniu** [comment]
每次都复现吗？清除适配数据试下

**Comment by sxyofficial** [comment]
> 每次都复现吗？清除适配数据试下

更新模块后已恢复正常，之前清除适配数据还是会复现此类问题

**Comment by klxiaoniu** [comment]
好的

**Comment by sxyofficial** [comment]
> 好的

今天重新试了一下 发现还是无法转发语音消息

**Comment by sxyofficial** [comment]
> 好的



> 每次都复现吗？清除适配数据试下

复现版本在QQ8.9.63

**Comment by klxiaoniu** [comment]
@sxyofficial 无法复现，清除适配数据再试
