### ISSUE TITLE
[Bug] 屏蔽更新提醒失效并报错

### ISSUE THREAD

**Issue by PandaYuuHa** [cinit/QAuxiliary#47]
### Steps to reproduce/复现步骤

更新4.13下午功能修复后的模块，打开模块的屏蔽更新提醒功能

### Expected behaviour/预期行为

不显示版本更新提示

### Actual behaviour/实际行为

依旧有版本更新提示

### XPosed Framework you used/你使用的XP框架

太极 承影 9.0.0.01201725-7595

### QQ(TIM)版本/QQ(TIM) Version

QQ8.8.50(2324)

### Module Version/模块版本

1.2.1.r392.39abb48-armAll

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.1.r392.39abb48
QQ8.8.50(2324)
me.kyuubiran.hook.AntiUpdate
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException
	at com.github.kyuubiran.ezxhelper.utils.ReflectUtilsKt.findMethod(ReflectUtils.kt:181)
	at me.kyuubiran.hook.AntiUpdate.initOnce(AntiUpdate.kt:72)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:60)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:121)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.apx$ʼ.ᐝ(SourceFile:334)
	at exp.ani.a(SourceFile:262)
	at exp.ani.a(SourceFile:191)
	at com.tencent.mobileqq.startup.step.LoadData_494642615376.doStep(Unknown Source:11)
	at com.tencent.mobileqq.startup.step.Step.step(P:126)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:158)
	at com.tencent.mobileqq.startup.step.Step.step(P:126)
	at com.tencent.mobileqq.startup.step.Step.run(P:99)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by KyuubiRan** [comment]
fixed by 咕咕华
