### ISSUE TITLE
[Bug] 防撤回失效

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#470]
### Steps to reproduce/复现步骤

QA更新至1.4.1.r1567.8113188(1567)且QQ更新至8.9.68后，防撤回失效

### Expected behaviour/预期行为

正常情况下防撤回还是生效的

### Actual behaviour/实际行为

实测后发现，防撤回已失效
![Cache_4ef37f47998509ea](https://github.com/cinit/QAuxiliary/assets/138845393/2753b90f-b857-44f6-be6e-9fdaa4574248)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

1.4.1.r1567.8113188(1567)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1567.8113188
QQ8.9.68(4264)
PID: 10105, UID: 10333
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by sxyofficial** [comment]
新log
> 1.4.1.r1567.8113188
QQ8.9.68(4264)
PID: 24275, UID: 10371
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: J0(java.lang.String,int,long,long) in com.tencent.imcore.message.QQMessageFacade
	at cc.ioctl.util.Reflex.invokeVirtual(SourceFile:169)
	at cc.ioctl.hook.msg.RevokeMsgHook.getMessage(SourceFile:68)
	at cc.ioctl.hook.msg.RevokeMsgHook.onRevokeMsg(SourceFile:77)
	at cc.ioctl.hook.msg.RevokeMsgHook.lambda$initOnce$1(SourceFile:39)
	at cc.ioctl.hook.msg.RevokeMsgHook.$r8$lambda$JsuunyW9TZIAmkKH3LLlau5fTF4(Unknown Source:0)
	at cc.ioctl.hook.msg.RevokeMsgHook$$ExternalSyntheticLambda3.beforeHookedMethod(Unknown Source:4)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(SourceFile:15)
	at TAhDtlGhXJSKN.zbSGU.Uo.XposedBridge$AdditionalHookInfo.callback(Unknown Source:87)
	at LSPHooker_.b2(Unknown Source:18)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.N(P:27)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.s(P:3)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.J(P:15)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.c(P:12)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.a(P:1)
	at com.tencent.imcore.message.h.R(P:2)
	at com.tencent.imcore.message.h.N(P:48)
	at com.tencent.imcore.message.p.c(P:18)
	at com.tencent.imcore.message.C2CMessageProcessorCallback.y(P:2)
	at com.tencent.imcore.message.h.O(P:1)
	at com.tencent.imcore.message.h.M(P:17)
	at com.tencent.imcore.message.h.x0(P:20)
	at com.tencent.imcore.message.h.w0(P:26)
	at com.tencent.imcore.message.h.D0(P:2)
	at com.tencent.imcore.message.h.v(P:4)
	at com.tencent.mobileqq.app.handler.b.i.a(P:4)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:3)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:16)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.t.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:2)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at mqq.app.MainService.access$700(P:1)
	at mqq.app.MainService$3.onRecvResp(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handleRespMsg(P:139)
	at mqq.app.msghandle.MSFRespHandleTask.doHandleResp(P:2)
	at mqq.app.msghandle.MSFRespHandleTask.handleCommonMsg(P:1)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:7)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by TCSlX** [comment]
一样，我也失效

**Comment by CutePaper1** [comment]
+1

**Comment by SYuanLUV** [comment]
+1

**Comment by ssyximmlove** [comment]
+1

**Comment by klxiaoniu** [comment]
> 一样，我也失效



> +1



> +1



> +1

问题已收到，请勿发送无意义Comment，这里不是QQ群

**Comment by NGGCGG2** [comment]
我也来个log
`1.4.1.r1587.956a8c2
QQ8.9.68(4264)
PID: 32607, UID: 10368
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 2
java.lang.RuntimeException: AobScanUtils: validator failed for target 'RecallC2cSysMsg' with sequence 098d40f8f50300aa21008052f30302aa298d40f9 for result 0x16e5ac4
	at cc.ioctl.hook.msg.RevokeMsgHook.nativeInitNtKernelRecallMsgHook(Native Method)
	at cc.ioctl.hook.msg.RevokeMsgHook.initOnce(SourceFile:1)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.HookInstaller.allowEarlyInit(SourceFile:25)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:54)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:112)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.a(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.c.d(P:1)
	at com.tencent.qqnt.startup.c.f(Unknown Source:0)
	at com.tencent.qqnt.startup.b.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

java.lang.RuntimeException: AobScanUtils: validator failed for target 'RecallGroupSysMsg' with sequence 280040f961008052098d40f8298d40f9 for result 0x16e7124
	at cc.ioctl.hook.msg.RevokeMsgHook.nativeInitNtKernelRecallMsgHook(Native Method)
	at cc.ioctl.hook.msg.RevokeMsgHook.initOnce(SourceFile:1)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.HookInstaller.allowEarlyInit(SourceFile:25)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:54)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:112)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.a(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.c.d(P:1)
	at com.tencent.qqnt.startup.c.f(Unknown Source:0)
	at com.tencent.qqnt.startup.b.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

`

**Comment by klxiaoniu** [comment]
更新 CI 版观察

**Comment by xiemobiao** [comment]
现在好像在后台消息被撤回了还是看不到，在前台撤回的可以
