### ISSUE TITLE
[Bug] QQ8.9.63以上版本创建长按菜单项失败

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#473]
### Steps to reproduce/复现步骤

个人近期反复尝试QA多版本和QQ8.9.63/8.9.68后，确认语音转发和保存功能失效

### Expected behaviour/预期行为

正常情况下语音能够转发，转发后的语音还是可以听得到的「QQ8.9.63以下的版本是还可以转发语音消息」
![1688830097274](https://github.com/cinit/QAuxiliary/assets/138845393/da27b0c8-96e2-461b-b4cc-a5faf9e11eb6)

### Actual behaviour/实际行为

更新至QQ8.9.63及以上版本后，语音消息和转发功能已失效
![Screenshot_2023-07-08-23-29-23-155_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/138845393/001c46fb-ba9d-4928-ba70-e075bf7a3b0d)
![Screenshot_2023-07-08-23-30-07-231_com android browser-edit](https://github.com/cinit/QAuxiliary/assets/138845393/72920e27-93c5-482e-a5bc-15f544b3cdef)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.63及以上版本

### Module Version/模块版本

1.4.1.r1572.1330f16(1572)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1572.1330f16
QQ8.9.63(4194)
PID: 30402, UID: 10333
cc.ioctl.hook.msg.PttForwardHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at io.github.qauxv.util.CustomMenu.createItemNt(SourceFile:13)
	at cc.ioctl.hook.msg.PttForwardHook.lambda$initOnce$3(SourceFile:23)
	at cc.ioctl.hook.msg.PttForwardHook.$r8$lambda$DrQN2q05UIyXs-be9EO9XweKsFM(Unknown Source:0)
	at cc.ioctl.hook.file.BaseApk$$ExternalSyntheticLambda1.afterHookedMethod(Unknown Source:30)
	at cc.ioctl.util.HookUtils$1.afterHookedMethod(SourceFile:15)
	at oqlKVWPVqCpvT.yCXHXbMC.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.V0(Unknown Source:8)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.W0(P:4)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.f1(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.BaseContentComponent.M0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.M0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.d.L0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.L0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.AIOPttContentComponent.handleUIState(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.a(P:1)
	at com.tencent.mvi.mvvm.BaseVB$mObserver$2$a.onChanged(P:1)
	at androidx.lifecycle.MVILiveData$MVIObserverWrapper.onChanged(P:2)
	at androidx.lifecycle.LiveData.considerNotify(P:6)
	at androidx.lifecycle.LiveData.dispatchingValue(P:8)
	at androidx.lifecycle.LiveData.setValue(P:4)
	at androidx.lifecycle.MutableLiveData.setValue(P:1)
	at androidx.lifecycle.MVILiveData.setValue(P:2)
	at com.tencent.mvi.mvvm.b.c.dispatchState$mvi_debug(P:4)
	at com.tencent.mvi.mvvm.BaseVM.updateUI(P:3)
	at com.tencent.mobileqq.aio.msglist.holder.component.c.o(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.c.m(P:2)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.q.m(P:17)
	at com.tencent.mobileqq.aio.msglist.holder.component.ptt.q.handleIntent(P:1)
	at com.tencent.mvi.mvvm.BaseVB.sendIntent(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.AIOBubbleMsgItemVB.P0(P:1)
	at com.tencent.mobileqq.aio.msglist.holder.AIOBubbleMsgItemVB.h1(Unknown Source:0)
	at com.tencent.mobileqq.aio.msglist.holder.b.onLongClick(Unknown Source:2)
	at android.view.View.performLongClickInternal(View.java:7628)
	at android.view.View.performLongClick(View.java:7586)
	at com.tencent.qqnt.aio.holder.template.BubbleLayoutCompatPress.b(P:5)
	at com.tencent.qqnt.aio.holder.template.BubbleLayoutCompatPress.a(Unknown Source:0)
	at com.tencent.qqnt.aio.holder.template.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by klxiaoniu** [comment]
非常奇怪，我在8.9.63和8.9.68测试，均无法复现你这种情况。请提供更多环境信息，并尝试排查是否其他模块产生影响导致

**Comment by sxyofficial** [comment]
> 非常奇怪，我在8.9.63和8.9.68测试，均无法复现你这种情况。请提供更多环境信息，并尝试排查是否其他模块产生影响导致

试过了，用的框架是LSP1.8.6(6926)最新内测版，对QQ单用QA模块原生裤arm64，手机是小米11U，平板是小米平板5Pro5G，系统是安卓13版本的MIUI14

**Comment by klxiaoniu** [comment]
> > 非常奇怪，我在8.9.63和8.9.68测试，均无法复现你这种情况。请提供更多环境信息，并尝试排查是否其他模块产生影响导致
> 
> 试过了，用的框架是LSP1.8.6(6926)最新内测版，对QQ单用QA模块原生裤arm64，手机是小米11U，平板是小米平板5Pro5G，系统是安卓13版本的MIUI14

可考虑回退正式版LSPosed测试该功能是否正常

**Comment by klxiaoniu** [comment]
更新r1576尝试是否已修复

**Comment by 6DDUU6** [comment]
> 更新r1576尝试是否已修复

测试ok，已经修复
