### ISSUE TITLE
[Bug] qqnt最新版侧滑栏异常

### ISSUE THREAD

**Issue by PSERUM** [cinit/QAuxiliary#475]
### Steps to reproduce/复现步骤

侧滑栏拉开以后精简的项目并没有生效，在故障测试礼显示是黄色感叹号

### Expected behaviour/预期行为

侧滑栏精简的十几项全部不显示

### Actual behaviour/实际行为

侧滑栏拉开以后精简的项目并没有生效
![Screenshots_2023-07-09-23-45-01](https://github.com/cinit/QAuxiliary/assets/92060233/28608d35-444e-4661-9012-99834ac0206a)

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

V8.9.68.11450

### Module Version/模块版本

1.4.1.r1574.b8a3b69(1574)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1574.b8a3b69
QQ8.9.68(4218)
PID: 32393, UID: 10313
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke$lambda$4(SourceFile:165)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.$r8$lambda$oSNYb3Z8xJnNuP9RTcumdAooNeU(Unknown Source:0)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$$ExternalSyntheticLambda0.afterHookedMethod(Unknown Source:2)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.activity.QQSettingMe.g0(P:6)
	at com.tencent.mobileqq.activity.QQSettingMe.j0(P:2)
	at com.tencent.mobileqq.activity.QQSettingMe.<init>(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.b0(P:11)
	at com.tencent.mobileqq.activity.home.Conversation.k0(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.u(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$o.c(P:13)
	at com.tencent.mobileqq.activity.home.Conversation$o.handleMessage(P:2)
	at com.tencent.mobileqq.utils.ak.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.queueIdle(P:2)
	at android.os.MessageQueue.next(MessageQueue.java:404)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8022)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by lliioollcn** [comment]
你好，目前只针对新式侧滑栏进行了适配，在体验模式下的侧滑栏还没有适配呢

**Comment by klxiaoniu** [comment]
几天前已经适配了，更新正式版 QQ 再试，测试版不做适配
