### ISSUE TITLE
[Bug]  消息撤回小字显示错误

### ISSUE THREAD

**Issue by CutePaper1** [cinit/QAuxiliary#481]
### Steps to reproduce/复现步骤

在正常聊天情况下的对方消息撤回，打开防撤回功能

### Expected behaviour/预期行为

防撤回功能响应正常，消息撤回被拦截并显示小字：xxx撤回了一条消息

### Actual behaviour/实际行为

消息被拦截撤回，但小字部分显示：xxx撤回了一条消息（没收到）
![Screenshot_2023-07-11-22-00-39-024_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/139243174/2d2d42a1-204d-4919-bf82-ff6f21c58f23)
![Screenshot_2023-07-11-21-48-42-609_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/139243174/b50cb5c6-7942-4482-9fbb-5e325c19ce3b)

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.6(6712)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.58(4108)

### Module Version/模块版本

1.4.1.r1395.eccb8bb(1395)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1395.eccb8bb
QQ8.9.58(4108)
PID: 9252, UID: 10347
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: H0(java.lang.String,int,long,long) in com.tencent.imcore.message.QQMessageFacade
	at cc.ioctl.util.Reflex.invokeVirtual(Reflex.java:173)
	at cc.ioctl.hook.msg.RevokeMsgHook.getMessage(RevokeMsgHook.java:68)
	at cc.ioctl.hook.msg.RevokeMsgHook.onRevokeMsg(RevokeMsgHook.java:92)
	at cc.ioctl.hook.msg.RevokeMsgHook.lambda$initOnce$1(RevokeMsgHook.java:39)
	at cc.ioctl.hook.msg.RevokeMsgHook.$r8$lambda$JsuunyW9TZIAmkKH3LLlau5fTF4(RevokeMsgHook.java:1)
	at cc.ioctl.hook.msg.RevokeMsgHook$$ExternalSyntheticLambda1.beforeHookedMethod(R8$$SyntheticClass:3)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(HookUtils.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.A2(Unknown Source:18)
	at com.tencent.mobileqq.service.message.codec.decoder.msgType0x210.MsgType0x210Decoder.O(P:27)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.cj.c(P:5)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.cj.b(P:2)
	at com.tencent.imcore.message.ext.codec.decoder.msgType0x210.cj.a(P:1)
	at com.tencent.imcore.message.g.F(P:2)
	at com.tencent.imcore.message.g.K(P:6)
	at com.tencent.imcore.message.ah$f.j(P:1)
	at com.tencent.imcore.message.ah$f.c(P:32)
	at com.tencent.imcore.message.g$a.f(P:15)
	at com.tencent.imcore.message.g.L(P:22)
	at com.tencent.imcore.message.g.v(P:2)
	at com.tencent.mobileqq.app.BaseMessageHandler.dispatchRespToProcessor(P:2)
	at com.tencent.mobileqq.app.MessageHandler.onReceiveSuccess(P:1)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:10)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:6)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:24)
	at com.tencent.mobileqq.service.d.handleResponse(P:2)
	at com.tencent.common.app.AppInterface.receiveToService(P:2)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:1)
	at com.tencent.mobileqq.t.a.onReceive(P:5)
	at mqq.app.MSFServlet.onReceive(P:2)
	at mqq.app.ServletContainer.notifyMSFServlet(P:6)
	at mqq.app.MainService.receiveMessageFromMSF(P:33)
	at mqq.app.MainService.access$800(P:1)
	at mqq.app.MainService$4.onRecvCmdPush(P:1)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:39)
	at mqq.app.msghandle.MSFRespHandleTask.handlePushMsg(P:3)
	at mqq.app.msghandle.MSFRespHandleTask.run(P:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by klxiaoniu** [comment]
“我正在使用最新 CI 调试版本且启用详细日志”，知道什么是CI版吗？更新CI版再试
