### ISSUE TITLE
[Bug] MessagingStyle通知的回复功能在Wear OS上失效

### ISSUE THREAD

**Issue by cxzlw** [cinit/QAuxiliary#487]
### Steps to reproduce/复现步骤

1. 启用 MessagingStyle通知
2. 收到通知后在手表上回复
3. 手表显示成功，实际并未发送消息

### Expected behaviour/预期行为

手表显示成功，消息成功被发出

### Actual behaviour/实际行为

手表显示成功，实际并未发送消息

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.6.5

### Module Version/模块版本

1.4.1.r1585.58442b9

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

以下来自功能异常列表：
[MessagingStyleNotification-1689351588468.txt](https://github.com/cinit/QAuxiliary/files/12052174/MessagingStyleNotification-1689351588468.txt)
以下来自logcat：
```
2023-07-15 00:17:02.592 22779-22779 Bundle                  com.tencent.mobileqq                 W  Key KEY_REPLY expected String but value was a android.text.SpannableString.  The default value <null> was returned.
2023-07-15 00:17:02.592 22779-22779 Bundle                  com.tencent.mobileqq                 W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at moe.zapic.hook.MessagingStyleNotification$hookNonNt$2.beforeHookedMethod(SourceFile:55)
                                                                                                    	at BYbuk.HZ.GYJABplFOxd.z.XposedBridge$AdditionalHookInfo.callback(Unknown Source:87)
                                                                                                    	at LSPHooker_.onReceive(Unknown Source:14)
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4488)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8247)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by klxiaoniu** [comment]
@cxzlw 以前版本QA正常吗？（例如1.4.1.

**Comment by cxzlw** [comment]
> @cxzlw 以前版本QA正常吗？（例如1.4.1.r1395）

唔1395并不正常，我是从r1395.eccb8bb不正常然后升到ci版也不正常了来发issue的

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/c40e953ae65b80e84082b7e0c67d130b10b8387a
