### ISSUE TITLE
[Bug] QQV8.9.68.11565 设置界面不显示模块设置，功能失效

### ISSUE THREAD

**Issue by g1hu** [cinit/QAuxiliary#496]
### Steps to reproduce/复现步骤

更新QQ到V8.9.68.11565后，模块所有功能失效，QQ设置中模块设置消失，尝试过重装arm64apk或arm all apk均未解决，lsposed正常显示模块已启用，可以跳转app界面，故障排查无法跳转，点击无反应

### Expected behaviour/预期行为

功能正常允许，QQ设置中模块设置可见，故障排查正常跳转

### Actual behaviour/实际行为

功能完全不运行，QQ设置中模块设置不可见，故障排查未跳转，点击后无反应

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.6（6712）-Zygisk  API 93

### QQ(TIM)版本/QQ(TIM) Version

QQ V8.9.68.11565

### Module Version/模块版本

1.4.1.r1395.eccb8bb arm all

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排查无法进入，点击后无反应，无法获取日志，附件为lsposed模块日志 （仅部分，可能无实质性帮助）
[ 2023-07-17T21:57:29.989    10268: 11039: 11039 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T21:57:30.012    10268: 11039: 11039 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-07-17T21:57:30.125    10268: 11039: 11039 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T21:57:30.125    10268: 11039: 11039 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:01:41.832    10268: 13953: 13953 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T22:01:41.853    10268: 13953: 13953 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-07-17T22:01:41.900    10268: 13953: 13953 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:01:41.900    10268: 13953: 13953 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:18.612    10268: 14572: 14572 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T22:02:18.633    10268: 14572: 14572 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-07-17T22:02:18.700    10268: 14572: 14572 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:18.700    10268: 14572: 14572 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:31.996    10268: 14894: 14894 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T22:02:32.018    10268: 14894: 14894 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-07-17T22:02:32.099    10268: 14894: 14894 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:32.099    10268: 14894: 14894 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:54.268    10268: 15151: 15151 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T22:02:54.288    10268: 15151: 15151 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-07-17T22:02:54.336    10268: 15151: 15151 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github.qauxv.startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:02:54.336    10268: 15151: 15151 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/lib/arm64, /data/app/~~LJWIMoqqpvhgyDY2UGkGEg==/com.tencent.mobileqq-k4mKvEX9b-tlscou-tFrig==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.startup.StartupHook.initialize(StartupHook.java:15)
	at io.github..startup.HookEntry.handleLoadPackage(HookEntry.java:127)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3090)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6696)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[ 2023-07-17T22:04:24.769    10268: 16013: 16013 I/LSPosed-Bridge  ] Loading module io.github.qauxv from /data/app/~~KeX1YaQNcnjCtCm6QnnjxQ==/io.github.qauxv-J2jFEJXSSTLak-pRhzbKFw==/base.apk
[ 2023-07-17T22:04:24.790    10268: 16013: 16013 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry

**Comment by klxiaoniu** [comment]
CI 版早已解决，勾选选项的时候这么自信吗
