### ISSUE TITLE
[Bug] 清理最近消息失效

### ISSUE THREAD

**Issue by mingqitianxia12138** [cinit/QAuxiliary#497]
### Steps to reproduce/复现步骤

长按主页右上角加号
出现清理消息弹窗
点击任意清理出现清理错误提示
显示清理出错，并出现错误代码

### Expected behaviour/预期行为

正常情况下点击任意清理按钮，会清理主页消息 比如说，点击清理群消息，它就会把主页上都群消息都给删除掉

### Actual behaviour/实际行为

![IMG_20230718_145303](https://github.com/cinit/QAuxiliary/assets/124969423/a4673e7d-2797-47a2-bb8c-5c297b921143)

### XPosed Framework you used/你使用的XP框架

LSPosed-Zigysk版

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.63

### Module Version/模块版本

1.4.1.r1610.7f4Se3a

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1610.7f45e3a
QQ8.9.63(4194)
PID: 14225, UID: 99910583
xyz.nextalone.hook.CleanRecentChat
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<*>
	at xyz.nextalone.hook.CleanRecentChat.handler(SourceFile:17)
	at xyz.nextalone.hook.CleanRecentChat.access$handler(Unknown Source:0)
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1$1$1$1$2.invoke(SourceFile:6)
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1$1$1$1$2.invoke(SourceFile:1)
	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(SourceFile:84)
	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(SourceFile:12)
	at android.view.View.performClick(View.java:7559)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29660)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by lenmon1231** [comment]
+1

**Comment by NextAlone** [comment]
@lenmon1231 +1
