### ISSUE TITLE
[Bug] QQNT 8.9.68打开合并聊天记录查看信息失败

### ISSUE THREAD

**Issue by ternurarl** [cinit/QAuxiliary#507]
### Steps to reproduce/复现步骤

打开一项合并聊天记录
点击头像查看信息
弹出错误 IllegalStateException

### Expected behaviour/预期行为

可以看到此聊天记录的QQ群号和QQ号

### Actual behaviour/实际行为

弹出IllegalStateException错误
![Screenshot_2023-07-20-07-43-44-999_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/59920288/841125d4-e66a-46ac-8d3b-ccd472f8e28a)

### XPosed Framework you used/你使用的XP框架

1.8.6（6915）

### QQ(TIM)版本/QQ(TIM) Version

8.9.68.11565

### Module Version/模块版本

1.4.1.r1621.63de9cb

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

功能异常列表未出现错误，这是弹出的错误日志
java.lang.IllegalStateException: troopUin must be positive or null, got 0
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.createAndShowDialogCommon(SourceFile:231)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.access$createAndShowDialogCommon(Unknown Source:0)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$2.invoke$lambda$5(SourceFile:86)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$2.$r8$lambda$EKokVUL6cXBPOWmCzkFYbj-uClk(Unknown Source:0)
	at cc.ioctl.hook.msg.PttForwardHook$$ExternalSyntheticLambda1.onClick(Unknown Source:34)
	at android.view.View.performClick(View.java:7545)
	at android.view.View.performClickInternal(View.java:7522)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29567)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by klxiaoniu** [comment]
@ternurarl 这是预期行为，通常说明此合并转发中的信息存在问题。

**Comment by klxiaoniu** [comment]
你把消息显示 ID 和时间打开，然后点这个合并转发里面消息下面的灰字，把弹出的内容长截图给我看下

**Comment by klxiaoniu** [comment]
在1623版优化了，由于服务器传回NT版本的数据不包含群号，现只可展示该成员QQ
