### ISSUE TITLE
[Bug] 转发消息点头像查看详细信息 功能异常

### ISSUE THREAD

**Issue by CodePwn2021** [cinit/QAuxiliary#510]
### Steps to reproduce/复现步骤

尝试在一个有问题的转发聊天记录点击头像查看详细信息

### Expected behaviour/预期行为

显示信息 或 提示缺少xxx信息

### Actual behaviour/实际行为

弹出错误日志弹窗

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

V 8.9.70.11635

### Module Version/模块版本

1.4.1.r1622.74df690

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

java.lang.IllegalStateException: troopUin must be positive or null, got 0
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.createAndShowDialogCommon(SourceFile:231)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.access$createAndShowDialogCommon(Unknown Source:0)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$2.invoke$lambda$5(SourceFile:86)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$2.$r8$lambda$EKokVUL6cXBPOWmCzkFYbj-uClk(Unknown Source:0)
	at cc.ioctl.hook.msg.PttForwardHook$$ExternalSyntheticLambda1.onClick(Unknown Source:34)
	at android.view.View.performClick(View.java:7559)
	at android.view.View.performClickInternal(View.java:7536)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29660)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by CodePwn2021** [comment]
相关聊天记录的卡片代码：
```json
{"app":"com.tencent.multimsg","config":{"autosize":1,"forward":1,"round":1,"type":"normal","width":300},"desc":"[聊天记录]","extra":"{\"filename\":\"2ab60190-7321-4ad6-98bc-1d53a8b94896\",\"tsum\":100}\n","meta":{"detail":{"news":[{"text":": 跟你们讲讲我高中与女同桌一个事"},{"text":": 什么"},{"text":": 我高中同桌是个漂亮女的"},{"text":": 高一"}],"resid":"7d77nuM8SVPvS3OFZEkk529EtfpXSKqHf5sdTWjBcPSCbM7W/72JMLaZTFAIA2Rz","source":"群聊的聊天记录","summary":"查看100条转发消息","uniseq":"2ab60190-7321-4ad6-98bc-1d53a8b94896"}},"prompt":"[聊天记录]","ver":"0.0.0.5","view":"contact"}
```

**Comment by CodePwn2021** [comment]
发完issue之后发现自己的版本并非最新，更新后发现已无此问题，抱歉。
