### ISSUE TITLE
[Bug] 转发消息点头像查看详细信息 功能报错

### ISSUE THREAD

**Issue by Jingyu-Yan** [cinit/QAuxiliary#513]
### Steps to reproduce/复现步骤

打开功能 转发消息点头像查看详细信息
在合并消息中点击头像会报错

### Expected behaviour/预期行为

之前安装 QA版本这个功能是正常的，可以弹出QQ号群号，但是忘了之前用的哪个版本

### Actual behaviour/实际行为

弹出报错

### XPosed Framework you used/你使用的XP框架

面具+梦境

### QQ(TIM)版本/QQ(TIM) Version

8.4.5(1468)

### Module Version/模块版本

1.4.1.r1395.eccb8bb(1395)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

java.lang.IllegalStateException: troopUin must be positive or null, got 0
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.createAndShowDialogCommon(MultiForwardAvatarHook.kt:233)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook.access$createAndShowDialogCommon(MultiForwardAvatarHook.kt:1)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$1.invoke(MultiForwardAvatarHook.kt:16)
	at cc.ioctl.hook.msg.MultiForwardAvatarHook$initOnce$1.invoke(MultiForwardAvatarHook.kt:1)
	at cc.ioctl.util.HookUtilsKt$hookBeforeIfEnabled$1.beforeHookedMethod(HookUtils.kt:15)
	at de.robv.android.xposed.XposedBridge$Handler.beforeCall(XposedBridge.java:278)
	at top.canyie.pine.Pine.handleCall(Pine.java:498)
	at top.canyie.pine.entry.Arm32Entry.handleBridge(Arm32Entry.java:207)
	at top.canyie.pine.entry.Arm32Entry.voidBridge(Arm32Entry.java:27)
	at android.view.View.performClick(View.java:6266)
	at android.view.View$PerformClick.run(View.java:24730)
	at android.os.Handler.handleCallback(Handler.java:793)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by klxiaoniu** [comment]
腾讯和谐了，更新到CI版还可查看QQ号，但不可查看群号

**Comment by Jingyu-Yan** [comment]
> 腾讯和谐了，更新到CI版图纸查看QQ号，但不可查看群号

最近我把QQ升级了最新模块最新，可以看见QQ号了没有群号，不过我最近升级前的QQ版本配合之前1.3.7版本是可以看见群号的，所以是不是新版QQ收到转发消息实际是有群号信息的，经过处理把群号信息抹去了

**Comment by cinit** [comment]
@Jingyu-Yan 截止到 2023-09-06，现在TX服务器已经群号和QQ号两个一起替换成占位用QQ/群号了，此功能不再继续维护。
