### ISSUE TITLE
[Bug] 去除扫码登录检验发生错误

### ISSUE THREAD

**Issue by anxiaoxuan-hh** [cinit/QAuxiliary#526]
### Steps to reproduce/复现步骤

打开去除相册扫码登录检验可以直接从相册里选择截图进行扫码，可以规避一些二维码扫码强制要求使用摄像头的提示

### Expected behaviour/预期行为

正常开启后应该不会有请使用手机摄像头扫码提示

### Actual behaviour/实际行为

功能失效 相册选取二维码提示使用手机摄像头扫一扫

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.70.11625(4288)

### Module Version/模块版本

1.4.2.r1659.fd171b1(1659)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1659.fd171b1
QQ8.9.70(4288)
PID: 20917, UID: 11565
me.ketal.hook.RemoveQRLoginAuth
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException
	at me.ketal.hook.RemoveQRLoginAuth$initOnce$1.invoke(SourceFile:11)
	at me.ketal.hook.RemoveQRLoginAuth$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at me.ketal.hook.RemoveQRLoginAuth.initOnce(SourceFile:6)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:122)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:112)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.g3.a.a.z(P:6)
	at com.tencent.mobileqq.g3.a.a.y(P:2)
	at com.tencent.mobileqq.g3.a.a.p(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2409)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2377)
	at android.app.ActivityThread.installProvider(ActivityThread.java:9050)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8552)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8216)
	at android.app.ActivityThread.access$2700(ActivityThread.java:299)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2739)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by klxiaoniu** [comment]
请使用正式版 QQ 8.9.70.11730(4330)
