### ISSUE TITLE
[Bug]: 无法使用“翻译文本消息”

### ISSUE THREAD

**Issue by 2096779623** [cinit/QAuxiliary#528]
### Steps to reproduce/复现步骤

1. 辅助功能 > 聊天和消息 > 消息 中打开翻译文本消息功能
2. 随便找一个英文的文本消息长按翻译

### Expected behaviour/预期行为

翻译正常

### Actual behaviour/实际行为

没有任何反应

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.8.68(2538)

### Module Version/模块版本

1.4.2.r1659.fd171b1

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
1.4.2.r1659.fd171b1
QQ8.8.68(2538)
PID: 14488, UID: 10477
me.qcuncle.hook.TranslateTextMsg
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at me.qcuncle.hook.TranslateTextMsg$menuItemClickCallback$1.invoke(SourceFile:11)
	at me.qcuncle.hook.TranslateTextMsg$menuItemClickCallback$1.invoke(SourceFile:1)
	at cc.ioctl.util.HookUtilsKt$afterHookIfEnabled$1.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.a(Unknown Source:21)
	at com.tencent.mobileqq.activity.aio.ChatAdapter1$BubbleOnlongClickListener.onClick(P:951)
	at com.tencent.mobileqq.utils.dialogutils.QQCustomMenuNoIconLayout$3.onClick(P:426)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by klxiaoniu** [comment]
你的 QQ 版本太老了，或许你可以试试自己修复呢

**Comment by myxuebi** [comment]
> 你的 QQ 版本太老了，或许你可以试试自己修复呢

这边用的8.9.58.11175也有同样的错误，必须是最新版才能用吗

**Comment by GGG233** [comment]
> > 你的 QQ 版本太老了，或许你可以试试自己修复呢
> 
> 这边用的8.9.58.11175也有同样的错误，必须是最新版才能用吗
> 

我70也没有
