### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yangyiyu08** [cinit/QAuxiliary#54]
### Steps to reproduce/复现步骤

1.打开 净化设置--资料卡--隐藏资料卡气泡
2.侧滑栏无法打开

### Expected behaviour/预期行为

侧滑栏可以正常打开，并且资料卡的气泡会被隐藏

### Actual behaviour/实际行为

侧滑栏无法打开，报了空指针

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ8.6.0(1672)

### Module Version/模块版本

1.2.2.r424.9cb9456

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
1.2.2.r424.9cb9456
QQ8.6.0(1672)
me.kyuubiran.hook.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.widget.LinearLayout
	at me.kyuubiran.hook.SimplifyQQSettingMe$initOnce$1$1.afterHookedMethod(SimplifyQQSettingMe.kt:143)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.constructor(Unknown Source:17)
	at com.tencent.mobileqq.activity.home.Conversation.t(P:3715)
	at com.tencent.mobileqq.activity.home.Conversation.T(P:3823)
	at com.tencent.mobileqq.activity.home.Conversation.d(P:449)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.b(P:1001)
	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:844)
	at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
	at mqq.os.MqqHandler.dispatchMessage(P:99)
	at mqq.os.MqqMessageQueue.dequeue(P:294)
	at mqq.os.MqqMessageQueue.queueIdle(P:251)
	at android.os.MessageQueue.next(MessageQueue.java:395)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)


```

**Comment by rewrite-ux** [comment]
我的是qq8.8.85版本，模块版本是最新的ci r437，也是出现了这个问题

**Comment by keta1** [comment]
fixed in r456
