### ISSUE TITLE
[Bug] 隐藏会员红名功能异常

### ISSUE THREAD

**Issue by xiaohuang2004** [cinit/QAuxiliary#560]
### Steps to reproduce/复现步骤

打开“隐藏会员红名”功能

### Expected behaviour/预期行为

会员不显示红名

### Actual behaviour/实际行为

会员仍然显示红名

### XPosed Framework you used/你使用的XP框架

太极 10.3.2

### QQ(TIM)版本/QQ(TIM) Version

8.9.73(4416)

### Module Version/模块版本

1.4.3.r1682.61b8fe6(1682)

### Version and Other Requirements/版本和其他要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [x] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1682.61b8fe6
QQ8.9.73(4416)
PID: 29364, UID: 10378
xyz.nextalone.hook.DisabledRedNick
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: DexTarget: NFriendChatPie_updateUITitle
	at io.github.qauxv.util.dexkit.DexKit.requireMethodFromCache(SourceFile:20)
	at xyz.nextalone.hook.DisabledRedNick.initOnce(SourceFile:14)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:122)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:115)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.startup.task.u.blockUntilFinish(Unknown Source:0)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.h3.a.a.z(P:6)
	at com.tencent.mobileqq.h3.a.a.y(P:2)
	at com.tencent.mobileqq.h3.a.a.p(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2530)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2500)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8053)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7538)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7269)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2350)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8486)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:996)

**Comment by klxiaoniu** [comment]
diplicate #503
