### ISSUE TITLE
MessagingStyle通知异常

### ISSUE THREAD

**Issue by xunyyds** [cinit/QAuxiliary#575]
### Steps to reproduce/复现步骤

无

### Expected behaviour/预期行为

不知道怎么说

### Actual behaviour/实际行为

好像没有通知了

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.5.8

### Module Version/模块版本

6911

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1685.7f9b633
QQ8.9.58(4106)
PID: 16966, UID: 10520
moe.zapic.hook.MessagingStyleNotification
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.IllegalArgumentException: Bad value in PersistableBundle key=PushMsgreportData value=MsgPushInfo(groupId=947821636, guildId=305008947099533380, channelId=214605414, pushType=2, pushPlace=1)
	at android.os.PersistableBundle.<init>(PersistableBundle.java:148)
	at android.os.PersistableBundle.<init>(PersistableBundle.java:121)
	at android.os.PersistableBundle.<init>(PersistableBundle.java:145)
	at android.os.PersistableBundle.<init>(PersistableBundle.java:121)
	at android.content.pm.ShortcutInfo.fixUpIntentExtras(ShortcutInfo.java:526)
	at android.content.pm.ShortcutInfo.<init>(ShortcutInfo.java:494)
	at android.content.pm.ShortcutInfo.<init>(Unknown Source:0)
	at android.content.pm.ShortcutInfo$Builder.build(ShortcutInfo.java:1495)
	at androidx.core.content.pm.ShortcutInfoCompat$$ExternalSyntheticApiModelOutline0.m(SourceFile:5)
	at androidx.core.content.pm.ShortcutInfoCompat.toShortcutInfo(SourceFile:222)
	at androidx.core.content.pm.PackageInfoCompat.pushDynamicShortcut(SourceFile:95)
	at me.singleneuron.util.NonNTMessageStyleNotification$hook$1.invoke(SourceFile:86)
	at me.singleneuron.util.NonNTMessageStyleNotification$hook$1.invoke(SourceFile:1)
	at cc.ioctl.util.HookUtilsKt$hookAfterIfEnabled$1.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:494)
	at LSPHooker_.g(Unknown Source:23)
	at com.tencent.mobileqq.service.d.w(Unknown Source:147)
	at com.tencent.mobileqq.service.d.k(Unknown Source:44)
	at com.tencent.mobileqq.app.be.e(Unknown Source:254)
	at com.tencent.mobileqq.app.be.f(Unknown Source:40)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:479)
	at LSPHooker_.f(Unknown Source:21)
	at com.tencent.mobileqq.app.QQAppInterface.showMessageNotificationWithPreview(Unknown Source:26)
	at com.tencent.mobileqq.app.QQAppInterface.notifyMessageReceived(Unknown Source:112)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:479)
	at LSPHooker_.notifyMessageReceived(Unknown Source:25)
	at com.tencent.mobileqq.app.QQAppInterface.handleReceivedMessage(Unknown Source:153)
	at com.tencent.mobileqq.guild.api.impl.GuildTempApiImpl.handleReceivedMessage(Unknown Source:51)
	at com.tencent.mobileqq.guild.message.notify.GuildNotifyMsgRecvCB$onGroupGuildUpdate$1.run(P:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by letianpai-lpt** [comment]
插眼，确实好像没了。我记得以前能直接在通知里回复，最近刷机装回来没了

**Comment by klxiaoniu** [comment]
有没有必现的途径？

**Comment by Hakuin123** [comment]
@klxiaoniu 我这边甚至所有消息都没有消息提示音（必现）

有的时候消息不显示也会遇到，还会出现同样一条消息的内容重复显示多次（实际对应的是不同的消息内容）
