### ISSUE TITLE
[Bug] (功能仅支持 QQNT) Tim 3.5.1 转发强制多选报错

### ISSUE THREAD

**Issue by HiSuzume** [cinit/QAuxiliary#586]
### Steps to reproduce/复现步骤

1. 启用此功能
2. 分享文件
3. 没效果

### Expected behaviour/预期行为

**注意：并不是[#438](https://github.com/cinit/QAuxiliary/issues/438)所请求的功能**

允许多选群/好友分享

### Actual behaviour/实际行为

和没开一样，无法多选，没有变化

![Screenshot_20230821_105029_edit_11416034160757](https://github.com/cinit/QAuxiliary/assets/132192681/1516cc75-fe65-47af-894b-2f46f45be97e)

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1 便携模式

### QQ(TIM)版本/QQ(TIM) Version

Tim 3.5.1

### Module Version/模块版本

1.4.3.r1689.4a56901

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1689.4a56901
TIM3.5.1(1298)
PID: 7920, UID: 10292
cc.microblock.hook.ForceEnableMultiForward
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: No method com.tencent.mobileqq.activity.ForwardRecentActivity.initEntryHeaderView[] with return type void found
	at cc.ioctl.util.Reflex.findMethod(SourceFile:18)
	at cc.microblock.hook.ForceEnableMultiForward.initOnce(SourceFile:14)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(SourceFile:107)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(SourceFile:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(SourceFile:1)
	at cc.hicore.Utils.HttpUtils$$ExternalSyntheticLambda4.run(SourceFile:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by MicroCBer** [comment]
我是给AndroidNT版写的，这么老的版本用不了……也算正常

**Comment by MicroCBer** [comment]
加上版本要求了

**Comment by HiSuzume** [comment]
> 加上版本要求了

OMG 这是目前的Tim Lastest Ver耶 (

没关系,后面会有好心人适配的
