### ISSUE TITLE
[Bug] 发送消息自动 pangu.kt 功能异常

### ISSUE THREAD

**Issue by ColdLemonTea** [cinit/QAuxiliary#587]
### Steps to reproduce/复现步骤

1.使用QQ 8.8.98
2.在模块中打开 发送消息自动 pangu.kt 功能

### Expected behaviour/预期行为

此功能应正常将中文和英文之间加上空格

### Actual behaviour/实际行为

一打开就报错

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.8.98

### Module Version/模块版本

1.4.3.r1691.9ccb840 (1691)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1691.9ccb840
QQ8.8.98(3002)
PID: 11392, UID: 10231
cc.microblock.hook.SendPangu
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: DexTarget: AIOTextElementCtor
	at io.github.qauxv.util.dexkit.DexKit.requireMethodFromCache(SourceFile:20)
	at cc.microblock.hook.SendPangu.initOnce(SourceFile:3)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:122)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:115)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at FaUnz.GKGlC.mL.oJFGJjW.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.k(P:4)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:11)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.biz.pubaccount.readinjoy.ReadInJoyDataProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7815)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7326)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7062)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by MicroCBer** [comment]
此功能暂时不支持非 NT 版本，已添加限制

我也没装非 NT 的 QQ，有兴趣可以自己 pr 一下（

**Comment by klxiaoniu** [comment]
建议升级NTQQ使用，老版本迟早被抛弃支持的
