### ISSUE TITLE
[Bug] 不支持 32 位设备

### ISSUE THREAD

**Issue by fengyec2** [cinit/QAuxiliary#618]
### Steps to reproduce/复现步骤

1. 下载安装 1.4.3 的 armabi-v7 的 QA
2. 打开
3. 停止运行

### Expected behaviour/预期行为

正常打开

### Actual behaviour/实际行为

停止运行，报错
`----part 2 start----
[ 2023-09-10T00:53:59.054    10157: 26895: 26895 I/LSPosed-Bridge  ] Loading legacy module io.github.qauxv from /data/app/io.github.qauxv-KzCHNFOYLTBcdMWZXPBRWg==/base.apk
[ 2023-09-10T00:54:00.450    10157: 26895: 26895 I/LSPosed-Bridge  ]   Loading class io.github.qauxv.startup.HookEntry
[ 2023-09-10T00:54:00.919    10157: 26895: 26895 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.qauxv/io.github.qauxv.activity.ConfigV2Activity}: java.lang.IllegalArgumentException: unsupported arch: armv7l
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2887)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2965)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6616)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.IllegalArgumentException: unsupported arch: armv7l
	at io.github.qauxv.util.hookstatus.AbiUtils.archStringToLibDirName(SourceFile:208)
	at io.github.qauxv.fragment.CheckAbiVariantModel.collectAbiInfo(SourceFile:25)
	at io.github.qauxv.activity.ConfigV2Activity.updateActivationStatus(SourceFile:18)
	at io.github.qauxv.activity.ConfigV2Activity.onCreate(SourceFile:144)
	at android.app.Activity.performCreate(Activity.java:7109)
	at android.app.Activity.performCreate(Activity.java:7100)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2840)
	... 9 more
`

### XPosed Framework you used/你使用的XP框架

LSPosed 1.9.1 (6990) Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.5.5

### Module Version/模块版本

1.4.3

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[LSPosed_2023-09-10T01_11_27.202.zip](https://github.com/cinit/QAuxiliary/files/12566328/LSPosed_2023-09-10T01_11_27.202.zip)

**Comment by cinit** [comment]
eb024f0bdcdba50aa805c2a63436be845e225e3b
