### ISSUE TITLE
[Bug] 重命名base bug

### ISSUE THREAD

**Issue by luckyzyx** [cinit/QAuxiliary#62]
### Steps to reproduce/复现步骤

打开群文件上传本机应用  
聊天页面上传文件

### Expected behaviour/预期行为

上传应用重命名正常

### Actual behaviour/实际行为

群里上传应用，上传完毕显示base.apk，(聊天页面base后变成重命名，群文件内上传显示base，退出重进群文件显示正常)，点开文件后显示base.apk

### XPosed Framework you used/你使用的XP框架

lsposed v1.8.2(6519)

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.8.88.7830(2770) 不止此版本有问题

### Module Version/模块版本

1.2.2.r471.27c88ec

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

``` 
1.2.2.r471.27c88ec
QQ8.8.88(2770)
com.rymmmmm.hook.BaseApk
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference
	at com.rymmmmm.hook.BaseApk$1.afterHookedMethod(BaseApk.java:105)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.getFileName(Unknown Source:8)
	at com.tencent.mobileqq.filemanager.util.QQFileManagerUtilImpl.n(P:2562)
	at com.tencent.mobileqq.filemanager.api.impl.FileManagerUtilImpl.getFileName(P:700)
	at com.tencent.mobileqq.filemanager.util.QQFileManagerUtil.n(P:519)
	at com.tencent.mobileqq.filemanager.util.FileManagerUtil.a(P:122)
	at com.tencent.mobileqq.guild.temp.api.impl.GuildFileTempApiImpl.handleGuildFileMsg(P:83)
	at com.tencent.mobileqq.service.message.MessagePBElemDecoder.a(P:2084)
	at com.tencent.mobileqq.service.message.MessagePBElemDecoder.a(P:2041)
	at com.tencent.imcore.message.ext.codec.decoder.pbelement.TransferElemElemDecoder.a(P:26)
	at com.tencent.mobileqq.service.message.QMessageProtoCodec.a(P:312)
	at com.tencent.mobileqq.service.message.QMessageProtoCodec.a(P:232)
	at com.tencent.mobileqq.guild.message.base.BaseGuildMessageProcessor.a(P:226)
	at com.tencent.mobileqq.guild.message.GuildOfflineMessageProcessor.a(P:105)
	at com.tencent.mobileqq.guild.message.GuildOfflineMessageProcessor.a(P:57)
	at com.tencent.mobileqq.guild.message.registerproxy.GuildChannelMsgProcesser$MsgTask.a(P:68)
	at com.tencent.mobileqq.guild.message.registerproxy.GuildChannelMsgProcesser$MsgTask.run(P:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by keta1** [comment]
经测试，使用 最新版模块在此版本 QQ 上无此问题

**Comment by bangzui15515** [comment]
无root用lsp安装一直显示安装包名重复是为什么
