### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ark-Two** [cinit/QAuxiliary#624]
### Steps to reproduce/复现步骤

打开了辅助-清理最近聊天

### Expected behaviour/预期行为

可以清理所有消息

### Actual behaviour/实际行为

如图
![QQ图片20230921065559](https://github.com/cinit/QAuxiliary/assets/72326210/8d0de27d-56f1-43f2-9b22-c43f419a6ffa)

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

8.9.68(4264)

### Module Version/模块版本

v1.4.4.r1735.d9f7335（1735）

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.4.r1735.d9f7335
QQ8.9.68(4264)
PID: 16570, UID: 10403
xyz.nextalone.hook.CleanRecentChat
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<*>
	at xyz.nextalone.hook.CleanRecentChat.handler(SourceFile:17)
	at xyz.nextalone.hook.CleanRecentChat.access$handler(SourceFile:1)
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1$1$1$1$2.invoke(SourceFile:8)
	at xyz.nextalone.hook.CleanRecentChat$initOnce$1$1$1$1$2.invoke(SourceFile:1)
	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(SourceFile:84)
	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(SourceFile:12)
	at android.view.View.performClick(View.java:7564)
	at android.view.View.performClickInternal(View.java:7540)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29705)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8380)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by klxiaoniu** [comment]
duplicate
