### ISSUE TITLE
[功能请求] 对QQ轻聊版小程序转链接打开/一些功能的修复

### ISSUE THREAD

**Issue by Merlyx** [cinit/QAuxiliary#65]
### QQ(TIM)版本/QQ(TIM) Version

QQ轻聊版4.0.4.1666

### 为什么你认为需要此功能

最近QQ主要版本的运存/存储占用水涨船高，迫于无奈选用了QQ轻聊版，惊喜之余发现有QA对轻聊版的适配，但是似乎不是很完美，特来寻求帮助，感谢！！

### 具体功能需要/Specific features require

QQ轻聊版一些功能的修复

**Comment by keta1** [comment]
@Merlyx 目前没有开发者有时间来适配 QQ Lite 
你可以自己来做

**Comment by cinit** [comment]
@Merlyx 建议按你需求的优先级(高/中/低) 把你需要使用且无法使用的功能排序，我们没有时间和精力去修复适配所有的功能。

**Comment by Merlyx** [comment]
> @Merlyx 建议按你需求的优先级(高/中/低) 把你需要使用且无法使用的功能排序，我们没有时间和精力去修复适配所有的功能。

试着看了一下，
轻聊版比较简洁，净化类功能可能用不到。

排序了一下需求和相应日志（其实前两个比较刚需
小程序转链接打开
`1.2.3.r483.4d61b18
QQ极速版4.0.4(9999)
me.singleneuron.hook.decorator.MiniAppToStruckMsg
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at io.github.qauxv.router.dispacher.ItemBuilderFactoryHook.initOnce(ItemBuilderFactoryHook.kt:56)
	at io.github.qauxv.hook.BaseHookDispatcher.initialize(BaseHookDispatcher.kt:54)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:135)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at com.tencent.mobileqq.startup.step.Step.doStep(ProGuard:103)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at rny.a(ProGuard:518)
	at rny.handleMessage(ProGuard:544)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

`
上传文件重命名
`1.2.3.r483.4d61b18
QQ极速版4.0.4(9999)
com.rymmmmm.hook.BaseApk
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:19)
	at com.rymmmmm.hook.BaseApk.initOnce(BaseApk.java:95)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:60)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:135)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at com.tencent.mobileqq.startup.step.Step.doStep(ProGuard:103)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at rny.a(ProGuard:518)
	at rny.handleMessage(ProGuard:544)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

`
批量清理消息
无log
转发消息查看详细
`1.2.3.r483.4d61b18
QQ极速版4.0.4(9999)
cc.ioctl.hook.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Method java.lang.Class.getMethod(java.lang.String, java.lang.Class[])' on a null object reference
	at cc.ioctl.hook.MultiForwardAvatarHook.initOnce(MultiForwardAvatarHook.java:223)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:60)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:135)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at com.tencent.mobileqq.startup.step.Step.doStep(ProGuard:103)
	at com.tencent.mobileqq.startup.step.Step.step(ProGuard:84)
	at rny.a(ProGuard:518)
	at rny.handleMessage(ProGuard:544)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

`
图片分享至其他应用
无log

然后算新功能请求的话：希望模块能强制轻聊版使用夜间主题？

测试了下，防撤回，链接浏览器打开这些都能正常使用，感谢工作！
