### ISSUE TITLE
[Bug] 8.9.85.12820(4766)所有功能失效

### ISSUE THREAD

**Issue by aixiaoke5** [cinit/QAuxiliary#650]
### Steps to reproduce/复现步骤

升级后出现所有功能不可用，功能异常列表仅有一条隐藏亲密抽屉出现异常。

### Expected behaviour/预期行为

rt

### Actual behaviour/实际行为

rt

### XPosed Framework you used/你使用的XP框架

LSP1.9.2.7029

### QQ(TIM)版本/QQ(TIM) Version

8.9.85.12820(4766)

### Module Version/模块版本

1.4.5.r1770.efcf464(1770)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.5.r1770.efcf464
QQ8.9.85(4766)
PID: 1799, UID: 10246
xyz.nextalone.hook.RemoveIntimateDrawer
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: DexTarget: CIntimateDrawer
	at io.github.qauxv.util.dexkit.DexKit.requireClassFromCache(SourceFile:20)
	at xyz.nextalone.hook.RemoveIntimateDrawer$initOnce$1.invoke(SourceFile:2)
	at xyz.nextalone.hook.RemoveIntimateDrawer$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at xyz.nextalone.hook.RemoveIntimateDrawer.initOnce(SourceFile:6)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(SourceFile:491)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:192)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:115)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:50)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.i3.a.a.z(P:6)
	at com.tencent.mobileqq.i3.a.a.y(P:2)
	at com.tencent.mobileqq.i3.a.a.p(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(Unknown Source:102)
	at android.content.ContentProvider.attachInfo(Unknown Source:1)
	at android.app.ActivityThread.installProvider(Unknown Source:353)
	at android.app.ActivityThread.installContentProviders(Unknown Source:68)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:935)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:878)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:81)
	at android.app.ActivityThread.main(Unknown Source:132)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:332)

**Comment by DoyoDia** [comment]
同QQ版本但是只有“以图片形式打开闪照”更新后异常
