### ISSUE TITLE
[Bug] 聊天小尾巴功能异常

### ISSUE THREAD

**Issue by Ivanlon30000** [cinit/QAuxiliary#66]
### Steps to reproduce/复现步骤

1. 打开聊天小尾巴功能
2. 发送消息

### Expected behaviour/预期行为

聊天消息有小尾巴

### Actual behaviour/实际行为

未见小尾巴

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.2(6519) Zygisk

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.4.6.3078/QQ 8.8.88

### Module Version/模块版本

1.2.3.r516.2904412

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
1.2.3.r516.2904412
TIM3.4.6(1218)
cc.ioctl.hook.ChatTailHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: No field curFriendUin in class Lcom/tencent/mobileqq/activity/aio/SessionInfo; (declaration of 'com.tencent.mobileqq.activity.aio.SessionInfo' appears in base.apk!classes8.dex)
	at java.lang.Class.getDeclaredField(Native Method)
	at cc.ioctl.hook.ChatTailHook.lambda$initOnce$1(ChatTailHook.java:208)
	at cc.ioctl.hook.ChatTailHook.$r8$lambda$D9umpBsIzR8FCkcHpCk5wCjMHU8(Unknown Source:0)
	at cc.ioctl.hook.ChatTailHook$$ExternalSyntheticLambda0.beforeHookedMethod(Unknown Source:2)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(HookUtils.java:166)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:82)
	at LSPHooker_.a(Unknown Source:23)
	at com.tencent.mobileqq.activity.BaseChatPie.a(SourceFile:12566)
	at com.tencent.mobileqq.activity.BaseChatPie.b(SourceFile:12428)
	at com.tencent.mobileqq.activity.BaseChatPie.bHN(SourceFile:12265)
	at com.tencent.mobileqq.activity.BaseChatPie.send(SourceFile:12198)
	at xwz.send(SourceFile:1428)
	at com.tencent.mobileqq.activity.BaseChatPie.bsb(SourceFile:3948)
	at com.tencent.mobileqq.activity.BaseChatPie.onClick(SourceFile:3917)
	at xwz.onClick(SourceFile:2507)
	at android.view.View.performClick(View.java:7677)
	at android.view.View.performClickInternal(View.java:7654)
	at android.view.View.access$3600(View.java:851)
	at android.view.View$PerformClick.run(View.java:28925)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

```
1.2.3.r516.2904412
QQ8.8.88(2770)
cc.ioctl.hook.ChatTailHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: No field curFriendUin in class Lcom/tencent/mobileqq/activity/aio/SessionInfo; (declaration of 'com.tencent.mobileqq.activity.aio.SessionInfo' appears in base.apk!classes7.dex)
	at java.lang.Class.getDeclaredField(Native Method)
	at cc.ioctl.hook.ChatTailHook.lambda$initOnce$1(ChatTailHook.java:208)
	at cc.ioctl.hook.ChatTailHook.$r8$lambda$D9umpBsIzR8FCkcHpCk5wCjMHU8(Unknown Source:0)
	at cc.ioctl.hook.ChatTailHook$$ExternalSyntheticLambda0.beforeHookedMethod(Unknown Source:2)
	at cc.ioctl.util.HookUtils$6.beforeHookedMethod(HookUtils.java:166)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:82)
	at LSPHooker_.a(Unknown Source:23)
	at com.tencent.mobileqq.activity.aio.rebuild.input.send.PhotoListMsgCallback.onMessageSending(P:34)
	at com.tencent.mobileqq.activity.aio.core.input.BaseMessageSender.c(P:98)
	at com.tencent.mobileqq.activity.aio.core.input.BaseMessageSender.b(P:72)
	at com.tencent.mobileqq.activity.aio.core.input.FriendMessageSender.b(P:12)
	at com.tencent.mobileqq.activity.aio.core.input.BaseMessageSender.a(P:52)
	at com.tencent.mobileqq.activity.aio.coreui.input.FunBtnUI$1.onClick(P:70)
	at android.view.View.performClick(View.java:7677)
	at android.view.View.performClickInternal(View.java:7654)
	at android.view.View.access$3600(View.java:851)
	at android.view.View$PerformClick.run(View.java:28925)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by keta1** [comment]
小尾巴 功能 不再维护
