### ISSUE TITLE
[Bug] 8.9.88移除侧滑栏左上角打卡 失效

### ISSUE THREAD

**Issue by PandaYuuHa** [cinit/QAuxiliary#688]
### Steps to reproduce/复现步骤

打开 移除侧滑栏左上角打卡 功能

### Expected behaviour/预期行为

侧滑栏不显示左上角打卡按钮

### Actual behaviour/实际行为

打卡按钮存在并报错

### XPosed Framework you used/你使用的XP框架

LSPosed 1.9.2(7024) zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.88

### Module Version/模块版本

1.4.6.r1805.c2b9e8f

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1805.c2b9e8f
QQ8.9.88(4852)
PID: 29514, UID: 12216
cc.ioctl.hook.ui.title.RemoveDailySign
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: Name: e0,Static: false, Type: android.widget.LinearLayout
	at com.github.kyuubiran.ezxhelper.utils.Args.field(SourceFile:181)
	at com.github.kyuubiran.ezxhelper.utils.Args.getObjectAs(SourceFile:22)
	at cc.ioctl.hook.ui.title.RemoveDailySign.initOnce$lambda$0(SourceFile:111)
	at cc.ioctl.hook.ui.title.RemoveDailySign.$r8$lambda$r9IghiMB2kqbU27W2GMJk_fJIIQ(SourceFile:1)
	at io.github.qauxv.util.Natives$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at G.NqGWx.gjBw.GWplq.pTk.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.activity.QQSettingMe.g0(P:6)
	at com.tencent.mobileqq.activity.QQSettingMe.k0(P:2)
	at com.tencent.mobileqq.activity.QQSettingMe.<init>(P:6)
	at com.tencent.mobileqq.activity.home.Conversation.i0(P:11)
	at com.tencent.mobileqq.activity.home.Conversation.r0(P:5)
	at com.tencent.mobileqq.activity.home.Conversation.E(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$o.c(P:13)
	at com.tencent.mobileqq.activity.home.Conversation$o.handleMessage(P:2)
	at com.tencent.mobileqq.utils.ak.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.queueIdle(P:2)
	at android.os.MessageQueue.next(MessageQueue.java:406)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by PandaYuuHa** [comment]
测试了一下，1.4.6.r1801及之前版本还是好的

**Comment by lliioollcn** [comment]
已修复

**Comment by PandaYuuHa** [comment]
> 已修复


[RemoveDailySign-1701339273932.txt](https://github.com/cinit/QAuxiliary/files/13511454/RemoveDailySign-1701339273932.txt)
[SimplifyQQSettingMe-1701339283425.txt](https://github.com/cinit/QAuxiliary/files/13511457/SimplifyQQSettingMe-1701339283425.txt)

问题依旧存在，并且整个侧滑栏精简全部失效了
