### ISSUE TITLE
[Bug] 1.4.6正式版在旧版QQ上，强制使用默认字体功能失效。

### ISSUE THREAD

**Issue by vqsld** [cinit/QAuxiliary#759]
### Steps to reproduce/复现步骤

1.将QA更新至1.4.6。
2.功能失效。

### Expected behaviour/预期行为

能用。

### Actual behaviour/实际行为

![Screenshot_20240110_213637](https://github.com/cinit/QAuxiliary/assets/70460086/fbea20c0-f294-43c5-b5cf-6de0cc79b23d)
功能失效，卸载并降级QA到1.4.4或更低版本，重置模块设置，再导入之前备份的模块设置，或手动打开“强制使用默认字体”功能，模块生效。

### XPosed Framework you used/你使用的XP框架

LSPatch和太极

### QQ(TIM)版本/QQ(TIM) Version

8.7.8

### Module Version/模块版本

1.4.6.r1786.189196f(1786)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1786.189196f
QQ8.7.8(1758)
PID: 15969, UID: 10261
cc.ioctl.hook.chat.DefaultFont
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: 
dumpStatus failed: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:2064)
	at io.github.qauxv.util.dexkit.DexMethodDescriptor.<init>(SourceFile:15)
	at io.github.qauxv.util.dexkit.DexKit.getMethodDescFromCacheImpl(SourceFile:23)
	at cc.ioctl.hook.chat.DefaultFont.isNeedFind(SourceFile:3)
	at io.github.qauxv.hook.BaseFunctionHook.isPreparationRequired(SourceFile:9)
	at io.github.qauxv.fragment.FuncStatusDetailsFragment.dumpStatus(SourceFile:162)
	at io.github.qauxv.fragment.FuncStatusDetailsFragment.doOnCreateView(SourceFile:20)
	at io.github.qauxv.fragment.BaseSettingFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:147)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:106)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:586)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:85)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:76)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:12)
	at android.os.Handler.handleCallback(Handler.java:955)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:9105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129)

**Comment by klxiaoniu** [comment]
清除适配数据试下

**Comment by vqsld** [comment]
> 清除适配数据试下

当时就是在QA里“重置模块设置”后再设置“强制使用默认字体”的呀！不重置模块设置，直接卸载1.4.6，重装1.4.4，还是“异常”。
不过现在也试不了了，号被风控到8.9.58了。😂

**Comment by klxiaoniu** [comment]
fixed
