### ISSUE TITLE
升到release里的最新版后，移除侧滑栏打卡功能失效

### ISSUE THREAD

**Issue by Chenyu550** [cinit/QAuxiliary#782]
### Steps to reproduce/复现步骤

1. 打开这个功能
2. 滑出侧滑栏
3. 看左上角

### Expected behaviour/预期行为

没有打卡按钮

### Actual behaviour/实际行为

![Screenshot_2024-02-01-23-09-17-308_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/114039435/671a8fad-16f6-4a70-b956-4ae21b093792)

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.9.70

### Module Version/模块版本

在日志里

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.4.7.r1883.b3d4b79
QQ8.9.70(4330)
PID: 4070, UID: 10239
cc.ioctl.hook.ui.title.RemoveDailySign
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: Name: e0,Static: false, Type: android.widget.LinearLayout
	at kotlin.ResultKt.field(SourceFile:171)
	at kotlin.ResultKt.getObjectAs(SourceFile:22)
	at cc.ioctl.hook.ui.title.RemoveDailySign.initOnce$lambda$0(SourceFile:131)
	at cc.ioctl.hook.ui.title.RemoveDailySign.$r8$lambda$r9IghiMB2kqbU27W2GMJk_fJIIQ(SourceFile:1)
	at cc.ioctl.hook.msg.FlashPicHook$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.activity.QQSettingMe.g0(P:6)
	at com.tencent.mobileqq.activity.QQSettingMe.j0(P:2)
	at com.tencent.mobileqq.activity.QQSettingMe.<init>(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.d0(P:11)
	at com.tencent.mobileqq.activity.home.Conversation.m0(P:4)
	at com.tencent.mobileqq.activity.home.Conversation.z(P:1)
	at com.tencent.mobileqq.activity.home.Conversation$o.c(P:13)
	at com.tencent.mobileqq.activity.home.Conversation$o.handleMessage(P:2)
	at com.tencent.mobileqq.utils.ak.handleMessage(P:2)
	at mqq.os.MqqHandler.dispatchMessage(P:7)
	at mqq.os.MqqMessageQueue.dequeue(P:15)
	at mqq.os.MqqMessageQueue.queueIdle(P:2)
	at android.os.MessageQueue.next(MessageQueue.java:406)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8307)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by EmptyDreams** [comment]
在应用转生 qq 9.0.8.14755(5540)，模块 1.4.7.r1887.afe496a(1887) 中该问题同样存在。

```
1.4.7.r1887.afe496a
QQ9.0.8(5540)
PID: 22937, UID: 10329
cc.ioctl.hook.ui.title.RemoveDailySign
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: Name: e0,Static: false, Type: android.widget.LinearLayout
	at kotlin.ResultKt.field(SourceFile:171)
	at kotlin.ResultKt.getObjectAs(SourceFile:22)
	at cc.ioctl.hook.ui.title.RemoveDailySign.initOnce$lambda$0(SourceFile:131)
	at cc.ioctl.hook.ui.title.RemoveDailySign.$r8$lambda$r9IghiMB2kqbU27W2GMJk_fJIIQ(SourceFile:1)
	at cc.ioctl.hook.msg.FlashPicHook$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at BugHooker_461cg6gg12n40vdoc8dlvhi2k2.hook(Unknown Source:56)
	at com.tencent.mobileqq.api.impl.DrawerApiImpl.getQQSettingMeView(P:4)
	at com.tencent.mobileqq.QQSettingMe.b0(P:2)
	at com.tencent.mobileqq.QQSettingMe.k0(P:2)
	at com.tencent.mobileqq.QQSettingMe.e0(P:3)
	at com.tencent.mobileqq.activity.home.Conversation$3.run(P:3)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by HdShare** [comment]
尝试最新ci版
