### ISSUE TITLE
打开"屏蔽主页面相机/小世界图标"功能报错

### ISSUE THREAD

**Issue by bocchi810** [cinit/QAuxiliary#818]
### Steps to reproduce/复现步骤

1.安装模块
2.打开功能

### Expected behaviour/预期行为

应当没有任何报错

### Actual behaviour/实际行为

提示初始化失败

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

qq 9.0.17

### Module Version/模块版本

1.4.8.r1913.6e492f7

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.8.r1913.6e492f7
QQ9.0.17(5714)
PID: 22624, UID: 10349
cc.ioctl.hook.ui.title.RemoveCameraButton
isInitialized: true
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException
	at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.findMethod(MethodUtils.kt:82)
	at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.findMethod$default(MethodUtils.kt:77)
	at cc.ioctl.hook.ui.title.RemoveCameraButton$initOnce$1.invoke(RemoveCameraButton.kt:48)
	at cc.ioctl.hook.ui.title.RemoveCameraButton$initOnce$1.invoke(RemoveCameraButton.kt:47)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at cc.ioctl.hook.ui.title.RemoveCameraButton.initOnce(RemoveCameraButton.kt:47)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:157)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:112)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by klxiaoniu** [comment]
现在不是超级QQ秀时代了吗？用下面的屏蔽QQ秀图标试试？
