### ISSUE TITLE
[Bug] 强制使用默认字体/强制使用默认消息气泡 两项功能错误

### ISSUE THREAD

**Issue by gezimao** [cinit/QAuxiliary#830]
### Steps to reproduce/复现步骤

更新QA至release里的1.4.8.r1905.3aed1c5 
未对qq进行任何更新操作 qq版本8.9.28（3700）
进入聊天界面，发现字体和聊天气泡均为个性化字体与气泡

### Expected behaviour/预期行为

进入聊天界面，正确使用默认气泡与默认字体

### Actual behaviour/实际行为

进入聊天界面，发现字体和聊天气泡均为个性化字体与气泡

### XPosed Framework you used/你使用的XP框架

太极阴 XposedAPI version：92

### QQ(TIM)版本/QQ(TIM) Version

8.9.28.10155

### Module Version/模块版本

1.4.8.r1905.3aed1c5 

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### 默认气泡的错误日志
1.4.8.r1905.3aed1c5
QQ8.9.28(3700)
PID: 16421, UID: 10289
cc.ioctl.hook.chat.DefaultBubbleHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/qqnt/kernel/nativeinterface/VASMsgBubble;
	at cc.ioctl.hook.chat.DefaultBubbleHook.initOnce(SourceFile:8)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.startup.step.LoadDex.doStep(P:1)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.director.StartupDirector.m(P:4)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:12)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2482)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8698)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8198)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7924)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2669)
	at android.os.Handler.dispatchMessage(Handler.java:114)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:9194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qqnt.kernel.nativeinterface.VASMsgBubble" on path: DexPathList[[zip file "/data/app/~~IrbpE8P68k8jUg9GKVmnbw==/io.github.qauxv-IA8O-LLp42pS48jJkQQIIA==/base.apk"],nativeLibraryDirectories=[/data/app/~~IrbpE8P68k8jUg9GKVmnbw==/io.github.qauxv-IA8O-LLp42pS48jJkQQIIA==/base.apk!/lib/arm64-v8a, /data/app/~~ydnwzdxlkDvub-ExLwFYkQ==/io.github.qauxv-PsIIWZSxBMrMkUTToeTUOQ==/lib/arm64, /system/lib64, /product_h/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 34 more
### 默认字体的错误日志
1.4.8.r1905.3aed1c5
QQ8.9.28(3700)
PID: 16421, UID: 10289
cc.ioctl.hook.chat.DefaultFont
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/qqnt/kernel/nativeinterface/VASMsgFont;
	at cc.ioctl.hook.chat.DefaultFont.initOnce(SourceFile:8)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(SourceFile:495)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(SourceFile:24)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.startup.step.LoadData.doStep(P:1)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.run(P:1)
	at android.os.Handler.handleCallback(Handler.java:971)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qqnt.kernel.nativeinterface.VASMsgFont" on path: DexPathList[[zip file "/data/app/~~IrbpE8P68k8jUg9GKVmnbw==/io.github.qauxv-IA8O-LLp42pS48jJkQQIIA==/base.apk"],nativeLibraryDirectories=[/data/app/~~IrbpE8P68k8jUg9GKVmnbw==/io.github.qauxv-IA8O-LLp42pS48jJkQQIIA==/base.apk!/lib/arm64-v8a, /data/app/~~ydnwzdxlkDvub-ExLwFYkQ==/io.github.qauxv-PsIIWZSxBMrMkUTToeTUOQ==/lib/arm64, /system/lib64, /product_h/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 18 more

**Comment by gezimao** [comment]
![Screenshot_20240225_130432](https://github.com/cinit/QAuxiliary/assets/75022029/ea8395a8-fcd4-406a-8d23-647a439f2fc7)故障排除页面的截图，尝试清除适配数据并重启QQ，未能解决这两个错误
