### ISSUE TITLE
[Bug] 9.0.17侧滑栏精简无法使用

### ISSUE THREAD

**Issue by xiaosoar** [cinit/QAuxiliary#834]
### Steps to reproduce/复现步骤

不管是全关还是全开/开一个都无法去除侧滑栏的项目，并且没有报错
![Screenshot_20240227_201621_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/105652758/6d66badf-1f1c-43f2-994c-997d65e6b905)

### Expected behaviour/预期行为

![Screenshot_20240227_201612_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/105652758/7fd03e17-b42c-44e5-abf4-1dd31531138b)

### Actual behaviour/实际行为

要清除勾选的项目

### XPosed Framework you used/你使用的XP框架

Taichi(太极)14.0.6.11231507-10550

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15190

### Module Version/模块版本

1.4.8.r1905.3aed1c5(1905)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[SimplifyQQSettingMe-1709036682703.txt](https://github.com/cinit/QAuxiliary/files/14419358/SimplifyQQSettingMe-1709036682703.txt)

**Comment by klxiaoniu** [comment]
更新CI看看

**Comment by lvye-asia** [comment]
> 更新CI看看

怎么更新？

**Comment by lvye-asia** [comment]
> 更新CI看看

还是没有用，版本1.4.8.r1928.220314a(1928)

**Comment by lvye-asia** [comment]
同样问题

**Comment by klxiaoniu** [comment]
你排查下勾了哪个导致的

**Comment by lvye-asia** [comment]
> 你排查下勾了哪个导致的

这勾其中一个也是一样

**Comment by lvye-asia** [comment]
> 你排查下勾了哪个导致的

现在更新QQ了，出现了报错。
报错内容：1.4.8.r1928.220314a
QQ9.0.20(5844)
PID: 7823, UID: 10334
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke$lambda$4(SourceFile:315)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.$r8$lambda$mB2ZNM6HnOCSBs2WfCd94N8CqdI(SourceFile:1)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$oo0oo0oO0o0Ooo0O0oo0oo0oo0ooO000o00o00.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:334)
	at exp.and.callAfterMethodHooked(SourceFile:494)
	at exp.anb.O0oo0oO00o00oo0o0000o00o000o00o00o00oO(SourceFile:134)
	at com.tencent.mobileqq.QQSettingMeView.<init>(P:1)
	at com.tencent.mobileqq.api.impl.DrawerApiImpl.getQQSettingMeView(P:4)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.Y(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.d0(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.Z(P:3)
	at com.tencent.mobileqq.activity.home.Conversation$b.d(P:4)
	at com.tencent.mobileqq.app.FrameHelperActivity$1.d(P:10)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.y(P:15)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.M(P:3)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.N(P:1)
	at com.tencent.mobileqq.app.FrameHelperActivity$e.e(P:2)
	at com.tencent.mobileqq.app.FrameHelperActivity$e.f(Unknown Source:0)
	at com.tencent.mobileqq.app.d.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
	at android.app.ActivityThread.main(ActivityThread.java:9923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

**Comment by lvye-asia** [comment]
QQ版本：9.0.20.15515(5844)
