### ISSUE TITLE
[功能请求] 屏蔽侧滑栏能量值

### ISSUE THREAD

**Issue by yyyyq97** [cinit/QAuxiliary#838]
### QQ(TIM)版本/QQ(TIM) Version

9.17

### 为什么你认为需要此功能

屏蔽能量值

### 联系到哪些已经存在的bug或者功能

顺便提个bug
9.20可以屏蔽左上角打卡但是下方设置那一排的夜间模式天气之类的无法屏蔽
9.17侧滑栏能屏蔽下面的，但是左上角打卡无法屏蔽

### 具体功能需要/Specific features require

屏蔽等级旁边的能量值[
![IMG_20240301_091752](https://github.com/cinit/QAuxiliary/assets/54359754/aa76adac-1a43-495c-8c0b-a79b44f34396)
](url)

**Comment by yyyyq97** [comment]
9.17无法屏蔽打卡的
1.4.8.r1930.e8cc3f7
QQ9.0.17(5712)
PID: 20472, UID: 10383
cc.ioctl.hook.ui.title.RemoveDailySign
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchFieldException: Name: e0,Static: false, Type: android.widget.LinearLayout
	at kotlin.ResultKt.field(SourceFile:171)
	at kotlin.ResultKt.getObjectAs(SourceFile:22)
	at cc.ioctl.hook.ui.title.RemoveDailySign.initOnce$lambda$0(SourceFile:144)
	at cc.ioctl.hook.ui.title.RemoveDailySign.$r8$lambda$r9IghiMB2kqbU27W2GMJk_fJIIQ(SourceFile:1)
	at cc.ioctl.hook.msg.FlashPicHook$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at XcC.aLw.yN.LeIrSvS.jrr.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.api.impl.DrawerApiImpl.getQQSettingMeView(P:4)
	at com.tencent.mobileqq.QQSettingMe.b0(P:2)
	at com.tencent.mobileqq.QQSettingMe.k0(P:2)
	at com.tencent.mobileqq.QQSettingMe.e0(P:3)
	at com.tencent.mobileqq.activity.home.Conversation$c.d(P:4)
	at com.tencent.mobileqq.app.FrameHelperActivity$1.d(P:10)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.w(P:6)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.onTouchEvent(P:18)
	at android.view.View.dispatchTouchEvent(View.java:15867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.dispatchTouchEvent(P:18)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:566)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
	at androidx.core.app.ComponentActivity.dispatchTouchEvent(Unknown Source:9)
	at androidx.activity.ComponentActivity.dispatchTouchEvent(Unknown Source:9)
	at androidx.fragment.app.FragmentActivity.dispatchTouchEvent(Unknown Source:9)
	at mqq.app.AppActivity.dispatchTouchEvent(P:3)
	at com.tencent.mobileqq.app.QBaseActivity.dispatchTouchEvent(P:5)
	at com.tencent.mobileqq.app.BaseActivity.dispatchTouchEvent(Unknown Source:9)
	at com.tencent.mobileqq.activity.SplashActivity.dispatchTouchEvent(Unknown Source:9)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:524)
	at android.view.View.dispatchPointerEvent(View.java:16145)
	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7815)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7581)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6976)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7141)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6957)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6976)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6957)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10124)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10075)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10039)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10285)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:304)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver

**Comment by klxiaoniu** [comment]
已添加
