### ISSUE TITLE
[Bug] 退群灰字提示失效

### ISSUE THREAD

**Issue by Stealthbaixiaomo** [cinit/QAuxiliary#866]
### Steps to reproduce/复现步骤

无

### Expected behaviour/预期行为

群成员退群时出现灰字提示

### Actual behaviour/实际行为

无显示

### Xposed Framework you used/你使用的Xposed框架

lsposed

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

V 9.0.20.15515

### Module Version/模块版本

1.4.9.r1949.d308dcf(1949)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1949.d308dcf
QQ9.0.20(5844)
PID: 30090, UID: 10420
cc.hicore.hook.TroopMemberLeaveGreyTip
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: OnlinePushPbPushTransMsg
	at java.util.Objects.requireNonNull(Objects.java:232)
	at cc.hicore.hook.TroopMemberLeaveGreyTip.initOnce(SourceFile:9)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.onCreate(Unknown Source:8)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2636)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2602)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8320)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7831)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7483)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by Stealthbaixiaomo** [comment]
目前来看没有，但是我的结论并没有太大参考价值，jm的lsposed不怎么好用



---原始邮件---
发件人: "Eat Hatsune ***@***.***&gt;
发送时间: 2025年1月30日(周四) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [cinit/QAuxiliary] [Bug] 退群灰字提示失效 (Issue #866)




 
问题好像还没解决吧
