### ISSUE TITLE
[Bug] QQ 9.0.0.14110 带图回复失效

### ISSUE THREAD

**Issue by March7th2048** [cinit/QAuxiliary#872]
### Steps to reproduce/复现步骤

1.打开带图回复
2.提示初始化失败
3.尝试使用该功能，但失效
![Screenshot_2024-03-21-14-22-11-128_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/140617554/452ecb32-5fde-4362-bfef-fdc03ff89eae)

### Expected behaviour/预期行为

成功触发带图回复
![Screenshot_2024-03-21-14-23-00-419_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/140617554/c761813d-f97a-4d1b-8ac0-ab8d8e52c82f)

### Actual behaviour/实际行为

未能触发带图回复，仅有图片成功发送，但文字信息未能回复
![Screenshot_2024-03-21-14-17-29-904_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/140617554/ef55bfe7-b313-4082-b513-c32b786f606d)

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2(7058)

### Your Android version/你使用的安卓系统版本

Android 14

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### Module Version/模块版本

v1.4.9.r1960.39766dc-arm64

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1960.39766dc
QQ9.0.0(5282)
PID: 32447, UID: 10363
cc.hicore.hook.ReplyMsgWithImg
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: CGuildHelperProvider.INSTANCE
	at java.util.Objects.requireNonNull(Objects.java:232)
	at cc.hicore.hook.ReplyMsgWithImg.initOnce(SourceFile:21)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(SourceFile:113)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(SourceFile:1)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$p6d4Z571M3T0oSu3Ep3L5AMN8ZU(SourceFile:1)
	at cc.hicore.Utils.HttpUtils$$ExternalSyntheticLambda3.run(SourceFile:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by cinit** [comment]
@March7th2048 已知问题，暂无精力维护
