### ISSUE TITLE
[Bug] 侧滑栏左下角不生效

### ISSUE THREAD

**Issue by Ehoumaki** [cinit/QAuxiliary#875]
### Steps to reproduce/复现步骤

1侧滑栏精简已选夜间温度等级
2左下角仍不能隐藏

### Expected behaviour/预期行为

正常隐藏

### Actual behaviour/实际行为

好几个版本不能隐藏了，最新的ci版本

### Xposed Framework you used/你使用的Xposed框架

lsp

### Your Android version/你使用的安卓系统版本

安卓10

### QQ(TIM)版本/QQ(TIM) Version

9.0.25

### Module Version/模块版本

1.4.9.r1966.e350ff9(1966)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1966.e350ff9
QQ9.0.25(5942)
PID: 20787, UID: 10298
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke$lambda$4(SourceFile:315)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.$r8$lambda$lRWYE9U1SU48C5saeShBQ-oIbFU(SourceFile:1)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at E.E.eRYn.LK.KVmhXHchjt.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.api.impl.DrawerApiImpl.getQQSettingMeView(P:4)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.Y(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.d0(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.Z(P:3)
	at com.tencent.mobileqq.activity.home.Conversation$b.d(P:4)
	at com.tencent.mobileqq.app.FrameHelperActivity$1.d(P:10)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.y(P:15)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.M(P:3)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.N(P:1)
	at com.tencent.mobileqq.app.FrameHelperActivity$e.a(P:4)
	at com.tencent.mobileqq.activity.home.view.TitleAreaHeadLayout.onClick(P:2)
	at android.view.View.performClick(View.java:7252)
	at android.view.View.performClickInternal(View.java:7229)
	at android.view.View.access$3500(View.java:821)
	at android.view.View$PerformClick.run(View.java:27765)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/pull/915
