### ISSUE TITLE
[Bug] TIM MessageStyle初始化失败

### ISSUE THREAD

**Issue by Biaogo** [cinit/QAuxiliary#89]
### Steps to reproduce/复现步骤

通知设置-MessageStyle

### Expected behaviour/预期行为

成功开启，原生系统会有对话泡按钮

### Actual behaviour/实际行为

初始化失败

### XPosed Framework you used/你使用的XP框架

Lsposed

### QQ(TIM)版本/QQ(TIM) Version

3.4.6(1218)

### Module Version/模块版本

1.2.6.r656.7fba07b

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```1.2.6.r656.7fba07b
TIM3.4.6(1218)
me.singleneuron.hook.MessageStyleNotification
isInitialized: true
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:19)
	at me.singleneuron.hook.MessageStyleNotification.initOnce(MessageStyleNotification.kt:77)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:61)
	at io.github.qauxv.core.HookInstaller.doInitAndSetupHookForeground(HookInstaller.java:125)
	at io.github.qauxv.core.HookInstaller.lambda$initializeHookForeground$0(HookInstaller.java:84)
	at io.github.qauxv.core.HookInstaller.$r8$lambda$1h6tEo2rVLwGyoNmjwMGOzB6Hd8(Unknown Source:0)
	at io.github.qauxv.core.HookInstaller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Comment by keta1** [comment]
MessageStyle 通知已经重构，请 使用 新版 模块 重新测试
