### ISSUE TITLE
[Bug] QQ侧滑栏精简功能失效

### ISSUE THREAD

**Issue by wangxue415** [cinit/QAuxiliary#896]
### Steps to reproduce/复现步骤

1.开启模块侧滑栏精简
2.重启QQ
3.再次打开QQ发下侧滑栏精简失效

### Expected behaviour/预期行为

侧滑栏被精简

### Actual behaviour/实际行为

侧滑栏保持原样

### Xposed Framework you used/你使用的Xposed框架

lsposed（1.9.2 7024）

### Your Android version/你使用的安卓系统版本

Android 14

### QQ(TIM)版本/QQ(TIM) Version

9.0.30.15995

### Module Version/模块版本

1.4.9.r1990.71a403e(1990)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1990.71a403e
QQ9.0.30(6038)
PID: 18808, UID: 10245
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke$lambda$4(SourceFile:315)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.$r8$lambda$lRWYE9U1SU48C5saeShBQ-oIbFU(SourceFile:1)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1$$ExternalSyntheticLambda0.afterHookedMethod(SourceFile:1)
	at cc.ioctl.util.HookUtils$3.afterHookedMethod(SourceFile:15)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.constructor(Unknown Source:14)
	at com.tencent.mobileqq.api.impl.DrawerApiImpl.getQQSettingMeView(P:7)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.X(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.c0(P:2)
	at com.tencent.mobileqq.qqsettingme.QQSettingMe.Y(P:3)
	at com.tencent.mobileqq.activity.home.Conversation$b.d(P:4)
	at com.tencent.mobileqq.app.FrameHelperActivity$1.d(P:10)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.w(P:6)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.onTouchEvent(P:18)
	at android.view.View.dispatchTouchEvent(View.java:15876)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
	at com.tencent.mobileqq.activity.recent.DrawerFrame.dispatchTouchEvent(P:18)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:577)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
	at androidx.core.app.ComponentActivity.dispatchTouchEvent(Unknown Source:9)
	at androidx.activity.ComponentActivity.dispatchTouchEvent(Unknown Source:9)
	at androidx.fragment.app.FragmentActivity.dispatchTouchEvent(Unknown Source:9)
	at mqq.app.AppActivity.dispatchTouchEvent(P:3)
	at com.tencent.mobileqq.app.QBaseActivity.dispatchTouchEvent(P:5)
	at com.tencent.mobileqq.app.BaseActivity.dispatchTouchEvent(Unknown Source:9)
	at com.tencent.mobileqq.activity.SplashActivity.dispatchTouchEvent(Unknown Source:9)
	at com.tencent.richframework.route.WindowCallbackWrapper.dispatchTouchEvent(P:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:535)
	at android.view.View.dispatchPointerEvent(View.java:16154)
	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7879)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7645)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7017)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7074)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7040)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7205)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7048)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7262)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7021)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7074)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7040)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7048)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7021)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10191)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10142)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10106)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10354)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:307)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:275)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10279)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10448)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1675)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1684)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1205)
	at android.view.Choreographer.doFrame(Choreographer.java:1102)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1648)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by klxiaoniu** [comment]
勾选精简了哪个/哪些选项之后出现的问题？

**Comment by wangxue415** [comment]
> 勾选精简了哪个/哪些选项之后出现的问题？

我勾选了除 我的钱包、我的收藏、我的相册、我的文件之外的所有其它选项

**Comment by klxiaoniu** [comment]
> > 勾选精简了哪个/哪些选项之后出现的问题？
> 
> 我勾选了除 我的钱包、我的收藏、我的相册、我的文件之外的所有其它选项

精确一下哪个导致的

**Comment by wangxue415** [comment]
我把所有选项尝试了一遍，均会导致报错

**Comment by Pil0tXia** [comment]
在8.9.90中也遇到了此问题。并且会导致QQ闪退回到桌面。

```
1.5.0.r2088.7b23d34
QQ8.9.90(4938)
PID: 22772, UID: 10262
xyz.nextalone.hook.DisabledRedNick
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: DexTarget: NFriendChatPie_updateUITitle
	at io.github.qauxv.util.dexkit.DexKit.requireMethodFromCache(DexKit.kt:134)
	at xyz.nextalone.hook.DisabledRedNick.initOnce(DisabledRedNick.kt:54)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:244)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8074)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7585)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7313)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by HdShare** [comment]
> 8.9.90从r2001升级到r2088后也遇到了此问题。并且会导致QQ闪退回到桌面。

推荐使用 更改好友会员，效果差不多
隐藏会员红名 失效好久了

**Comment by Pil0tXia** [comment]
@HdShare 不好意思，应该是贴错日志了。下面这段日志才是侧滑栏精简的。

```
1.5.0.r2001.597cbf1
QQ8.9.90(4938)
PID: 29224, UID: 10262
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: DexTarget: QQSettingMeABTestHelper_isZPlanExpGroup
	at io.github.qauxv.util.dexkit.DexKit.requireMethodFromCache(SourceFile:20)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke(SourceFile:34)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe.initOnce(SourceFile:3)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8074)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7585)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7313)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by HdShare** [comment]
> @HdShare 不好意思，应该是贴错日志了。下面这段日志才是侧滑栏精简的。

侧滑栏 下拉形象展示 异常，最新CI版修复了
闪退尝试使用 异常跟踪(AppErrorsTracking) 模块 查看异常堆栈
