### ISSUE TITLE
[Bug] 8.9.90 消息列表 - 禁用轻互动 失效

### ISSUE THREAD

**Issue by Pil0tXia** [cinit/QAuxiliary#903]
### Steps to reproduce/复现步骤

在QQ8.9.90-qauxv_r1876中，此净化功能就是失效的。在升级到QQ8.9.90-qauxv_r2001后，依然没有生效。

### Expected behaviour/预期行为

在消息列表的联系人会话右侧、及聊天界面的输入框上方，不再显示“戳一戳”、“晚安”等图标。

### Actual behaviour/实际行为

![Screenshot_2024-04-10-11-09-32-341_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/41445332/325241ac-c152-41d2-8c39-ed0ef1a168ad)

在消息列表的联系人会话右侧、及聊天界面的输入框上方，仍然显示“戳一戳”、“晚安”等图标。

### Xposed Framework you used/你使用的Xposed框架

lspatched 便携模式打包

### Your Android version/你使用的安卓系统版本

MIUI 14.0.8

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.90

### Module Version/模块版本

v1.5.0 r2001

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.5.0.r2001.597cbf1
QQ8.9.90(4938)
PID: 8590, UID: 10262
cc.ioctl.hook.chat.DisableLightInteraction
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at cc.ioctl.hook.chat.DisableLightInteraction.initOnce(SourceFile:66)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:9)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7832)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7343)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7076)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by klxiaoniu** [comment]
@Pil0tXia 建议更新QQ

**Comment by Pil0tXia** [comment]
@klxiaoniu 我检查了一下社区现存的bug，更新到QQ9后会遇到更多净化失效的情况，所以我个人暂时没有升级的打算。我希望等QAuxv支持对QQ9比较全面的净化之后再升级（例如#815、#834 和#813），您按照您的优先级一个一个忙就行。

**Comment by HdShare** [comment]
使用最新的CI

**Comment by Pil0tXia** [comment]
@HdShare 👍👍
