### ISSUE TITLE
[Bug] TIM 无法拦截文件在线预览

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#952]
### Steps to reproduce/复现步骤

1. 发送一个 .js 文件
2. 打开下载页面，下载
3. 下载完后会跳出预览页面并加载txt插件

### Expected behaviour/预期行为

拦截在线预览行为，阻止页面打开

### Actual behaviour/实际行为

文件被在线预览，并下载txt插件

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2

### Your Android version/你使用的安卓系统版本

Android 13

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.1

### Module Version/模块版本

1.5.0.r2031.8c50403(2031) 截至目前该功能上次更新为 6月前

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2031.8c50403
TIM3.5.1(1298)
PID: 6449, UID: 1110279
com.xiaoniu.hook.DisableDocOnlinePreview
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NoSuchMethodException: Lcom/tencent/mobileqq/filemanager/fileviewer/docs/TroopDocsPreviewConfigProcessor;->parse([B)Lcom/tencent/freesia/IConfigData;
	at io.github.qauxv.util.dexkit.DexMethodDescriptor.getMethodInstance(DexMethodDescriptor.java:208)
	at xyz.nextalone.util.HookUtilsKt.getMethod(HookUtils.kt:60)
	at com.xiaoniu.hook.DisableDocOnlinePreview.initOnce(DisableDocOnlinePreview.kt:38)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:244)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at OlbGAMXILVNVjYpOZDAq.Z.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at com.tencent.mobileqq.startup.step.Step.doStep(SourceFile:153)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at anlo.a(SourceFile:408)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(SourceFile:310)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(SourceFile:30)
	at mqq.app.AppContentProvider.onCreate(SourceFile:30)
	at cooperation.readinjoy.content.ReadInJoyDataProvider.onCreate(SourceFile:103)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8003)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7514)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7242)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2244)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.filemanager.fileviewer.docs.TroopDocsPreviewConfigProcessor" on path: DexPathList[[zip file "/data/app/~~ufALQzXPS1oiA6_5mAUkKQ==/com.tencent.tim-R2SGziw_lnKWhmxfnXOYXA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ufALQzXPS1oiA6_5mAUkKQ==/com.tencent.tim-R2SGziw_lnKWhmxfnXOYXA==/lib/arm64, /data/app/~~ufALQzXPS1oiA6_5mAUkKQ==/com.tencent.tim-R2SGziw_lnKWhmxfnXOYXA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at io.github.qauxv.util.dexkit.DexMethodDescriptor.getMethodInstance(DexMethodDescriptor.java:188)
	... 33 more

TIM包好像不存在这个类，不过我找到个可疑的，不知道是不是：
Lcom/tencent/mobileqq/filemanager/fileviewer/viewer/SimpleFileViewer;

辛苦了

**Comment by klxiaoniu** [comment]
这不是在线预览，都下载到本地了
TIM多少年没更新了，没这个功能

**Comment by MoonLeeeaf** [comment]
> 这不是在线预览，都下载到本地了 TIM多少年没更新了，没这个功能

啊...
抱歉
没看懂功能（
