### ISSUE TITLE
群文件长按转存永久在qq9.05上无法使用

### ISSUE THREAD

**Issue by Arce0416** [cinit/QAuxiliary#957]
### Steps to reproduce/复现步骤

1..打开“群文件长按转存永久”模块，出现报错
2.打开模块设置界面-故障排查-功能异常列表
3.复制日志

### Expected behaviour/预期行为

正常情况应该是能够启动的

### Actual behaviour/实际行为

报错，初始化失败，并多次尝试依旧失败

### Xposed Framework you used/你使用的Xposed框架

LSPatch

### Your Android version/你使用的安卓系统版本

android13

### QQ(TIM)版本/QQ(TIM) Version

9.0.50

### Module Version/模块版本

1.5.0.r2043.54a1f11

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2043.54a1f11
QQ9.0.50(6258)
PID: 20686, UID: 10668
cc.ioctl.hook.troop.TroopFileSaveLasting
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at me.ketal.util.HookUtilKt.findClass(HookUtil.kt:36)
	at me.ketal.util.HookUtilKt.findClass$default(HookUtil.kt:35)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:52)
	at cc.ioctl.hook.troop.TroopFileSaveLasting$startHook$1.invoke(TroopFileSaveLasting.kt:47)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at cc.ioctl.hook.troop.TroopFileSaveLasting.startHook(TroopFileSaveLasting.kt:47)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:90)
	at me.ketal.base.PluginDelayableHook$initOnce$1.invoke(PluginDelayableHook.kt:58)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(HookUtils.kt:150)
	at me.ketal.base.PluginDelayableHook.initOnce(PluginDelayableHook.kt:58)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:64)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(InjectDelayableHooks.java:244)
	at io.github.qauxv.core.MainHook.performHook(MainHook.java:135)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:67)
	at io.github.qauxv.startup.StartupHook.execStartupInit(StartupHook.java:79)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.onCreate(Unknown Source:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2482)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2452)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7933)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2287)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8370)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.troop.data.TroopFileShowAdapter
	... 47 more

**Comment by klxiaoniu** [comment]
杀后台重启QQ
