### ISSUE TITLE
[Bug] 精简加号菜单无法正常使用

### ISSUE THREAD

**Issue by kid145608** [cinit/QAuxiliary#980]
### Steps to reproduce/复现步骤

精简加号菜单-选择要精简的项目-选择任意一项或多项

### Expected behaviour/预期行为

加号菜单中被精简的项目隐藏

### Actual behaviour/实际行为

被精简的项目没有隐藏

### Xposed Framework you used/你使用的Xposed框架

LSPatch 版本 0.6 (398)  框架版本 1.9.2 (7024) 

### Your Android version/你使用的安卓系统版本

鸿蒙3.0.0.168

### QQ(TIM)版本/QQ(TIM) Version

9.0.55.16820

### Module Version/模块版本

1.5.0.r2001.597cbf1(2001)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2001.597cbf1
QQ9.0.55(6368)
PID: 31764, UID: 11003
xyz.nextalone.hook.SimplifyPlusPanel
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException
	at xyz.nextalone.hook.SimplifyPlusPanel$initOnce$1.invoke(SourceFile:15)
	at xyz.nextalone.hook.SimplifyPlusPanel$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at xyz.nextalone.hook.SimplifyPlusPanel.initOnce(SourceFile:3)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.stepForMainBackgroundStartup(SourceFile:35)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:129)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2120)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2093)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8181)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7722)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7586)
	at android.app.ActivityThread.access$2600(ActivityThread.java:259)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by klxiaoniu** [comment]
https://t.me/QAuxiliary_CI
