### ISSUE TITLE
[Bug] QQ900版本，侧滑栏异常

### ISSUE THREAD

**Issue by YiChen2025** [cinit/QAuxiliary#985]
### Steps to reproduce/复现步骤

侧滑栏异常，旧版新版都一样

### Expected behaviour/预期行为

修复，并且兼容8968开始及以上版本全兼容修复

### Actual behaviour/实际行为

测试是否正常

### Xposed Framework you used/你使用的Xposed框架

lsposed

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.0

### Module Version/模块版本

QAuxv-v1.5.0.r2071.bff8012-arm64

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1971.ec5dcea
QQ9.0.0(5282)
PID: 4300, UID: 10275
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.ClassNotFoundException: DexTarget: QQ_SETTING_ME_CONFIG_CLASS
	at io.github.qauxv.util.dexkit.DexKit.requireClassFromCache(SourceFile:20)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke(SourceFile:12)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe$initOnce$1.invoke(SourceFile:1)
	at xyz.nextalone.util.HookUtilsKt.throwOrTrue(SourceFile:9)
	at cc.ioctl.hook.sideswipe.SimplifyQQSettingMe.initOnce(SourceFile:3)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(SourceFile:8)
	at io.github.qauxv.core.InjectDelayableHooks.step(SourceFile:495)
	at io.github.qauxv.core.MainHook.performHook(SourceFile:199)
	at io.github.qauxv.startup.StartupRoutine.execPostStartupInit(SourceFile:114)
	at io.github.qauxv.startup.StartupHook.execStartupInit(SourceFile:46)
	at io.github.qauxv.startup.StartupHook$1.afterHookedMethod(SourceFile:52)
	at ZWqA.OPvoFaTnZubKihW.e.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.blockUntilFinish(Unknown Source:8)
	at com.tencent.qqnt.startup.NtStartup.c(P:30)
	at com.tencent.mobileqq.startup.director.a.A(P:6)
	at com.tencent.mobileqq.startup.director.a.z(P:2)
	at com.tencent.mobileqq.startup.director.a.q(P:6)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:8)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:2)
	at mqq.app.AppContentProvider.onCreate(P:1)
	at com.tencent.mobileqq.content.FriendListProvider.onCreate(P:1)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7805)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7052)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by klxiaoniu** [comment]
故障排查-清除缓存试一下

**Comment by SolitaryEgo** [comment]
> 故障排查-清除缓存试一下

嘻嘻，没用

**Comment by YiChen2025** [comment]
> 故障排查-清除缓存试一下

说出来你可能不信，早上八点到现在，我找3月份的qa版本都试过了都没用，反复升降测试，在9.0.0不兼容，没修复并适配，鉴于新版qq9抽风，所以每个人选择也不同，然后qa这边对于每个qq的版本(从第一版QQ9，9.0.0开始)，qa就还没全部修复bug🌚🌚

**Comment by YiChen2025** [comment]
> 故障排查-清除缓存试一下

就是想请你把全部功能排查修复下，我在最新版9.0.50也有部分常用bug[需要的话，可提供异常错误的日志]

**Comment by YiChen2025** [comment]
> 故障排查-清除缓存试一下

其余没开就不会提示错误，图中这两个是开过然后提示的
![Screenshot_2024-05-21-10-20-41-989_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/80463727/db6ce7f7-112e-44ff-99ab-75498860acb3)

**Comment by HdShare** [comment]
尝试最新CI版，QQ9.0.0+最新CI版r2109未复现

**Comment by YiChen2025** [comment]
> 尝试最新CI版，QQ9.0.0+最新CI版r2109未复现

OK。900测试结果👌，没大问题了
![IMG_20240606_094712](https://github.com/cinit/QAuxiliary/assets/80463727/3ec8db53-1b91-468d-8604-f2c66f07e870)
![Screenshot_2024-06-06-10-04-14-381_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/80463727/0a622753-4a41-48e8-aaf5-93aa6ff4121c)

**Comment by YiChen2025** [comment]
> 尝试最新CI版，QQ9.0.0+最新CI版r2109未复现

对了，还想反应一个，就是防撤回这个功能的，能否优化下
1.即使阻止到了，这个提示"没收到"，就删除了，保留正确的阻止提示
2.有时候即使qq在前台聊天，切其他群聊看消息，忽然看到某些较近消息出现未防到撤回，一直提示没收到，但是对方消息确实是发送过然后撤回的。然后还有一种就是跟假离线状态一样，仿佛进入离线状态部分被对方撤回的消息，也没法防到撤回，qq长时间挂后台，杀后台或者没被杀后台，时间长了再去看下消息，也是提示"没收到"
![Screenshot_2024-06-06-10-13-01-715_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/80463727/e71dde2b-1fa0-4036-9393-ffdea912e2ad)

![Screenshot_2024-06-06-10-11-32-890_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/80463727/5d0a5752-a434-4ae6-a7d5-d7e76344eed7)
