### ISSUE TITLE
[Bug] “图片/表情包自定义概要”功能在QQ 9.0.56导致自定义表情发送失败

### ISSUE THREAD

**Issue by Just-Prog** [cinit/QAuxiliary#991]
### Steps to reproduce/复现步骤

1. QA设置-辅助功能-聊天消息-开启“图片表情包自定义概要”功能并设置概要文字
2. 在表情界面选择“自定义表情”点击发送

### Expected behaviour/预期行为

正常发送

### Actual behaviour/实际行为

显示无法发送，主体表情图片缺失或概率性显示上一次发送的图片/表情

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2 (7058)

### Your Android version/你使用的安卓系统版本

Android 14 (API 34) / HyperOS OS1.0.4.0.ULFCNXM

### QQ(TIM)版本/QQ(TIM) Version

9.0.56

### Module Version/模块版本

v1.5.0.r2073.b08c39a

### Version and Other Requirements/版本和其他要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志
```
java.lang.NoSuchFieldException: field 'd' not found in com.tencent.qqnt.aio.msg.element.AIOElementType$e
	at cc.ioctl.util.Reflex.findField(Reflex.java:1210)
	at cc.ioctl.util.Reflex.setInstanceObject(Reflex.java:995)
	at cc.ioctl.util.Reflex.setInstanceObject(Reflex.java:989)
	at xyz.nextalone.util.HookUtilsKt.set(HookUtils.kt:198)
	at cc.microblock.hook.ImageCustomSummary.initOnce$lambda$0(ImageCustomSummary.kt:65)
	at cc.microblock.hook.ImageCustomSummary.$r8$lambda$H_hfk8MG7atJ8jbzqA1QPJdJCrU(ImageCustomSummary.kt:0)
	at cc.microblock.hook.ImageCustomSummary$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at com.github.kyuubiran.ezxhelper.utils.HookUtilsKt$hookBefore$1.beforeHookedMethod(HookUtils.kt:54)
	at QcjXdChSDLPpFwAkCccVhq.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:180)
	at LSPHooker_.k0(Unknown Source:17)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.l0(P:1)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.p0(P:3)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.U(P:6)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.H(P:11)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.m(P:1)
	at com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate$b.call(P:1)
	at com.tencent.mvi.runtime.wrapper.LifeCycleAction1Wrapper.call(Unknown Source:24)
	at com.tencent.mvi.base.route.VMMessenger$send$1.invoke(P:13)
	at com.tencent.mvi.base.route.VMMessenger$send$1.invoke(P:1)
	at com.tencent.mvi.base.route.VMMessenger.r(P:2)
	at com.tencent.mvi.base.route.VMMessenger.s(P:1)
	at com.tencent.mvi.base.route.VMMessenger.f(P:1)
	at com.tencent.aio.runtime.b.f(Unknown Source:23)
	at com.tencent.mobileqq.aio.l.a.d.i(P:3)
	at com.tencent.qqnt.aio.api.e$a$a.a(P:1)
	at com.tencent.qqnt.aio.adapter.emoticon.NTEmoticonPanelProvider$sendFavPicEmotion$1$2.run(P:3)
	at mqq.os.MqqHandler.handleCallback(P:1)
	at mqq.os.MqqHandler.dispatchMessage(P:4)
	at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:1)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by CATBirdlong** [comment]
+1
**发生了一致的问题**
_出现在版本9.0.56_
已成功确认是模块问题(或模块与该qq版本不兼容导致)
0err_0war_all t
启用安全模式可恢复

**Comment by HdShare** [comment]
使用最新的CI

**Comment by Just-Prog** [comment]
> 使用最新的CI

fixed
